### ISSUE TITLE
[Language Server] Notifications about supported languages (and syntax highlighting)

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/xtext-core#1001]
I know syntax highlighting is a client thing #283, but it would be nice to have a language server that can notify connecting clients about the languages (and maybe keywords or other information about the languages).
I use a language server that supports multiple DSLs that may change over time and Theia as a client.

Is this something you plan to add, is it out of question (as mentioned in #283), or does this already work via semantic coloring (the syntax highlighting part)?

**Comment by cdietrich** [comment]
cc @kittaakos can you help out here?

**Comment by kittaakos** [comment]
@soerendomroes, although the [semantic highlighting extension](https://github.com/Microsoft/vscode-languageserver-node/pull/367) is not yet part of the LSP, LSP4J has the API for it with `@Beta`. See [here](https://github.com/eclipse/lsp4j/blob/1a5507d96601199ef20b7129068ae5a5f295482d/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/LanguageClient.java#L136).

[Here](https://github.com/theia-ide/yang-lsp/pull/143/files#diff-c64ca45dbd4fce8c4fa78df4fc9c87a4), you can find a reference implementation for [YANG 1.1](https://tools.ietf.org/html/rfc7950) with Xtext. Please note, there are [known limitations](https://github.com/theia-ide/theia/issues/2906) this point in Theia. Also, you have to [define your TextMate grammar](https://github.com/theia-ide/yangster/pull/65/files#diff-1bc3b9eb7601249eefb6de6519d94fb7) with the scopes.

**Comment by soerendomroes** [comment]
Ok, I already looked into that, but it does not seem useful for my context, since keywords of the language are still hard coded in the TextMate grammar. Currently I use an LS-extension that responses with the keywords for the languages and dynamically adds syntax highlighting.
Back to my question: Is it planed to add a notification to inform the client which languages the LS supports? This seems to be a useful feature to me.

**Comment by cdietrich** [comment]
i still dont see what problem that solves:
- the packaging of ls is client specific so it already knows the languages anyway cause you have to define what languages exist in all clients
- the keywords for client side highlighting and the one from server side highlighting dont need to relate. so the server will send the highlighting regions for the keywords as well. so an empty list or some dummy keywords in the textmate grammar should be sufficient

**Comment by soerendomroes** [comment]
Ok, I did not know that the keywords where not relevant, thank you :)
