### ISSUE TITLE
generateTestLanguages does not work in combination with clean build

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1003]
am not sure if. e.g. extras is affected too
`./gradlew clean build -PuseJenkinsSnapshots=true generateTestLanguages --gradle-user-home=.g`

```
Caused by: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on classpath. URI was 'classpath:/org/eclipse/xtext/generator/ecore/SuperTestLanguage.xtext'
	at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.findResourceOnClasspath(ClassloaderClasspathUriResolver.java:61)
	at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.resolve(ClassloaderClasspathUriResolver.java:46)
	... 17 more

```

**Comment by cdietrich** [comment]
i wonder if this ever worked.

**Comment by cdietrich** [comment]
problem is here: test.finalizedBy(cleanupEcoreFiles)
but this means that generateTestLanguages runs after test and not before

**Comment by cdietrich** [comment]
@oehme do you have a hint.
how can i sort generateTestLanguages before testCompileJava?
but access the resources on classpath?

**Comment by cdietrich** [comment]
maybe something like

```
task generateTestLanguages(type: XtextGeneratorTask) {
	workflow = file('src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2')
	outputs.dir 'src-gen'
	mustRunAfter "processTestResources"
}

tasks.withType(Test) {
	mustRunAfter "generateTestLanguages"
}
```

**Comment by oehme** [comment]
You need to specify the inputs, e.g.

```
generateTestLangs {
  inputs.files(processResources.outputs)
}

compileJava {
  source(generateTestLangs.outputs)
}
```

**Comment by cdietrich** [comment]
@oehme doent that for a generateTestLanguages

**Comment by oehme** [comment]
Not sure what you mean by "force"?

**Comment by cdietrich** [comment]
wont that lead the generateTestLanguages task needs to be executed for compile.
what i want is: if generateTestLanguages is executed (manually) that then if "build" is excuted as well. that then the generateTestLanguages happens before test

**Comment by oehme** [comment]
Sorry, I meant to put `test` in the snippet above, not `compileJava`

**Comment by oehme** [comment]
> wont that lead the generateTestLanguages task needs to be executed for compile.

Of course, they are an input to compilation after all.

> if generateTestLanguages is executed (manually)

Nothing in a build should require manual intervention. If I say `test`, everything needed for the tests should be built.

**Comment by cdietrich** [comment]
We have checked in stuff and generation is optional. Generation takes too long and should not happen on a every build basis

**Comment by oehme** [comment]
> Generation takes too long and should not happen on a every build basis

That's what up-to-date checking is for :)

**Comment by cdietrich** [comment]
Yes but that’s a different topic. We are too far away from using such features and don’t have the manpower to work on it

**Comment by cdietrich** [comment]
Extras has the same issue.

**Comment by oehme** [comment]
> We are too far away from using such features and don’t have the manpower to work on it

What do you mean by "too far away"? You need to specify the inputs and outputs of that task. The inputs are the DSL sources and mwe dependencies and the outputs are the generated classes/resources. You already do this for the example builds, so why not here?

**Comment by cdietrich** [comment]
jenkins creates machines and thus daemons randomly. => there is no stable situation when local caching is actualy used => we would have to use shared cache

**Comment by oehme** [comment]
So not even CI runs the test language generation? How do you know it's not broken at any time?

**Comment by cdietrich** [comment]
exactly

**Comment by oehme** [comment]
Installing the [cache node](https://hub.docker.com/r/gradle/build-cache-node/) is just a docker container away btw.

**Comment by cdietrich** [comment]
on eclipse infrastructure ....

**Comment by oehme** [comment]
Why? It doesn't have to be on their infrastructure, itemis can host it or you can put it on AWS in a datacenter near the Eclipse servers.

**Comment by cdietrich** [comment]
will talk to the team about that

**Comment by cdietrich** [comment]
move to 2.22

**Comment by cdietrich** [comment]
move to 2.24

**Comment by cdietrich** [comment]
as we no longer build with gradle this is no longer an issue
