### ISSUE TITLE
[Wizard] Investigate if Mwe.launch can be managed by bom only

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1005]
[Wizard] Investigate if Mwe.launch can be managed by bom only
currently the wizard created an explizit version to pom and gradle file as well

**Comment by kthoms** [comment]
Wizard creates currently 
```
dependencies {
    mwe2 "org.eclipse.emf:org.eclipse.emf.mwe2.launch:2.10.0-SNAPSHOT"
   ...
```
for Gradle projects to build.gradle

and 
```
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.mwe2.launch</artifactId>
			<version>2.10.0-SNAPSHOT</version>
			<optional>true</optional>
		</dependency>
```
in Maven projects in the runtime module.

Since MWE artifacts are managed by the BOM, the declaration of a version becomes obsolete.

The wizard should not create versions for mwe2.launch to to build descriptors.

**Comment by cdietrich** [comment]
the answer is: yes it can. => fixed
