### ISSUE TITLE
[wizard] Configure lineDelimiter for CodeConfig

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#101]
The property CodeConfig#lineDelimiter determines the delimiter to use for generated text files and newly also for the manifest file (see bug#378980). The default value is system dependent, which could result in alternating changes to the manifest file, or if checked in also for generated code.

Therefore it is better to set this property, like the encoding, explicitly. The wizard should take the value configured in the workspace preferences as default and add the lineDelimiter property to the MWE2 workflow.

**Comment by spoenemann** [comment]
That would require extensions to both xtext-core (`org.eclipse.xtext.xtext.wizard`) and xtext-eclipse (`org.eclipse.xtext.xtext.ui`).

**Comment by kthoms** [comment]
Fixed in 2.11
