### ISSUE TITLE
MergableManifest produces surprising results

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-core#1018]
Renerating Xtends yields this diff:
```
  org.eclipse.xtend.ide.hyperlinking;x-internal:=true,
- org.eclipse.xtend.ide.internal;x-friends:="org.eclipse.xtend.ide.tests,
-   org.eclipse.xtend.ide.swtbot.tests",
+ org.eclipse.xtend.ide.internal;x-friends:="org.eclipse.xtend.ide.tests,  org.eclipse.xtend.ide.swtbot.tests",
```

**Comment by ArneDeutsch** [comment]
Hmmm ... functionally wise it should not make any difference. Internally a newline followed by blank will merge the two lines into one anyway. But I see that a diff is not nice. I will have a look if I can generate differently. Do you consider this an urgend or more as a minor issue?

**Comment by szarnekow** [comment]
It's a minor issue. Just caught my attention after I regenerated all the things (tm). If we want to keep it as is, we should regenerate the test langs to avoid diffs later on, that are unrelated.

**Comment by cdietrich** [comment]
@ArneDeutsch 
is this fixed now?

**Comment by ArneDeutsch** [comment]
Fixed.
