### ISSUE TITLE
[Language Server] Performance issue: publishDiagnostic on startup for whole workspace

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/xtext-core#1019]
I am not sure if this is a problem of my client or of the langauge server: 
When I open a new workspace and a new initialize request is sent my language server sends diagnostics for all files in the workspace. This causes severe performance issues. Is this something I can turn of or does the initilize message somehow provoke this?
This is the initialize message:
```{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"rootPath"<rootPath>,"rootUri":<rootUri>,"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"]}},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true},"implementation":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true}}},"trace":"off","workspaceFolders":[{"uri":<uri>,"name":<name>}],"processId":14228}}```

**Comment by soerendomroes** [comment]
Here some more information: I am using Theia as a client and use xtext 2.16 to build a language server. After I open the first file the language server is started and seems to parse all files in my workspace. I waited 20min and no reply to the initialize request was send and the LS was still busy doing something. If I use a smaller workspace this problem does not occur. The Client does not explicitly send request to get diagnostics.

**Comment by cdietrich** [comment]
Did you increase memory for the server ?

**Comment by cdietrich** [comment]
See https://github.com/eclipse/xtext-core/issues/516 as well

**Comment by cdietrich** [comment]
I assume you can customize the behavior by not validating on initialize

**Comment by soerendomroes** [comment]
I did not increase memory but I will try whether this helps.

**Comment by soerendomroes** [comment]
I have only ~7k files. Maybe I will try a medium sized workspace with only several hundreds.

**Comment by soerendomroes** [comment]
More memory for a smaller, but still big, workspace seems to work, but it still needs several minutes to complete, where can this feature be turned of? I think it would be enough to parse files that are explicitly opened.
Why is this only a problem for the language server? I think a normal eclipse product should runin the same issues or is this handled differently?

**Comment by cdietrich** [comment]
Is the problem the validation or the publish?

As i said you need how you can Change org.eclipse.xtext.ide.server.WorkspaceManager.initialize(URI, (URI, Iterable<Issue>)=>void, CancelIndicator)
or
org.eclipse.xtext.ide.server.LanguageServerImpl.publishDiagnostics(URI, Iterable<? extends Issue>)
(which is private unfortunately

**Comment by cdietrich** [comment]
can you provide a profiling yourkit preferred, maybe jvisualvm?

**Comment by soerendomroes** [comment]
The initialize is the problem, the publishDiagnostics notification is not sent.

**Comment by cdietrich** [comment]
=> you need to profile

**Comment by soerendomroes** [comment]
Ok, I attached YourKit to my language server, what exactly do you need? Memory consumption?

**Comment by cdietrich** [comment]
CPU profiling, and memory snapshot if you have both

**Comment by soerendomroes** [comment]
Is this sufficient?
[Chart--CPU-time.txt](https://github.com/eclipse/xtext-core/files/2836252/Chart--CPU-time.txt)

[Chart--Heap-memory.txt](https://github.com/eclipse/xtext-core/files/2836256/Chart--Heap-memory.txt)

**Comment by cdietrich** [comment]
dont know these files formats
actually having a snapshot file is what i preferr

**Comment by soerendomroes** [comment]
Snapshot file is too big...

**Comment by cdietrich** [comment]
can you share it with google drive / ms drive etc?

**Comment by cdietrich** [comment]
cpu snapshot only would help and should not be too big.

**Comment by soerendomroes** [comment]
Right, just change the file-extension
[kieler.exe-2019-02-06(1).snapshot.txt](https://github.com/eclipse/xtext-core/files/2836285/kieler.exe-2019-02-06.1.snapshot.txt)

**Comment by soerendomroes** [comment]
I can send you the memory snaphsot via wetransfer if that is okay for you.

**Comment by cdietrich** [comment]
you need to do actually do a cpu profilig for me to get suffient data.
but why i can see is that memory is at limit
=> can you try e.g. 2gb istead of 1GB

**Comment by soerendomroes** [comment]
[kieler.exe-cpu-2019-02-06.snapshot.txt](https://github.com/eclipse/xtext-core/files/2836318/kieler.exe-cpu-2019-02-06.snapshot.txt)

**Comment by cdietrich** [comment]
there are no obvious bottlenecks => please try with 2gb

**Comment by soerendomroes** [comment]
[kieler.exe-cpu-2019-02-06(GB2).snapshot.txt](https://github.com/eclipse/xtext-core/files/2836344/kieler.exe-cpu-2019-02-06.2.snapshot.txt)

**Comment by cdietrich** [comment]
please set Xms to 2GB too. i dont see where it actually makes use of the two gb.
and again start with cpu profing
will find time to look into maybe next week

**Comment by soerendomroes** [comment]
Memory snapshot from a new minute in:
https://drive.google.com/open?id=13Z4fZkw-1oHNQeJN_Lk4Wjd3wiixzMP-

**Comment by cdietrich** [comment]
did you try with Xms 2GB?

**Comment by soerendomroes** [comment]
[kieler.exe-2019-02-06(cpuXms2GB).snapshot.txt](https://github.com/eclipse/xtext-core/files/2836381/kieler.exe-2019-02-06.Xms2GB.snapshot.txt)

**Comment by soerendomroes** [comment]
No, but you will get that too. Is it relevant to you how long the LS runs before I take a snapshot?

**Comment by soerendomroes** [comment]
Memory Xms2GB:
https://drive.google.com/open?id=1HLzpqhVNJGRwl2iZaMP23ECxJLGuWxIf

**Comment by cdietrich** [comment]
and cpu with that?

**Comment by soerendomroes** [comment]
the cpu snapshot I send before should be from the same run

**Comment by soerendomroes** [comment]
I can send you another one after on hour of running (if the language server needs this long to connect)

**Comment by cdietrich** [comment]
looks like your scoping is quite cpu intense.
are you sure the very same doesnt take as long ran from eclipse?

**Comment by cdietrich** [comment]
i would test this locally with e.g. vscode (or even a unit test)

**Comment by soerendomroes** [comment]
Yes, if I start the eclipse product it is no problem to open this workspace. Running the eclipse product as a langauge server however causes this problem.

**Comment by cdietrich** [comment]
and you did not do any performance optimizations specific for eclipse and restrict eclipse memory the same way as you do it lsp and you have one project only

**Comment by soerendomroes** [comment]
I have one project only and applied the same memory restrictions. The eclipse application is ready in several seconds. The LS in 30+. I am not sure about performance optimizations for eclipse but I will look into that.

**Comment by cdietrich** [comment]
=> please do intense cpu prodiling and see whats the difference

**Comment by cdietrich** [comment]
it may be that the lsp impl does bad usage of the Xtext index
which does not happen in eclipse. 
but on the first glance i dont see that.
i would expect the same in eclipse if you do a clean build on the project

**Comment by soerendomroes** [comment]
Our serializer in the eclipse product is somehow optimized.

**Comment by cdietrich** [comment]
no i see only QualifiedNameProvider / Scoping

**Comment by soerendomroes** [comment]
We also do scoping, but not to boost performance. Tomorrow I can give a more detailed answer about that.

**Comment by soerendomroes** [comment]
This is the profiling data for the ecplise product:
https://drive.google.com/open?id=1qwYJA1xaK00fNx5I7myHSPLS-kVRsOpF
https://drive.google.com/open?id=11c9UAy0He457a-EXKvR2DyUSTvbKkYny

**Comment by cdietrich** [comment]
i dont see a build happening in eclipse

**Comment by soerendomroes** [comment]
Oh, I misread your comment, you need a profiling snapshot during the build of the eclipse product and not a profiling snapshot of the eclipse product. Why would that help? I am not sure if I understood correctly what you need. Do you want me to import the big project into the eclipse product and profile what happens?
I cannot profile the creation of this workspace in the eclipse product, since it is too quick, it just happens. 
When I use the LS instead it needs a long time until the publishDiagnostic messages are even (in a remotely large workspace). I don't think that this is desired behavior, since seems to functions without it.

**Comment by cdietrich** [comment]
(1) start eclipse
(2) start cpu profiling
(3) clean build
(4) stop profiling

also having an additional profiling with call counting in both cases would be nice

**Comment by soerendomroes** [comment]
We do not have xtetx nature and xtext builder in our eclipse product, since this caused issues in the past :)

**Comment by cdietrich** [comment]
so you dont actually build in eclipse? how can your dsl then work?

**Comment by soerendomroes** [comment]
Ok, know I think I know how we handle that:
We have our own `ResourceSet` and compiler for our dsls. So I think what we need is a way to configure the language server to use that instead.

**Comment by soerendomroes** [comment]
More information:
We have our own resources and manage our own ResourceSet. 
My question is:
Who makes the workspace opened by the LS a Xtext project and how can we disable that?
Is the problem that we use a LS eclipse product and eclipse does this automatically or does the `LanguageServerImpl` do that?

**Comment by cdietrich** [comment]
your client (in that case theia) does that

**Comment by cdietrich** [comment]
i dont know what happes if you do nothing on initialize call with a folder

**Comment by soerendomroes** [comment]
Ok, is the problem the rootUri/Path or the workspaceFolders which results in the creation of a Xtext project?

**Comment by cdietrich** [comment]
yes. its not a xtext project as in eclipse but "a folder where xtext searches for files and tries to build them"

**Comment by soerendomroes** [comment]
My current solution is to set the workspaceManager in the `LanguageServerImpl` to a subclass of the `WorkspaceManager` that overrides the `initialize` method to not set the `baseDir` and the `issueAcceptor`

**Comment by soerendomroes** [comment]
Is the `baseDir` only used to create this folder where xtext searches for stuff or tries to build it or are there other uses that I might disable by not setting it?

**Comment by cdietrich** [comment]
i dont know. you have to try.
