### ISSUE TITLE
Potential memory leak caused by threadlocal

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-core#1021]
In `org.eclipse.xtext.validation.AbstractDeclarativeValidator.state` we are using thread local to hold the state. The problem I currently see, is that in eclipse runtime, where long running Worker threads are used, this could cause a memory leak.

In my case two worker threads (waiting state) still holds the whole Xtext model. The language is a bit "complex" so it cause overall (NodeModel etc.) ~300 Mb wasted space.

Is there a place where we clean up/ reset the state after the validation job finished successfully?

**Comment by szarnekow** [comment]
Looks like it should be reset in `org.eclipse.xtext.validation.AbstractDeclarativeValidator.MethodWrapper.invoke(State)`

**Comment by dhuebner** [comment]
@szarnekow Thanks for the hint! Will look into it tomorrow

**Comment by cdietrich** [comment]
@szarnekow wont that break org.eclipse.xtext.validation.AbstractDeclarativeValidator.getContext()

**Comment by szarnekow** [comment]
Sorry, I'm confused. The method in the validator does already reset the context. Maybe I'm missing something but the validator itself should already clear the threadlocal. I wouldn't expect a change to be necessary.

**Comment by cdietrich** [comment]
@szarnekow i dont see the reset place. which one do you mean:
the entry one:
org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(EClass, EObject, DiagnosticChain, Map<Object, Object>)

**Comment by szarnekow** [comment]
From my understanding it all happens in `org.eclipse.xtext.validation.AbstractDeclarativeValidator.MethodWrapper.invoke(State)`

**Comment by cdietrich** [comment]
that is what i see as well. thus i wonder whats different in @dhuebner usecase

**Comment by kthoms** [comment]
@dhuebner could you have your colleagues have a closer look at your case?

**Comment by dhuebner** [comment]
It's really difficult to debug/profile the method is called very often and is final. I still can't say how it's possible, but that what I see in YourKit (state.currentObject holds the model):
 
<img width="1269" alt="bildschirmfoto 2019-02-08 um 10 18 16" src="https://user-images.githubusercontent.com/454322/52469309-60715780-2b8b-11e9-8b08-443f2be78d42.png">

**Comment by dhuebner** [comment]
What I found in web, people say one should call remove and `set(null)` seem not be enough. 
> You should always call remove because ThreadLocal class puts values from the Thread Class defined by ThreadLocal.Values localValues; This will also cause to hold reference of Thread and associated objects.

**Comment by dhuebner** [comment]
@szarnekow What do you think?

**Comment by cdietrich** [comment]
is this the builder threads? or for the editor? or for some jobs you start

**Comment by szarnekow** [comment]
> @szarnekow What do you think?

It should be refactored to remove for sure. Still I wonder why it captures the state given that set(null) effectively discards its value from the map, too.

**Comment by szarnekow** [comment]
Do you use this guy somewhere in yr code? 
`org.eclipse.xtext.validation.AbstractDeclarativeValidator.StateAccess`

**Comment by dhuebner** [comment]
@cdietrich Builder i think. I also tried to set the break point in AbstractDeclValidator at line 315 with condition:

`this.state.get() != null`

It never breaks.... So the wrapper seem to work fine. The only GC root it the treadlocal map, so I can't explain how it can happen :(

**Comment by dhuebner** [comment]
> Do you use this guy somewhere in yr code?

yes... No idea why the colleague used, need to investigate

**Comment by dhuebner** [comment]
@szarnekow StateAccess, that was it :-/ 

After `delegate.validate(model)` the `state.currentObject` was still there. The `delegate` validator itself was a subclass of ADV, having an own validate method. So the MethodWrapper was never called to clean up the threadlocal.

Thanks for all  your help guys. I will close the issue, but we probably should point the user (javadoc?) that manually accessing the State could cause a memory leak.
