### ISSUE TITLE
Missing validation: Entry rule cannot be a fragment

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-core#1034]
The Grammar workflow breaks if the first rule is a fragment. There is a missing validation for that. Should be a warning by default.

**Comment by cdietrich** [comment]
@szarnekow for non parser rules it is already an error?
so should it be here the same?

**Comment by szarnekow** [comment]
I’m not sure. Error by default is sane, but I’m not certain whether it should be configurable.

**Comment by cdietrich** [comment]
we have this rule but terminals does not stick to it :)

**Comment by szarnekow** [comment]
Challenge is, that it’s mostly the mwe2 config, that dictates what is valid or not

**Comment by loradd** [comment]
Hi everybody, I would like to start contributing. Can I work on this issue?

**Comment by kthoms** [comment]
@loradd That‘ll be awesome! Please ask when you need assistance.

**Comment by szarnekow** [comment]
Sorry but @epoell is already on it

**Comment by miklossy** [comment]
@loradd How about working on a similar issue, such as [#410479](https://bugs.eclipse.org/bugs/show_bug.cgi?id=410479) ?

**Comment by loradd** [comment]
@miklossy I can work on [#410479](https://bugs.eclipse.org/bugs/show_bug.cgi?id=410479). Thank you!

**Comment by szarnekow** [comment]
Fix was merged into master. Thank you @epoell
