### ISSUE TITLE
Child grammar rules of inactive rules become active

### ISSUE THREAD

**Issue by tkutz** [eclipse/xtext-core#1035]
Consider the following grammar:
```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	greetings+=Greeting*;

Greeting:
	'hi' name=ID'!';

Inactive:
	greet=InactiveToo '!';

InactiveToo:
	'hello' name=ID;
```

Although the rule `Inactive` and `InactiveToo` are not used, writing `hi hello !` gives an error message:
![bildschirmfoto 2019-02-14 um 12 17 44](https://user-images.githubusercontent.com/2589669/52787235-7c7a6a80-305d-11e9-8446-2c9650fc4a67.png)

In case there is no indirection, the rule stays inactive as expected. This means, with this grammar:
```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	greetings+=Greeting*;

Greeting:
	'hi' name=ID'!';

Inactive:
	'hello' name=ID '!';
```
I can write `hi hello!` without any errors, means `hello` is considered an ID again.

**Comment by tkutz** [comment]
Further observation:

In the first case, InternalMyDsl.g contains a rule for `InactiveToo`, while in the second case it does not contain any rule for `Inactive`. Looks like an issue in the generator from Xtext to Antlr.

**Comment by cdietrich** [comment]
problem can be circumvented using

```
			parserGenerator = {
				options = {
					skipUnusedRules = true
				}
			}
```

**Comment by szarnekow** [comment]
We wont change the default behavior that’s present since 0.7
