### ISSUE TITLE
Mergable Manifest Problem

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1038]
(1) run `xtext-core/org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/GenerateTestLanguages.mwe2` (e.g. via gradlew generateTestLanguages
(2) `xtext-eclipse/org.eclipse.xtext.testlanguages.ui/META-INF/MANIFEST.MF`is broken now

```
 org.eclipse.xtext.junit4,
 org.eclipse.xtext.xbase.testing,
 org.eclipse.xtext.xbase.junit,
 
Import-Package: org.apache.log4j;version="1.2.15",
```

org.eclipse.xtext.xtext.generator.junit.JUnitFragment.generate()
adds "" as xbase testing package. i assume we have to be more resilient against such things

**Comment by cdietrich** [comment]
@ArneDeutsch @szarnekow problem seems to be caused by the recent change about preserving whitespace

**Comment by cdietrich** [comment]
possible solution

```
			while (lineIndex < lines.size() && lines.get(lineIndex).startsWith(" ")) {
				String l = lines.get(lineIndex);
				if (!l.trim().isEmpty()) {
					line += newline + l;
				}
				lineIndex++;
			}
```

**Comment by ArneDeutsch** [comment]
Will handle this.

**Comment by ArneDeutsch** [comment]
Done.
