### ISSUE TITLE
[ide] Bogus serialization when reassign container 

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-core#1043]
See org.eclipse.xtext.ide.tests.serializer.ChangeSerializerTest.testMoveElement()

```
#22 {
	child1
	children1 {
		child2 jumper
	}
}
```
Adding `jumper` as sibling of `child1` doesn't work.

**Comment by dhuebner** [comment]
We should also check  eclipse/xtext#2565

**Comment by szarnekow** [comment]
I'm not sure about the impact of your changes, but please bear in mind that we are already close to 2019-3 - so maybe this should be postponed to 2.18 to allow for more involving testing?

**Comment by dhuebner** [comment]
I know, therefore I didn't assigned a milestone.
I don't think we can use the 2.17 in our project anyway.
Would be nice to have a bugfix release for an older version aka LTS

**Comment by szarnekow** [comment]
Makes sense. I don't that anybody would object having a maintenance release.

**Comment by cdietrich** [comment]
@dhuebner is this fixed now?

**Comment by dhuebner** [comment]
@cdietrich Yes
