### ISSUE TITLE
Fix WorkspaceSymbolTest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1048]
Fix WorkspaceSymbolTest

https://ci.eclipse.org/xtext/view/Xtext-release/job/xtext-core/job/master/278/testReport/junit/org.eclipse.xtext.ide.tests.server/WorkspaceSymbolTest/testSymbol_01/

![wst](https://user-images.githubusercontent.com/238736/53299469-fcad8680-383a-11e9-9b14-5b9e16bb7e26.png)

cc @tivervac

**Comment by cdietrich** [comment]
After restart locally the test was green again. same on server it staid red. on typefox js it is grren

**Comment by cdietrich** [comment]
to reproduce locally

(1) run all tests
(2) run the failing test only

=> seems order dependent

**Comment by cdietrich** [comment]
@kthoms @tivervac can it be that there are other tests that dont cleanup too?

**Comment by cdietrich** [comment]
WorkspaceManagerTest does not 
=> (1) WorkspaceManagerTest
=> (2) WorkspaceSymbolTest fails

**Comment by kthoms** [comment]
Decided with @szarnekow to disable the test for M3 and investigate after that.

**Comment by cdietrich** [comment]
@kthoms i have a pr on the way with the fix

**Comment by kthoms** [comment]
OK, even better :) You don't exactly know what "vacation" is about?

**Comment by kthoms** [comment]
PR fixes the issue.

**Comment by tivervac** [comment]
> @kthoms @tivervac can it be that there are other tests that dont cleanup too?

Definitely
