### ISSUE TITLE
Evaluate build dependency to xtext-extras

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-core#1066]
One MWE2 file has a build time dependency to a class from a project out of `xtext-extras`. Evaluate if this dependency is really needed and if we can git rid of it somehow.

Plugin: `org.eclipse.xtext.tests`, package `org.eclipse.xtext`, file `GenerateAllTestLanguages.mwe2`, line `47`: `bean = org.eclipse.xtext.ecore.EcoreSupport {}`

The class `EcoreSupport` is form `xtext-extras` in project `org.eclipse.xtext.ecore`.

**Comment by cdietrich** [comment]
@ArneDeutsch do you know why `org.eclipse.xtext.testlanguages.ecore.EcoreSupport` is not used

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/issues/834

**Comment by cdietrich** [comment]
i assume this has the same cause as https://github.com/eclipse/xtext-core/issues/1003

**Comment by cdietrich** [comment]
Fixed in 2.18
