### ISSUE TITLE
[LS] As an LS extension developer, I would like to access the Xtext index

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#1067]
As an LS extension developer (`ILanguageServerExtension`), I can load any Xtext resource given by its URI via the `ILanguageServerAccess`. I would like to access the Xtext index, and read its content, in such a convenient way. The index can be retrieved from the `WorkspaceManager` but injecting it into my LS extension is not an option, I would get different instances.

I propose extending the `ILanguageServerAccess` API with something like this:
```java
def CompletableFuture<Void> doReadIndex(Consumer<IResourceDescription> consumer)
```

**Comment by cdietrich** [comment]
@kittaakos any news on this issue?

**Comment by kittaakos** [comment]
> any news on this issue?

The [PR is ready](https://github.com/eclipse/xtext-core/pull/1051), but conflicting. Unfortunately, I won't have time to work on this until the next week, apologies. I have a couple of other Xtext-related things on my TODO list as well, can we please come back to this next week?

If it is urgent, please take over the PR, I doubt there is anything you cannot solve without me :)

**Comment by cdietrich** [comment]
no, next week is completly fine. release is planned in the first week of june
