### ISSUE TITLE
Follow up GSON update in LSP4J

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1077]
Follow up GSON update in LSP4J

https://github.com/eclipse/lsp4j/issues/309

**Comment by cdietrich** [comment]
TODO: org.eclipse.xtend.caliper.tests seems to embedded old gson. investigate if we can do something about too

**Comment by cdietrich** [comment]
also org.eclipse.xtext.web.servlet should be investigated for a newer version / bom managed one

**Comment by cdietrich** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19276

**Comment by cdietrich** [comment]
@szarnekow can you share some insights how caliper and gson interact with each other?

**Comment by szarnekow** [comment]
Caliper allows to serialize the performance test results as json and upload it to some server. We should drop the caliper tests and (if necessary) replace them by jmh tests.
