### ISSUE TITLE
Update to LSP4J 0.8.0 Final

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1082]
This time we should try to be in sync with the release train and update to LSP4J 0.8.0 Final before the release

cc @spoenemann @kittaakos

**Comment by cdietrich** [comment]
@spoenemann @kittaakos  is there already a planned release date for lsp4j 0.8.0?

**Comment by spoenemann** [comment]
https://github.com/eclipse/lsp4j/issues/316#issuecomment-490415825

**Comment by cdietrich** [comment]
=> move the 0.8.0 update to 2.19

**Comment by cdietrich** [comment]
0.7.1 is on 2.18 now

**Comment by cdietrich** [comment]
(needed for full guava compatibility)

**Comment by cdietrich** [comment]
Planned release date is 22.8

**Comment by cdietrich** [comment]
declarationProvider in sever capabilities

**Comment by cdietrich** [comment]
Fixed in 2.19
