### ISSUE TITLE
Incorrect handling of tycho.testArgLine in the generated POMs

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#1087]
I think the way tycho.testArgLine is used in the generated POMs is not completely correct.

In the parent POM the property is set to empty

```
<tycho.testArgLine></tycho.testArgLine>
```

and used in the general configuration of tycho-surefire in the pluginManagement section

```
<plugin>
	<groupId>org.eclipse.tycho</groupId>
	<artifactId>tycho-surefire-plugin</artifactId>
	<version>${tychoVersion}</version>
	<configuration>
		<!-- THE FOLLOWING LINE MUST NOT BE BROKEN BY AUTOFORMATTING -->
		<argLine>${tycho.testArgLine} ${platformSystemProperties} ${systemProperties} ${moduleProperties}</argLine>
	</configuration>
</plugin>
```

I seem to understand that the property is then set in the TestProjectDescriptor in case at least Java 9 is used:

https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend#L82

To specify `--add-modules=ALL-SYSTEM` but that's useless, since in the parent POM there's already a profile that sets another property (`moduleProperties`) with `--add-modules=ALL-SYSTEM` :

https://github.com/eclipse/xtext-core/blob/cc6ab5469fc0172cef4765688722fafc59604447/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend#L565

The real problem is that `tycho.testArgLine` is typically set by Jacoco for enabling code coverage. However, if the property is set to empty (as it is now in the parent's properties section), Jacoco will have no way of setting the property in time so that it can be used when running tests, resulting in no coverage. This problem is known, but usually it is quite hard to detect when tycho.testArgLine is set to empty by default (see, e.g., https://github.com/LorenzoBettini/tycho-multiproject-jacoco-report-example/pull/2).

I'd suggest not to specify `tycho.testArgLine` at all in the parent POM. Instead, another property could be used, e.g., `additionalTestArguments`, set to empty by default and used in the tycho-surefire configuration in pluginManagement. Since Jacoco is typically configured in a separate profile, in that profile one could set

```
<additionalTestArguments>${tycho.testArgLine}</additionalTestArguments>
```

and everything works automatically with the current configuration of tycho-surefire.

I think the authors of these generated POM are @kthoms (for the parent) and @cdietrich (for the  POM of the test project, which is already useless right now).

I can provide a PR, if you think that makes sense.

**Comment by cdietrich** [comment]
@kthoms any idea?

**Comment by kthoms** [comment]
`--add-modules=ALL-SYSTEM` seems indeed unnecessarely speficied twice. It should not be necessary to hard-coded enter that into the parent POM, but automatically at runtime by the `jdk9-or-newer` profile. So it is wrong to declare that to the parent POM.

The name of the property `tycho.testArgLine` does not really matter. Important is just that there _is_ some empty default property that is used in the management for `tycho-surefire-plugin`. I'm fine to change that to another name. Since they are _additional_ it may be better to put that after the other args.

```
<argLine>${platformSystemProperties} ${systemProperties} ${moduleProperties} ${additionalTestArguments}</argLine>
```

**Comment by LorenzoBettini** [comment]
OK, I'll work on that ASAP!

**Comment by LorenzoBettini** [comment]
I'd like to start working on that... but my current workspace setup was pretty old... I've fetched all the new git masters and run the update with Oomph but I still get tons of errors in main projects...

**Comment by cdietrich** [comment]
in which projects. oomph is not 4.12 ready so i dont know if it is fine. you should also do a gradle refresh gradle projects in eclipse e.g. on the composite in root projects working set.
and you may have to run a `mvn -f releng/org.eclipse.xtext.dev-bom/ install`  in lib and a `./gradlew clean build install -PuseJenkinsSnapshots=true -x test` in xtend

**Comment by LorenzoBettini** [comment]
what's the composite in root projects?

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2019-03-22 15-54-18](https://user-images.githubusercontent.com/238736/54831540-ce488d00-4cba-11e9-8417-b5b021baec5b.png)

**Comment by LorenzoBettini** [comment]
OK! thanks!
Errors in main projects seem to have disappeared.
Of course, lots of changed files according to git but I guess I mist ignore them

**Comment by cdietrich** [comment]
you should not see any. which xtext/xtend version is in your host.
can you give some examples?

**Comment by LorenzoBettini** [comment]
sorry, just .classpath in xtext.xbase.lib...

this part has been added

```
	<classpathentry including="**/*.java|**/*.xtend" kind="src" output="bin/main" path="xtend-gen">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
```

**Comment by cdietrich** [comment]
Need to check if I have this too.

**Comment by cdietrich** [comment]
@LorenzoBettini i have this already locally with no diff

**Comment by LorenzoBettini** [comment]
OK, but I don't think it's a big issue.
I created the PR, but Jenkins is overloaded I guess :)
We're using Eclipse CI, aren't we?

**Comment by cdietrich** [comment]
yes cbi is still worked on
