### ISSUE TITLE
[LanguageServer] Unexpected occurrence highlighting

### ISSUE THREAD

**Issue by mark-christiaens** [eclipse/xtext-core#1090]
The [DefaultDocumentHighlightService](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/occurrences/DefaultDocumentHighlightService.java#L184) behaves unexpectedly.

In particular, the `if (selectedElement == containedElement) { ... }` block doesn't make much sense to me. For example, I have a rule in our grammar:

```
Dec:
    'entity' name=ID 'is'
        DecPart
    ('begin'
        ConcPart)?
    'end' hasEntityKeyword?='entity'? endName=[EntityDeclaration]? ';';
```

The following source text matches this rule:
```
entity t is
end entity t;
```

When I put my cursor on the second `t` (in VS code attached to the LSP server), the aforementioned code does not highlight the two `t`s. When I put my cursor on the first `t`, both `t`s are highlighted.  Occurrence highlighting for the second `t` seems to be behaving badly due to the fact that it is a reference to the object it is contained in.

When I remove the if-block, then occurrence-highlighting behaves as expected.  What exactly is the purpose of this code?

**Comment by cdietrich** [comment]
@kittaakos can you answer this?

**Comment by cdietrich** [comment]
@mark-christiaens did you have a look at the tests in org.eclipse.xtext.ide.tests.server.DocumentHighlightTest

**Comment by mark-christiaens** [comment]
@cdietrich No, I didn't.  I guess you are asking, "if you remove the if-block, do the tests still work"?

**Comment by cdietrich** [comment]
correct. maybe the tests reveal the answer

**Comment by mark-christiaens** [comment]
When I remove the if-block then a few tests fail.  I guess that the implementations both with and without the if-block are incorrect.

**Comment by kittaakos** [comment]
> I guess that the implementations both with and without the if-block are incorrect.

@mark-christiaens, it easily possible. Do you happen to have time to look into this malfunction? Freely speaking, it's been a while I have contributed that code so I do not know the answer off the top of my head and I won't have time to investigate it until the beginning of April thoroughly.

**Comment by mark-christiaens** [comment]
I think this fixes the issue (it does so in the Sigasi code).  However, I couldn't whip up a specific test for this.  The reason being that `DocumentHighlightTest` is based on the Xtext test language that does not have grammar rules that trigger this issue.  If you know of an elegant way to test this, let me know.

**Comment by kittaakos** [comment]
> I think this fixes the issue

Awesome 👍

> couldn't whip up a specific test for this

It should be possible to define `YourNewGrammar` under `org.eclipse.xtext.testlanguages.yourNewGrammar` package, [add it to the workflow](https://github.com/eclipse/xtext-core/blob/dcc92fc7e0fbff8afb45d61802a2eb1ba382d190/org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/GenerateTestLanguages.mwe2#L43) and create a new test class for your tests:
```java
class DocumentHighlight2Test extends AbstractLanguageServerTest {

    new() {
        super('yourNewGrammarFileExtension');
    }

    @Test
    def void yourTest() {}
}
```

I have to admit, I have not tried it, but in theory, it should work like this.

**Comment by cdietrich** [comment]
👍 for adding a test

**Comment by cdietrich** [comment]
@tivervac @mark-christiaens is there anything left open?

**Comment by mark-christiaens** [comment]
@cdietrich No, I think this issue is concluded.  I'll close it.
