### ISSUE TITLE
Broken download of antlr-generator-3.2.0-patch.jar in AntlrToolFacade

### ISSUE THREAD

**Issue by mvmn** [eclipse/xtext-core#1098]
Hi

AntlrToolFacade has this pretty ugly code with hardcoded URLs for downloading antlr-generator-3.2.0-patch.jar from http://download.itemis.com/antlr-generator-3.2.0-patch.jar. But - the download doesn't seem to follow redirects. And just today http://download.itemis.com/antlr-generator-3.2.0-patch.jar returns HTTP/1.1 301 Moved Permanently with Location: https://download.itemis.com/antlr-generator-3.2.0-patch.jar (HTTPS instead of HTTP).

Which breaks download (to be specific - it downloads content that is an HTML page but saves it as a JAR file - which breaks subsequent loading of classes like de.itemis.xtext.antlr.toolrunner.AntlrToolRunner from that JAR).

**Comment by cdietrich** [comment]
@mvmn should work again
