### ISSUE TITLE
LSP4J (and Tests) on windows

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1108]
there are testfailures on windows. these need to be investigated if there is stuff missing in the tests (e.g. a `toUnixLineSeparator`)  or in the API (the document class e.g. uses `\n` to split whereas the spec specifies

> To ensure that both client and server split the string into the same line representation the protocol specifies the following end-of-line sequences: ‘\n’, ‘\r\n’ and ‘\r’.
> export const EOL: string[] = ['\n', '\r\n', '\r'];

**Comment by cdietrich** [comment]
@kittaakos @svenefftinge what do you think

**Comment by kittaakos** [comment]
Would the Windows build run on Jenkins too or do we want to use other free Windows CIs such as AppVeyor or Azure Pipeline?

**Comment by cdietrich** [comment]
@kthoms do you know if there is an option for that at eclipse infrastructure?

**Comment by kthoms** [comment]
In principle this seems to be possible. File a bug to Eclipse Community / Jenkins-CI to request a Windows node and instructions to use it.
https://www.eclipse.org/lists/cbi-dev/msg02038.html

**Comment by cdietrich** [comment]
cc @miklossy

**Comment by miklossy** [comment]
Currently the following 3 test cases are failing on Windows:

org.eclipse.xtext.ide.tests.server.SemanticHighlightingTest.testDidOpen_multiLine
org.eclipse.xtext.ide.tests.server.CompletionTest.testCompletion_AdditionalEdits_01
org.eclipse.xtext.ide.tests.server.DocumentTest.testGetLineContent

The tests are failing both in Eclipse as in the Gradle build:
![screenshot1](https://user-images.githubusercontent.com/20393472/70852285-f65aca80-1e9f-11ea-873b-abaea1eed90c.png)
![screenshot2](https://user-images.githubusercontent.com/20393472/70852287-f8bd2480-1e9f-11ea-83db-8d5722316556.png)
![screenshot3](https://user-images.githubusercontent.com/20393472/70852288-fbb81500-1e9f-11ea-9e4c-a464bef2a631.png)
![screenshot4](https://user-images.githubusercontent.com/20393472/70852289-fe1a6f00-1e9f-11ea-9c95-9d2fa6925fd4.png)
![screenshot5](https://user-images.githubusercontent.com/20393472/70852293-01155f80-1ea0-11ea-8090-cdc7495129a9.png)

**Comment by miklossy** [comment]
The following PR https://github.com/eclipse/xtext-core/pull/1333 adresses one problem described above.

**Comment by miklossy** [comment]
Fixed in 2.21.
