### ISSUE TITLE
[generator] Generate launch config

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#112]
With previous Xtext releases a launch config `Launch Runtime Eclipse.launch` was generated to the `.launch` folder of the runtime project. This feature got lost with the new generator infrastructure.

**Comment by svenefftinge** [comment]
Sorry, I forgot what value these launch configs bring over the default ones eclipse would generate.

**Comment by kthoms** [comment]
The "Launch Runtime Eclipse.launch" is more or less the same as if you would create one with Eclipse. Differences are
1) You don't have to create one, it's provided
2) A default launch config would be named "New_configuration" and the runtime workspace is "runtime-New_configuration". With the provided one the workspace is fixed.
3) The launch config is persisted by default and can be shared, which may not be known to all users how to do this with a launch config

The second launch config is to generate the Xtext infrastructure with. This could be achieved usually with right-click on the grammar.

The original question on slack was if it was a bug or feature that the launch configs are not generated anymore. It was said that I should consider it as a bug, since a feature got lost during the generator migration. Thus I restored the feature with the new generator.

**Comment by svenefftinge** [comment]
I don't recall if we explicitly avoided generation of them, but now that we are thinking about it I'd like to not have them, because the default behavior of Eclipse is good and we don't need to pollute the project tree. In the past the defaults weren't good (e.g. because of a too small permanent generation size) and we were Eclipse-only so it made more sense.
I'm in favor of closing this.

**Comment by kthoms** [comment]
Before actually closing this: I agree that the launch config for the runtime Eclipse is not really necessary, especially since when you create multiple DSL projects in the workspace, there would be multiple of them all with the same name and starting the same environment. One manually created would be enough. And we should assume that developers who want to develop Eclipse plugins should be familiar on how to create such a launch config.

What I would like to discuss the value of the second launch config, which starts the MWE workflow. Usually a user would generate the artifacts by using the context menu actions. Having a dedicated launch config could be still useful when a DSL is part of a workspace materialized with Oomph without checking in generated sources. In this case an Oomph setup could be instrumented to run the launch config, which otherwise would have to be created by the user manually. It would be convenience feature here. The type of launch config would be dependent on the selected build system and project configuration, which is respected by the PR.

I could live if this issue is voted to be a WONTFIX. However, this was a silently dropped feature with 2.9 (and actually using the old generator it would still exist), and it should be documented if a feature is discontinued.

**Comment by cdietrich** [comment]
@kthoms t though you fixed that. at least the wizard creates a launch.
