### ISSUE TITLE
[lsp] better handle canceled builds 

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-core#1121]
When I edit files in an auto-saving editor (like Theia), `didChange` notifications are usually followed by `didChangeWatchedFiles` notifications. The latter cancel the build, but only look at their own changes to decide whether a new build should be issued. The changes from the prior `didChange` queued on the `BuildManager` are ignored.

**Comment by cdietrich** [comment]
i thought we use didChangeWatchedFiles events only for non open documents.
this i would expected that the didChangeWatchdFiles build is queued

**Comment by JanKoehnlein** [comment]
Well, in my case it was apparently triggered for an opened document (which should be safe), thereby there were no dirty/deleted files detected from the change and the cancelled build was not retriggered.

**Comment by cdietrich** [comment]
=> why cancel the build at all?

**Comment by JanKoehnlein** [comment]
Cancellation happens automatically when another`runWrite()` is issued.
