### ISSUE TITLE
[LSP] We run validation twice on `didOpen`

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#1127]
https://github.com/eclipse/xtext-core/blob/639253d4646a30ffb05e6bd998e4aa09b03f8810/org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend#L120-L121

First, we validate with
https://github.com/eclipse/xtext-core/blob/639253d4646a30ffb05e6bd998e4aa09b03f8810/org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend#L139-L146

Then with the default `IShouldGenerate`
https://github.com/eclipse/xtext-core/blob/639253d4646a30ffb05e6bd998e4aa09b03f8810/org.eclipse.xtext/src/org/eclipse/xtext/generator/IShouldGenerate.xtend#L43

It does not make much sense.

**Comment by JanKoehnlein** [comment]
Is there a cache we can get the first validation result from?

**Comment by cdietrich** [comment]
why was it done this way in the first place?

**Comment by JanKoehnlein** [comment]
@cdietrich Looks like when introducing the IShouldGenerate interface in 2015 we overlooked that already. 
We should hand the issue list over to (an extended) IShouldGenerate.

**Comment by kittaakos** [comment]
> we overlooked that already

I do not follow much the changes outside of `xtext-core`, but it used the be the same for the Eclipse-based builder. I remember applying this trick in various Xtext-based projects. Note, it was long ago.

**Comment by cdietrich** [comment]
well the ishouldgenerate was introduce right to allow this

**Comment by kittaakos** [comment]
> cachedresourcevalidator is used to avoid

Nice, I was not aware of it.

----

A quick workaround for `xtext-core` can be:

```
class CachingResourceValidator extends ResourceValidatorImpl {

  public static String VALIDATION_RESULTS_KEY = 'validation-results';

  override validate(Resource resource, CheckMode mode,
    CancelIndicator cancelIndicator) throws OperationCanceledError {

    if (resource instanceof XtextResource) {
      return resource.cache.get(VALIDATION_RESULTS_KEY, resource, [
        super.validate(resource, mode, cancelIndicator);
      ]);
    } else {
      return super.validate(resource, mode, cancelIndicator);
    }
  }

}
```

```
class MyLanguageRuntimeModule extends AbstractMyLanguageRuntimeModule {

  def Class<? extends ResourceValidatorImpl> bindResourceValidatorImpl() {
    return CachingResourceValidator;
  }

  def Class<? extends IResourceValidator> bindIResourceValidator() {
    return CachingResourceValidator;
  }

}
```

which I guess more or less the same as the above-mentioned cachedresourcevalidator.

PS: let me know if my proposed workaround is incomplete :)

**Comment by cdietrich** [comment]
@szarnekow @JanKoehnlein what do you think.
should we go this route. or having a different default IShouldGenerate?

**Comment by JanKoehnlein** [comment]
Control flow is more explicit if we change IShouldGenerate, but for the Sprotty scenarios, I need the validation issues a third time, so transparently caching would come handy. Both ideas are fine by me.

**Comment by cdietrich** [comment]
as nobody is working on this, I will remove this from any milestone

**Comment by szarnekow** [comment]
Closing as there was no more input. Please reopen in https://github.com/eclipse/xtext if you plan to work on this.
