### ISSUE TITLE
[LSP] Concurrent request handling on LS

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/xtext-core#1135]
Is it possible for the language server to execute a request when one is already being executed?
My use case for this is a resource consuming process that is executed on the LS via a request, which I want to stop via another request/notification to the LS.

In my current setup, the second request is only handled after the first request has finished. I am sure whether I am doing this wrong or whether this is not possible.

**Comment by svenefftinge** [comment]
By default read requests can run in parallel and write requests run exclusively. So not sure why it doesn't do that in your case.

**Comment by soerendomroes** [comment]
Okay, thank you, I fixed my issue by using notifications instead of requests.
