### ISSUE TITLE
Maven Build: Jvm type reference cannot be resolved if target type is annotated with Lombok annotation

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-core#1143]
I have an Xbase based language which references Java types. Unfortujnately these references cannot be resolved by the xtext-maven-plugin whenever the target type is annotated with a Lombok annotation.

Within Eclipse everything works fine, but the xtext-maven-plugin fails.

```
[INFO] Starting validation for input: 'Super.hero'
[ERROR] ERROR:somepackage.SomeType cannot be resolved. 
```

**Comment by cdietrich** [comment]
can you please provide a minimal example

**Comment by OLibutzki** [comment]
You can test it with the herolanguage easily. I created a fork: https://github.com/OLibutzki/maven-xtext-example

Just try to build the example-project with Maven.

**Comment by OLibutzki** [comment]
> does it work in xtend and xtend-maven-plugin?
Yes, it does

**Comment by cdietrich** [comment]
```
[WARNING] ----------
[WARNING] 1. ERROR in /home/dietrich/Downloads/tmp/maven-xtext-example/example-project/target/xtext-temp/stubs/my/company/Superman.java
[WARNING]  (at line 0)
	package my.company;
	^
[WARNING] Internal compiler error: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: Provider lombok.launch.AnnotationProcessorHider$ClaimingProcessor not found at java.util.ServiceLoader.fail(ServiceLoader.java:239)
[WARNING] ----------
[INFO] [2 units compiled]
[WARNING] 1 problem (1 error)
```

**Comment by cdietrich** [comment]
=> disabling annotation processing in xtext maven plugin seems to help

```
			<plugin>
				<groupId>org.eclipse.xtext</groupId>
				<artifactId>xtext-maven-plugin</artifactId>
				<version>${xtext-version}</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<compilerSkipAnnotationProcessing>true</compilerSkipAnnotationProcessing>
```

**Comment by OLibutzki** [comment]
Thanks! That helps!

The problem that the stuff which is generated by Lombok cannot be referenced (neither in Eclipse nor Maven) cannot be solved, right?

**Comment by cdietrich** [comment]
i assume so. am not sure what happens if you enable annotation processing and add the missing class to the dependencies

**Comment by OLibutzki** [comment]
Ok, thanks a lot @cdietrich. I close this issue.
