### ISSUE TITLE
Generating a project with two languages using maven not working

### ISSUE THREAD

**Issue by woernm** [eclipse/xtext-core#1151]
Hi,

I am having issues to build my project containing two languages with maven.

As a simple reproducer I created the 'MyDsl' example project leaving all parameters at their default except using Maven as preferred build system. I then created a second language MyDsl2.xtext in the same package as MyDsl.xtext. MyDsl2 depends on MyDsl:

```
grammar org.xtext.example.mydsl.MyDsl2 with org.xtext.example.mydsl.MyDsl

generate myDsl2 "http ://www.xtext.org/example/mydsl/MyDsl2"

Model2:
	model2 = Model;

```

I adapted the GenerateMyDsl.mwe2 to build MyDsl2 as well.

Running ```mvn clean install``` gives the following message:
```
ERROR XtextGeneratorLanguage - [XtextLinkingDiagnostic: null:1 Couldn't resolve reference to Grammar 'org.xtext.example.mydsl.MyDsl'., XtextLinkingDiagnostic: null:6 Model cannot be resolved to a rule]
```

There is a sample project at
https://github.com/woernm/MyDslWithTwoLanguages

Just download it and try to build it using Maven.

There is already a thread on this on the Xtext forum where the issue could not be solved:
https://www.eclipse.org/forums/index.php/t/1098672/

Regards
Werner

**Comment by szarnekow** [comment]
I can reproduce the problem with your example when I call `mvn clean package` the second time.

**Comment by szarnekow** [comment]
```
language = StandardLanguage {
	name = "org.xtext.example.mydsl.MyDsl2"
	fileExtensions = "mydsl2"
	referencedResource = "platform:/resource/org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDsl.xtext"

	serializer = {
		generateStub = false
	}
	validator = {
		// composedCheck = "org.eclipse.xtext.validation.NamesAreUniqueValidator"
		// Generates checks for @Deprecated grammar annotations, an IssueProvider and a corresponding PropertyPage
		generateDeprecationValidation = true
	}
	junitSupport = {
		junitVersion = "5"
	}
}
```

You'll need to load the first language manually into the resource set of the second language. The maven lifecycle does not copy the Xtext files to the target/classes folder (apparently) before the workflow is executed. So there is no generically applicable algorithm to guess the location of an Xtext file given only the FQN of the language.

Long story short - adding a referencedResource that points to the MyDsl.xtext will help.

**Comment by faustocarva** [comment]
I have the same problem. After using "referencedResource" the error changed to the bellow transcript:

50  [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow GenerateMetaCrySL: The EPackage "http://www.eclipse.org/xtext/xbase/Xtype" in grammar org.eclipse.xtext.xbase.Xtype could not be found. You might want to register that EPackage in your workflow file.
java.lang.RuntimeException: Problems running workflow GenerateMetaCrySL: The EPackage "http://www.eclipse.org/xtext/xbase/Xtype" in grammar org.eclipse.xtext.xbase.Xtype could not be found. You might want to register that EPackage in your workflow file.

The referenced grammar is doing a "with" to Xtype. 

Any clue?

**Comment by cdietrich** [comment]
Can you provide more details
