### ISSUE TITLE
Generated java package name 'org.xtext.example.mydsl.myDsl' does not match java package naming conventions

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#1161]
When creating a new Xtext MyDsl project via the Xtext new project wizard and executing the `GenerateMyDsl.mwe2` workflow, the EMF classes are generated into the  `org.xtext.example.mydsl.myDsl` java package. 

The camel case notation does not match to the java package naming conventions, so that SonarQube recognizes that as an issue.
![screenshot](https://user-images.githubusercontent.com/20393472/58935892-c1dab900-876e-11e9-8818-4b0d09acfc4a.png)

**Hint:** When changing the `myDsl` to `mydsl` in the `MyDsl.xtext` file, the generated java packages are named as desired.

I suggest two solutions for this problem:
- the ID after the generate keyword should always be in lower case, then the java packages are automatically generated with the right naming
- use the lowercase notation of the ID after the generate keyword when determining the names of the generated java packages

**Comment by cdietrich** [comment]
for me this looks like a feature, not a bug

**Comment by szarnekow** [comment]
> feature

True. We should not automatically mangle the names.
An optional validation could be useful, though.

**Comment by miklossy** [comment]
@loradd Would you like to take care of this issue? An optional validation issue and a corresponding quickfix would be awesome...

**Comment by cdietrich** [comment]
i think the validation should be added to the wizard too.
am not sure if a quickfix is sufficient since it may require a merge of plugin.xml etc after regeneration

**Comment by loradd** [comment]
@miklossy yes, I would like to take of this issue! 

> i think the validation should be added to the wizard too.
> am not sure if a quickfix is sufficient since it may require a merge of plugin.xml etc after regeneration

Any suggestion about the merging process?

**Comment by cdietrich** [comment]
the merging is done manually. thats the problem.
=> user need to know the the followings things need to be done after executing a quickfix
(1) run workflow
(2) merge plugin.xmls
=> quickfix in editor does not make sense to me.

**Comment by miklossy** [comment]
As @szarnekov suggested, a configurable issue (set to ignore as default) would be fine. If I recall it correctly, both plugin.xml files (in the runtime module and in the ui module) have to be merged. @cdietrich Please confirm.

**Comment by cdietrich** [comment]
Dont know needs to be checked 
Runtime for sure

**Comment by miklossy** [comment]
I suggest to create a configurable issue `Java package naming conventions` (and set is to Ignore as default) under the `Grammar` section on the `Xtext`->`Errors/Warning` preference page:
![screenshot](https://user-images.githubusercontent.com/20393472/59144550-e9818980-89d9-11e9-8a35-6431d5422c21.png)

**Comment by loradd** [comment]
I added a validation check for this issue. Considering the validator for bidirectional references, it seemed to me that no unit test is provided. Any suggestion on how to define a unit test for ignored checks? Also, integrating the configurable issue in the preferences concerns the xtext-eclipse project, if I am not wrong. Should I open an issue there referencing to this one?

**Comment by miklossy** [comment]
@loradd  You can add the necessary changes to the `xtext-eclipse` repo and reference the issue in the `xtext-core` repository, no need to create a new issue. In order to be able to test the ignore checks, you can modify the severity of the issue in the test case to warning or error and then you should be able to test it. For further information see the [StricterIssueCodesInTests](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/RuntimeTestSetup.java#L129), [ValidationIssue397Test](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationIssue397Test.xtend#L31), [ValidationIssue397QuickFixTest](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue397QuickFixTest.xtend#L31) test cases.

**Comment by miklossy** [comment]
Thanks for the fix @loradd I merged you PRs into the master branch.

Resolving this issue as fixed in 2.19.
