### ISSUE TITLE
Missing starting character from text from multi-line comment

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/xtext-core#1171]
In our language (n4js) we can write:

```ts
/**test*/
class MyClass {}
```

When hovering over 'MyClass', we get:
<img width="208" alt="Screenshot 2019-06-14 at 16 41 09" src="https://user-images.githubusercontent.com/20560257/59518592-35469e00-8ec6-11e9-82dd-13edeaa3dfc6.png">

The starting character 't' from the multi-line comment is missing. This is happening in `AbstractMultiLineCommentProvider#getTextFromMultilineComment(String)` ([link](https://github.com/eclipse/xtext-core/blob/23ce64da6c476020582013e6d3ff7e7fb5d92c68/org.eclipse.xtext/src/org/eclipse/xtext/documentation/impl/AbstractMultiLineCommentProvider.java#L101)) when passing as an argument the value `/**test*/`. In the body (line 101) the statement `returnValue = startTagRegex.matcher(returnValue).replaceAll("");` will remove the head of the original value so that the value of `returnValue` equals to `est*/`.

**Comment by miklossy** [comment]
Thanks for the bug report! Is the problem reproducible on the Domain-Model example shipped with Xtext? If yes, could you provide a PR with a test case similar to https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HoverTest.xtend

**Comment by cdietrich** [comment]
i cannot reproduce this in Xtend

```
/**test*/
class Viech {
	
}
```

nor in mydsl

nor in dmodel

```
/**test*/
entity Person {
	
}
```

=> how does startTagRegex look like for you @mmews-n4

**Comment by cdietrich** [comment]
@mmews-n4 i found this one:
https://github.com/eclipse/n4js/blob/0fa04126396368c16d21298a992c69f50a14dd8b/plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSRuntimeModule.java#L300
=> seems intended

**Comment by mmews-n4** [comment]
@cdietrich Thanks for your help! I wasn't aware of this re-bind.
