### ISSUE TITLE
[Junit4Fragment2] Improve generated test code

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#118]
The currently generated test code looks as follows:

```
@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslParsingTest{

    @Inject
    ParseHelper<Model> parseHelper

    @Test 
    def void loadModel() {
        val result = parseHelper.parse('''
            Hello Xtext!
        ''')
        Assert.assertNotNull(result)
    }

}
```

This test would also pass if the parsed model is invalid, e.g. when testing `Hello Xtext` instead of `Hello Xtext!`. Using the ValidationTestHelper would improve that.

Using the with-Operator could make the test more readable. And when Assert is imported as static extension, the code would be even more fluent.

Next, the method name "loadModel" is not appropriate. A model is not loaded from somewhere, it is just parsed from inline text.

Therefore I propose that the generated test code should look like this:

```
@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslParsingTest{

    @Inject extension ParseHelper<Model>
    @Inject extension ValidationTestHelper

    @Test 
    def void testModel() {
        '''
            Hello Xtext!
        '''.parse => [
            assertNotNull
            assertNoErrors
        ]
    }
}
```

**Comment by LorenzoBettini** [comment]
I think this is somehow related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=492034

I think the parsing test should only test parsing and the test should pass also with "Hello world" because the parse can actually create a model out of that, shouldn't it?

**Comment by kthoms** [comment]
I already encountered situations where users where confused by the fact that the test passes also with an invalid model. They were even not aware of the fact that there is the ValidationTestHelper, and usually one would only write tests for models which either are valid or invalid. For the case that someone would like to test an invalid model, this should be also tested with the test helper.

What do you think?

**Comment by kthoms** [comment]
Maybe the test class should be even extended by a negative test?

**Comment by kthoms** [comment]
```
	@Test
	def void testInvalidModel () {
		'''
			Hello Xtext
		'''.parse => [
			assertNotNull
			assertError(it.eClass, Diagnostic.SYNTAX_DIAGNOSTIC, "expecting '!'")
		]
	}
```

**Comment by LorenzoBettini** [comment]
As I said in my original bugzilla bug, I'd like to have more test use cases generated, but I agree with Sven that the generated test class is really a starting point (and only for parsing not for validation).

You could comment on the bug or discuss in Slack?

**Comment by svenefftinge** [comment]
Better documentation about the testing library would help more than generating everything into fresh projects. Let's keep the stuff that is initially generated minimal.

**Comment by cdietrich** [comment]
I would extend the existing test with the usage of vth assertnoerrors but leave it with that

**Comment by kthoms** [comment]
I agree with Christian and will update the PR accordingly.

**Comment by cdietrich** [comment]
fixed in 2.11

**Comment by vwegert** [comment]
Since I just ran into this very issue in 2.10 - I would have loved to have at least a hint that something like the ValidationTestHelper existed, especially since it is not mentioned in the documentation in any place. That would have saved me quite some time.

**Comment by cdietrich** [comment]
Created https://github.com/eclipse/xtext-core/issues/253
