### ISSUE TITLE
Backporting windows test fixes

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-core#1183]
During the work to get the build running on tycho only a couple of tests where fixed that fail on windows only. We should backport these fixes to master.

**Comment by cdietrich** [comment]
@ArneDeutsch can you check how much overlay this has with https://github.com/eclipse/xtext-core/issues/1108

am not sure if we should fix the tests only or the impl too

**Comment by ArneDeutsch** [comment]
I will have an eye on that during the backport. But as I remember, quite often it is more a test issue (e.g. creating the output of an operation with system line seperator but then using `/n` in the test).

**Comment by ArneDeutsch** [comment]
Fixed in scope of https://github.com/eclipse/xtext/issues/1455 .

**Comment by cdietrich** [comment]
nice @ArneDeutsch
