### ISSUE TITLE
[doc] error: unable to create file – Filename too long when cloning on Windows

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#1186]
Originally from https://gitter.im/eclipse/xtext?at=5d12129718e3256238394794

Git clone can fail on Windows due to long file paths.

```
Resolving deltas: 100% (68762/68762), done.
error: unable to create file org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target: Filename too long
error: unable to create file org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch: Filename too long
Checking out files: 100% (7644/7644), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

This happened when I did a `git clone` under `C:\Users\kittaakos\dev`. Switching to `C:\` fixed the issue.

I am not sure if we can do anything with this, one line of documentation could be useful.

**Comment by cdietrich** [comment]
cc @ArneDeutsch this is the same problem you already saw.

possible workaround

- use shorter project names, to at leas handle such common checkouts to somehere on users
- while we are at we should drop the java 9 and 10 tests
- add java 11 tests
- add junit 5 tests

**Comment by cdietrich** [comment]
java 11 already done
