### ISSUE TITLE
Find replacement for XtextAntlrGeneratorComparisonFragment

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1189]
Find replacement for XtextAntlrGeneratorComparisonFragment which is a FragmentAdapter
or deprecate it and remove usages

**Comment by szarnekow** [comment]
I don't think we need this anymore since it was only used as a safety net when migrating to the new generator.

**Comment by cdietrich** [comment]
ok, i will deprecate it and remove it from generatexbase

**Comment by cdietrich** [comment]
fixed in 2.19
