### ISSUE TITLE
Adaptability of ParserBasedContentAssistContextFactory.StatefulFactory

### ISSUE THREAD

**Issue by kduske-n4** [eclipse/xtext-core#120]
I have a use case where I need to adapt `org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory.StatefulFactory`, specifically, I need to adapt the behavior of `org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory.FollowElementCalculator`, which I can do by subclassing and overriding some methods.

In order to have my custom subclass used by `ParserBasedContentAssistContextFactory.StatefulFactory#computeFollowElements(Collection<FollowElement>, Collection<AbstractElement>)`, I have to override that method and copy all of the code. It would be much better if there was a factory method in `ParserBasedContentAssistContextFactory.StatefulFactory` to create the `FollowElementCalculator` to use.

**Comment by spoenemann** [comment]
Needs to be done in the xtext-eclipse repository.

**Comment by kduske-n4** [comment]
Should I move it over there?

**Comment by spoenemann** [comment]
That would be good, thanks. However, note that `ParserBasedContentAssistContextFactory` is regarded as deprecated (annotation is missing), so I don't know whether we'll do any changes there.

**Comment by kduske-n4** [comment]
That's discouraging ;-). What should we use instead?

**Comment by spoenemann** [comment]
Newer languages use `org.eclipse.xtext.ui.editor.contentassist.antlr.DelegatingContentAssistContextFactory`.

**Comment by meysholdt** [comment]
hi Kristian,
this is related to migrating a language's MWE2 workflow to the new generator. 

The old generator binds 
`org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory`

The new generator instead binds
`org.eclipse.xtext.ui.editor.contentassist.antlr.DelegatingContentAssistContextFactory` which delegates to 
`org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory`

This change was necessary to decouple the content assist parser from Eclipse UI dependencies.

So this issue should be about making instantiation of 
`org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementCalculator`
customizable in 
`org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElementComputer`

**Comment by kduske-n4** [comment]
Alright, but since we are still using the old generator, we're going to leave things as they are for now. Thanks for your input! I suppose this issue can be closed.

**Comment by spoenemann** [comment]
Ok, feel free to reopen if we should change anything in the new `ContentAssistContextFactory`.
