### ISSUE TITLE
Replacement for ExternalAntlrLexerFragment

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1208]
is there a replacement for Replacement for ExternalAntlrLexerFragment
it is used e.g. in MWE
@szarnekow do you have any insights?

**Comment by szarnekow** [comment]
I'm not aware of a replacement. Could be, that we have to migrate that from scratch.

**Comment by cdietrich** [comment]
the fragment or the workflow in mwe?

**Comment by szarnekow** [comment]
The fragment.

**Comment by cdietrich** [comment]
fixed in 2.20
