### ISSUE TITLE
[grammar] prefix overriding parser rules with 'override' keyword

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#121]
Java introduced the @Override annotation in Java so that developers get feedback from the compiler when a super class changes a method signature but the sub-class still expects to override it.

We face the same scenario in grammars: When a parser rule is being renamed in a super grammar and there is a parser rule in a sub-grammar overriding that parser rule, currently developers of the sub-grammar get no feedback indicating that they need to rename their parser rule as well. Instead, the parser rule silently turns from being an 'override' into a new declaration.

We could prefix parser rules with the 'override' keyword when they are expected to override a parser rule from a super-grammar. This would give developers an error message if the parser rule from the super grammar is not available anymore. This would also improve readability of a grammar because it would make it explicit where override happens. 

For backward compatibility, overriding rules without using the 'override' keyword would still need to work. However, this should cause a warning. A quick-fix could resolve the warning by adding the 'override' keyword.

Introducing a new keyword to the language may cause conflicts with existing identifiers. In the grammar language, we have identifiers for epackage-aliases, EClasses, EStructuralFeatures, Rules. Only aliases and EStructuralFeatures are candidates for conflicts, as Rule-names and EClass-names start with an uppercase letter by convention. The 'override' keyword could be allowed as an identifier for aliases and EStructuralFeatures.

**Comment by meysholdt** [comment]
@JensN4 describes this al follows in [bug503311](https://bugs.eclipse.org/bugs/show_bug.cgi?id=503311):

	When a grammar extends another one, e.g.
	
	----
	grammar SubGrammar with SuperGrammar
	----
	
	rules can be overridden. This is simply done by using the same rule name.
	
	It would great if an overriding rule could be marked as "override", similar to the Java/Xtend @Override/override feature. Xtext already checks the correct "return type" (the model element created by the rule).
	
	Example (using Xpect notation):
	
	Given 
	----
	grammar SuperGrammar 
	Program: (x+=Item | x+=Element)*;
	Item: "item" prop=IDENTIFIER;
	Element: "element" prop=IDENTIFIER;
	----
	
	and
	----
	grammar SubGrammar with SuperGrammar
	override Program: (x+=Element | x+=More)*;
	
	// XPECT warning --> "rule Element overrides SuperGrammar.rule, should be marked with 'override'"
	Element: "elem" prop=IDENTIFIER;
	
	// XPECT error --> "rule More does not override any super rule"
	override More: "more" prop=IDENTIFIER;
	----
	
	Additionally it would be nice to add the triangle marker at the right hand side to enable easy navigation to the overridden rule.
	
	In order to ensure backwards compatibility, missing override annotations could be indicated as warning, or warning/error is only created based on project settings.

**Comment by meysholdt** [comment]
Other thoughts that were expressed to me
 * the `override` keyword could allow overriding rule declarations to cross-reference the overridden rule
 * maybe use `@Override` instead of `override` to absolutely avoid syntactic collisions with identifiers.

**Comment by svenefftinge** [comment]
Long time ago we had a discussion about annotations in the grammar language. That is instead of hardcoding these things into the grammar, we could allow an identifier (prefixed with an '@').

This wouldn't conflict with identifiers in existing grammars (especially 'override' is possibly used in 80% of all grammars :)) and would open up the syntactical space for other meta data that than can be used in the validator and generator fragments.

**Comment by svenefftinge** [comment]
> the override keyword could allow overriding rule declarations to cross-reference the overridden rule

Why would that be helpful?

**Comment by meysholdt** [comment]
> Why would that be helpful?

out-of-the box support for "open declaration", content assist, and validation :)
But it does stand in conflict with introducing generic annotations.

**Comment by svenefftinge** [comment]
I would prefer to do it like it is done in JDT. I.e. having an icon in the gutter to navigate.
Also I don't see how it helps with content assist. I'd like to have a similar override proposal than in JDT.

**Comment by knutwannheden** [comment]
As in the discussion we had a "long time ago" I still like the idea of "annotations".

We have a customer who needs simple semantic predicates for their grammars. The way it has been implemented is by adding a comment like `/* @SemanticPredicate(MyPredicates.isObjectType) */` before the rule declaration. A custom generator detects this and generates a corresponding semantic predicate into the ANTLR grammar for all calls to this rule.

Not having to do this in comments would of course be nice, even if the custom generator has to remain.

**Comment by JensN4** [comment]
@svenefftinge 
When we discussed the "override" marker with Moritz, I think we were referring to the icon in the gutter, similar to the JDT. At least that's what I meant.

Whether it is `@Override` or just `override` -- I as a user of Xtext do not really care.

**Comment by szarnekow** [comment]
Was it a deliberate decision to support exactly one annotation per rule or is that an oversight?

**Comment by spoenemann** [comment]
The motivation behind it was to not introduce unnecessary complexity. The Xtext AST ist not regarded as public API, so it wont't be a problem to change this to multiple annotations when we find a need for that.

**Comment by szarnekow** [comment]
I'd like to allow multiple annotations per rule. Those could be evaluated by custom generator fragments. Should I reopen this ticket or create a new one?

**Comment by knutwannheden** [comment]
IMHO it would also make sense to allow for simple annotation parameters, as e.g. with the SuppressWarnings comments in `Xtext.xtext`.

**Comment by spoenemann** [comment]
@szarnekow create a new issue. This issue was about overriding rules.
