### ISSUE TITLE
[Wizard] Switch default back to Java

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1223]
I think we should switch the default back to Java and use Xtend only for Tests and the Generator.

What do you think?

**Comment by kthoms** [comment]
I support the idea. For Xtext newbies it is too complex to add the burden of learning Xtend upfront when they "just" want to create a simple Xtext project.

**Comment by LorenzoBettini** [comment]
In my humble opinion that would be a bad step backwards, since Xtend is much easier to use for every task in an Xtext DSL implementation... are you at least going to provide any flag in the wizard for easily switching? Last (but in my case, definitely not least) it will "break" the Xtext book...

**Comment by cdietrich** [comment]
we dont have the capacity to maintain and develop Xtend in a way that would / should / could encourage users to use it as GPL. 
additionally people have to learn xtend to get very basic tasks done.

i could live with a flag in the Wizard though.

**Comment by LorenzoBettini** [comment]
> we dont have the capacity to maintain and develop Xtend in a way that would / should / could encourage users to use it as GPL.

that's even more depressing... :'(

**Comment by cdietrich** [comment]
we had a discussion on this topic at eclipsecon and came to the conclusion we should go this route. 
the question is: do we need a flag in the wizard
@ArneDeutsch @miklossy do you have any thoughts how much effort such a flag would be?

**Comment by miklossy** [comment]
Adsing a flag (checkbox/combobox/radio buttons) to the wizard is no problem.

**Comment by LorenzoBettini** [comment]
+1 for the flag

**Comment by cdietrich** [comment]
Who could work on that?

**Comment by kthoms** [comment]
🙋‍♂

**Comment by miklossy** [comment]
The question is how to represent the flag on the Gui? Combobox / radio buttons, something else?

**Comment by szarnekow** [comment]
Generally I prefer fewer options over more options, but if we agree on having a flag in the wizard, I't like to be a checkbox `[ ] Create service stubs as Xtend classes` (wording to be discussed)

**Comment by cdietrich** [comment]
I wonder if a comment on the flag in the generated workflow could help too

**Comment by kthoms** [comment]
IMO if it is visible in the workflow that's actually enough. Adding a UI visible thingy for something we discourage to use is not helping users.

**Comment by LorenzoBettini** [comment]
Just for curiosity: we actually "discourage" the use of Xtend now?

**Comment by kthoms** [comment]
Yes, for usages where it does not add much benefits. We leave it for generators and formatting.

**Comment by szarnekow** [comment]
A little bit of background on Karstens comment:
Since we see new Java versions every 6 months, it is hard to keep up with its fast evolution. There is still a clear sweet spot in using Xtend in certain areas though. For code generation and for APIs that are designed particularly for extensions (namely the formatting API), it is beneficial to use Xtend. For plain vanilla coding, Java 8 and especially Java 11 are the better choice. Compile times, tooling etc are superior to Xtend.

This is what was discussed during EclipseCon in Ludwigsburg and we came to the conclusion, that we don't want to encourage using Xtend for everyday coding problems. It's a pity but sometimes writing Java is more fun than writing Xtend.

**Comment by cdietrich** [comment]
TODO: wizard

**Comment by kthoms** [comment]
@LorenzoBettini After thinking about it I don't think we should blow up the wizard for this option. The wizard is already complex enough and should encourage only to use the most common configuration for new projects. We don't want to encourage using Xtend for everything, but only for generators and tests. This would be further enabled by default, while other customizations will use Java by default.

If you agree I would like to close the issue.

**Comment by LorenzoBettini** [comment]
Please go on closing this, I did not agree on the whole issue anyway ;) but since this was the final decision...
so from what i understand, besides generator and tests, each single component that one wants to be generated in Xtend must be explicitly enabled in the mwe2 file right?

**Comment by cdietrich** [comment]
@LorenzoBettini this is not a decision we want to do but we have to do due lacking resources and contributions

**Comment by cdietrich** [comment]
@LorenzoBettini  no.

you just need to remove this line or toggle it to true
https://github.com/eclipse/xtext-core/blob/cdfdc90a717156d665bd491c372784451499f0ec/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/org.xtext.example.lsGradleApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2#L23

**Comment by cdietrich** [comment]
=> the only thing that changes is how the workflow is generated by the wizard.
existing workflows wont change behaviour
