### ISSUE TITLE
Serializer messes up whitespace if EObjects override equals/hashCode

### ISSUE THREAD

**Issue by xpomul** [eclipse/xtext-core#1230]
**Problem**

Given a semantic model which contains `EClass`es that override equals/hashCode in a way that two different instances `a` and `b` of the `EClass` can be equal (`a.equals(b) == true`) – as in

```
package net.winklerweb.xtext.test.model

import java.util.Objects

class Books {
	contains Book[] books
}

class Book {
	String author
	String title
	
	op boolean equals(Object o) {
		if (o instanceof Book)
			return this.author == o.author && this.title == o.title
		else
			return false
	}
	
	op int hashCode() {
		return Objects.hash(author, title)
	}
}
```

, given a grammar that defines a DSL such as 

```
// automatically generated by Xtext
grammar net.winklerweb.xtext.test.dsl.BookDsl with org.eclipse.xtext.common.Terminals

import "net.winklerweb.xtext.test.model" 
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Books returns Books hidden(WS, SL_COMMENT):
	(books += Book)*
;

Book returns Book:
	{Book}
	'Book'
	'{'
		('title' title=STRING)
		('author' author=STRING)
	'}';

EString returns ecore::EString:
	STRING | ID;
```

and given a DSL string that contains duplicate objects with different spacing – such as 

```
Book  {  title  "Magyk"          author       "Angie Sage"    }
Book { title 
"Magyk" author  "Angie Sage" }
Book  {  title  "The Hobbit"     author "J. R. R. Tolkien" }
Book { title "The Hobbit"  author "J. R. R. Tolkien"    }
```

If this string is parsed and then serialized again using 

```
val result = parseHelper.parse(string)
val text = serializer.serialize(result)
```

the result messes up spacing (note, e.g. the extra line break):

```
Book { title 
"Magyk"          author       "Angie Sage"    }
Book { title 
"Magyk" author  "Angie Sage" }
Book { title "The Hobbit"     author "J. R. R. Tolkien" }
Book { title "The Hobbit"  author "J. R. R. Tolkien"    }
```

The code above is from an attempt to reproduce with a minimal example. I have attached the minimal example in the form of an archive containing Eclipse projects. Import and run `net.winklerweb.xtext.test.dsl.tests.BookDslParsingTest` to try for yourself.

In our production environment, the grammar is more complex and we have cases in which the mandantory space between a keyword token and a QualifiedName token is eaten up by the serializer, resulting in an invalid DSL file serialized.

**Environment**

First detected in production with Xtext 2.14, but is most likely even older.
The minimal example was reproduced with Eclipse 2019-06 and Xtext 2.18.

**Root Cause**

I was able to analyze and track down the problem as follows:

The `org.eclipse.xtext.serializer.sequencer.SemanticNodeProvider.NodesForEObjectProvider` builds up a `HashMap` called `childrenBySemanticChild` which uses the semantic element (`EObject`) as key. If an `EReference` contains multiple objects that are equal according to their `equals` implementation, then putting them into the `Map` leads to the previous object being overwritten by the newer, equal one.

The problem is that these multiple objects relate to different nodes in the node model, so they should be mapped to different `SemanticNode` instances. This relation gets lost; all duplicate objects are mapped to the same `SemanticNode` instance and thus, to the same `INode` from the node model.

That, in turn, leads to an uncovered case in `org.eclipse.xtext.serializer.sequencer.HiddenTokenSequencer.getHiddenNodesBetween(INode, INode)` because the `from` and `to` nodes are actually in different subtrees of the node model and thus, the hidden tokens are not correctly emitted during serialization.

**Proposed solution**

Instead of a `HashMap` use a `TreeMap` with a custom comparator which only reports objects as equal if the instance is equal (using `==`).

Alternatively, wrap the key of the map (the `EObject`) in a wrapper that provides a suitable `equals` implementation that again compares the instances of the `EObject`s instead of using their `equals` method. 

I'd be happy to contribute, but I'd like confirmation first that this is accepted as a bug.

**Comment by xpomul** [comment]
[SerializerIssue.zip](https://github.com/eclipse/xtext-core/files/3551633/SerializerIssue.zip) contains the minimal example I mentioned above.

**Comment by cdietrich** [comment]
i fear there is nobody actively working on that part of xtext right now

**Comment by cdietrich** [comment]
@meysholdt what do you think? bug or not?

**Comment by cdietrich** [comment]
@xpomul does a Identity Hashmap the job as well ?

**Comment by meysholdt** [comment]
Thank you for this extensive report and analysis, @xpomul!

The EMF Framework however assumes that `equals()` of [EMF Objects is not overwritten](https://github.com/eclipse/emf/blob/8a3d58071a0cd5ce0fd5c765f4563620f14cbe50/plugins/org.eclipse.emf.ecore/src/org/eclipse/emf/ecore/EObject.java#L65-L66
):
> The framework also assumes that implementations will not specialize {@link #equals(Object)} (nor {@link #hashCode()}) so that "<code>==</code>" can be always used for equality testing;

And the Xtext Serializer is based on that assumption. I would not want to broaden assumtions beyond EMF.

**Comment by xpomul** [comment]
Ah, bummer :-(

I think in our project nobody was aware about this EMF assumption (and it is funny that nobody noticed this on our side in the past nine years ;-) - because the overridden equals was in there for ages...).

Thanks for your quick replies, though, @meysholdt and @cdietrich. I agree that we should not broaden the assumptions.

Well, at least I have learned a lot about the node model and serializer ;-)

**Comment by xpomul** [comment]
For anyone stumbling over this in the future, the following workaround *seems* to work for now:

```java
@SuppressWarnings("restriction")
public class CustomSemanticNodeProvider extends SemanticNodeProvider
{
  public class CustomNodesForEObjectProvider extends SemanticNodeProvider.NodesForEObjectProvider
  {
    public CustomNodesForEObjectProvider(final EObject semanticObject, final ICompositeNode node)
    {
      super(semanticObject, node);
      this.childrenBySemanticChild = new IdentityHashMap<>();
    }
  }

  @Override
  protected NodesForEObjectProvider createNodesForEObjectProvider(final EObject semanticObject, final ICompositeNode node)
  {
    return new CustomNodesForEObjectProvider(semanticObject, node);
  }
}
```

This class can be bound in the runtime module of the DSL like this:

```java
  @Override
  public void configure(final Binder binder)
  {
    super.configure(binder);
    binder.bind(ISemanticNodeProvider.class).to(DcmDslSemanticNodeProvider.class);
  }
```

**DISCLAIMER**

This seems to work fine for our case, but as @meysholdt stated above, it is out of spec. 
If you have any way to not override `equals` in the model, then go for that.
In our case, we will try to eliminate the custom `equals` longterm, but as this could have a greater impact on our codebase, we chose to go for this (in our current state less risky) way for the time being.
