### ISSUE TITLE
[LS] Support workspace/didChangeWorkspaceFolders

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#1238]
Spec: [`workspace/didChangeWorkspaceFolders`](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWorkspaceFolders)

**Comment by cdietrich** [comment]
@kittaakos does this make sense if we dont support / ignore `org.eclipse.lsp4j.InitializeParams.workspaceFolders`
in the initialize request?

**Comment by kittaakos** [comment]
Yes, sure. We have to adjust the `initialize` as well. Otherwise, it won't work. Sorry for not being clear about it. This should be part of the task.
