### ISSUE TITLE
[LSP] 2.19.0 WebSocket support example / documentation

### ISSUE THREAD

**Issue by PHameete** [eclipse/xtext-core#1239]
I am excited to see in the release notes that Xtext 'now uses LSP4J version 0.8.0 / Language Server Protocol version 3.14.0. This allows you to consume Xtext Language Servers through WebSocket.'

I'm currently using a custom implementation of a Websocket Server in front of the LSP, which allows multiple clients to use the LSP in parallel.
Does the official WebSocket implementation allow multiple clients? And is there an example/documentation on how to use the Xtext LSP via WebSockets?

**Comment by cdietrich** [comment]
no there is no documentation. yes it allows multiple clients. the code / api is in lsp4j. 
there is no official example for that but you can read through https://github.com/eclipse/lsp4j/issues/203

**Comment by PHameete** [comment]
@cdietrich thanks for the response! It took me some time to figure out exactly how to use it. Mostly because I was unfamiliar with the javax.websocket and LSP4J APIs.

I am retrieving a new LanguageServerImpl for every WebSocket session. Is that the suggested way to do this? I remember you saying each LanguageServer is built to serve one client.

Here's the xtend code for who is interested (perhaps you might want to use it as example?).

First create a LSP4J WebSocketEndpoint that uses the Xtext LanguageServerImpl: 
```xtend
class LanguageServerEndpoint extends WebSocketEndpoint<LanguageClient> {

	final static Injector injector = Guice.createInjector(new ServerModule())

	override configure(Launcher.Builder<LanguageClient> builder) {
		val server = injector.getInstance(LanguageServerImpl);
		builder.setLocalService(server).setRemoteInterface(LanguageClient)
	}

	override connect(Collection<Object> localServices, LanguageClient remoteProxy) {
		localServices.forEach[s|(s as LanguageServerImpl).connect(remoteProxy)]
	}
}
```

Then define a ServerApplicationConfig for the programatically defined server endpoint:
```
class LSPWebsocketServerConfigProvider implements ServerApplicationConfig {
	
	override getAnnotatedEndpointClasses(Set<Class<?>> scanned) {
		return scanned
	}
	
	override getEndpointConfigs(Set<Class<? extends Endpoint>> endpointClasses) {
        val config = ServerEndpointConfig.Builder.create(LanguageServerEndpoint, "/").build
        return Set.of(config)
	}	
}
```

Finally I used Tyrus + Grizzly to run a standalone Websocket Server:
```java
public class LSPWebsocketServer {

    private static Logger log = LoggerFactory.getLogger(LSPWebsocketServer.class);

    public static void main(String[] args) {
        String host = "localhost";
        int port = 5051;
        Server server = new Server(host, port, null, null,
            LSPWebsocketServerConfigProvider.class);

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            log.info("Stopping LSP WebSocket Server...");
            server.stop();
        }, "lsp-websocket-server-shutdown-hook"));

        try {
            server.start();
            log.info("LSP WebSocket Server started at {}:{}", host, port);
            Thread.currentThread().join();
        } catch (Exception e) {
            throw new RuntimeException(e);
        } finally {
            server.stop();
        }
    }

}
```

**Comment by cdietrich** [comment]
also have a look at the linked elk example https://github.com/OpenKieler/elkgraph-web/pull/13/files#diff-dc0f9c1dec5e5df77b8b2be6746c2e10 that i intended you to have a look at

**Comment by PHameete** [comment]
@cdietrich yes thanks for the pointer. Jetty is also possible of course and eliminates the need for the config provider. Code is then as follows, and I believe a bit more simple than the example you linked:

Websocket Endpoint definition:
```xtend
class LanguageServerEndpoint extends WebSocketEndpoint<LanguageClient> {

	final static Injector injector = Guice.createInjector(new ServerModule())

	override configure(Launcher.Builder<LanguageClient> builder) {
		builder.localService = injector.getInstance(LanguageServer);
		builder.remoteInterface = LanguageClient
	}

	override connect(Collection<Object> localServices, LanguageClient remoteProxy) {
		localServices.filter(LanguageClientAware).forEach[connect(remoteProxy)]
	}

}
```

Standalone Jetty Server that serves the Endpoint:
```xtend
class LspWebsocketServer {

	static val log = LoggerFactory.getLogger(LspWebsocketServer);

	def static void main(String[] args) {
                val host = "localhost"
                val port = 5051
		val server = new Server()
		val connector = new ServerConnector(server)
		connector.port = host
		connector.host = port
		server.connectors = #[connector]

		val context = new ServletContextHandler
		context.contextPath = "/"
		server.handler = context

		val container = WebSocketServerContainerInitializer.initialize(context)
		val endpointConfig = ServerEndpointConfig.Builder.create(LanguageServerEndpoint, "/").build
		container.addEndpoint(endpointConfig)

		Runtime.runtime.addShutdownHook(new Thread([
			log.info("Stopping LSP WebSocket Server...");
			server.stop();
		], "LSP-websocket-server-shutdown-hook"));

		log.info("LSP WebSocket Server started at {}:{}", host, port);
		server.start
	}
}
```

**Comment by PHameete** [comment]
Also note that in the example you link they use a single LanguageServer instance to serve all WebSocket clients. I've seen this can lead to concurrency exceptions so I would suggest to create an instance per client.

**Comment by PHameete** [comment]
Thanks for the help @cdietrich Ill close this now.
