### ISSUE TITLE
'Xtext' language artifacts can't be generated

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-core#125]
The former helper bundle 'org.eclipse.xtext.bootstrap' apparently got lost during the repository split.
However, it seems to be necessary to have such a (sub) project in order to get the fragments referenced in the generator workflow resolved, as well as the `Mwe2Launcher`.
(btw: currently there's no workflow)

Further question: How could we handle the generation of the IDEA-specific artifacts?
The corresponding fragments are located in 'org.eclipse.xtext.idea.generator' that is part of the xtext-idea repository. It however has not been released to JCenter, has it? Hence we cannot simply reference the latest released version.

**Comment by sailingKieler** [comment]
Created a draft version of the bootstrap project in [cs/xtext-bootstrap](https://github.com/eclipse/xtext-core/tree/cs/xtext-bootstrap) that works for me:
* copied the workflow + launchConfig from the old repository
* the generation of the idea-specific parts is not solved, yet, and thus deactivated

**Comment by spoenemann** [comment]
Fixed with #202.
