### ISSUE TITLE
Performance improvement for StateBasedContainer

### ISSUE THREAD

**Issue by tisis2** [eclipse/xtext-core#1252]
In Workspaces with a huge index the implementation of getExportedObjectsByType gets slow, since its first filtering by type and then the uri filter is applied on the result. We see small Projects get affected by big workspaces (content assist, reparse,...)

**Comment by tisis2** [comment]
When profiling we saw a lot of pressure on the EObjectDescriptionLookUp.getExportedObjectsByType in a wokspace with a huge index.

I created an implementaion of IResourceDescription that filters the resource descriptions to the actual visible one in the current container state. On this way the filtering if the resource is acutally in the current state happens before the filtering of all exported Objects by their type.

**Comment by tisis2** [comment]
since the pull request #1253 does not solve this problem anymore, what should we do with this issue?

**Comment by cdietrich** [comment]
would it keep open for now but remove it from any milestone

**Comment by cdietrich** [comment]
=> with https://github.com/eclipse/xtext-core/pull/1253 we will allow to customize this easier but we will leave this issue open for now

**Comment by szarnekow** [comment]
Please re-open in https://github.com/eclipse/xtext if the problem is still present.
