### ISSUE TITLE
Endless loop in NodeIterator when start node is null

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-core#1262]
We should assert `INode startWith` is not null or better fix the  hasNext()  implementation.

To reproduce:

```
import org.eclipse.xtext.nodemodel.util.NodeIterator;

public class Test {

	public static void main(String[] args) {
		new NodeIterator(null).forEachRemaining(e -> {
			System.out.println("Loop");
		});
	}

}
```

**Comment by rablewis** [comment]
I'm willing to take this as my first issue.
It should be easy to fix by modifying hasNext() like this:

```java
public boolean hasNext() {
	return (lastReturned == null && startWith != null) || lastReturned.hasNextSibling();
}
```

I would propose also making a similar change to hasPrevious().

Any comments on the above approach or on appropriate testing before I proceed?

Thanks.
-R

**Comment by szarnekow** [comment]
Sounds very good to me. Please go ahead.

**Comment by cdietrich** [comment]
@rablewis are you still going to work on this issue?

**Comment by rablewis** [comment]
I'd like to. I am having dependency issues that are preventing me from getting started. I'm going to seek advice today. I'll report back on progress tomorrow.

**Comment by rablewis** [comment]
There was a failure in the Maven build stage of the Jenkins build. I don't see how this could be related to my changes, but please let me know if there's something I need to fix. Thanks. -rab

**Comment by cdietrich** [comment]
hi, the ci is currently running slow and admins not available over the weekend. https://bugs.eclipse.org/bugs/show_bug.cgi?id=559314

**Comment by cdietrich** [comment]
@szarnekow anything left?

**Comment by szarnekow** [comment]
Fixed. Thank you @rablewis
