### ISSUE TITLE
Bogus Generator for Label providers

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1272]
Bogus Generator for Label providers:

Depending on if Xtend or Java is used for the generation the Label providers have comments with and without the word see

 `See <url>`  vs  `<url>` 

see comments in https://github.com/eclipse/xtext-eclipse/pull/1241/files

**Comment by cdietrich** [comment]
there are also places where @override is inconsistent (description label provider)

**Comment by miklossy** [comment]
Fuxed in 2.21.
