### ISSUE TITLE
The projectWizard fragment always regenerates icons in the UI project "icons" folder

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#1321]
The projectWizard fragment always regenerates icons in the UI project "icons" folder and I think this is not intentional. In particular, if one customizes such icons on the next MWE2 run they will be replaced. Of course one could change the reference to the icon in the plugin.xml but I don't think such a regeneration is correct. @miklossy what do you think?

**Comment by miklossy** [comment]
I think that the icons should not be overridden once they are customized.
