### ISSUE TITLE
Consider removing LineFilterOutputStream and mark as deprecated

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-core#1328]
We should use BufferedOutputStream or remove LineFilterOutputStream from Xtext. 
I don't recall why we have a copy here...

See https://github.com/eclipse/mwe/pull/138

**Comment by cdietrich** [comment]
i will have a look at some of the testlanguages workflows if the LineFilterOutputStream  shows up

**Comment by cdietrich** [comment]
LineFilterOutputStream actually does not show up
just the one of mwe does.

@szarnekow do you know if LineFilterOutputStream is used anywhere?

**Comment by dhuebner** [comment]
I could imagine in downstream projects, but I'm not sure

**Comment by szarnekow** [comment]
Certainly no usages anymore in Xtext.
We used to have the ecore generator stuff in the Xtext repo. Since that was moved to MWE, we apparently don't use the filtering in Xtext anymore. The type should be deprecated and removed a few releases in the future.

**Comment by cdietrich** [comment]
thus we can close this one as wontfix / not relevant?

**Comment by dhuebner** [comment]
I can re-name the issue to "Mark as deprecated prepare for removal"

**Comment by cdietrich** [comment]
done
