### ISSUE TITLE
The generated parent POM ignores maven-resources-plugin goals

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#1335]
The generated parent POM for an Xtext project has an m2e lifecycle mapping that ignores the goals `resources` and `testResources` of the `maven-resources-plugin`. This breaks the standard m2e building mechanism that in Eclipse copies the resources to the target folder. In fact, by default, m2e disables the standard JDT copy mechanism for resource folders (with `classpathentry excluding="**"`), see the FAQ "Why do Resource Folders in Java Project Have excluded="*"" (https://www.eclipse.org/m2e/documentation/m2e-faq.html). With the exclusion above, resources are not copied into output folder automatically when using Eclipse. Of course one could change the classpath entry, but updating a Maven project will bring the filter back, for good reasons, as explained in the FAQ.
I can provide a PR, but I first wanted to be sure that such filter has no further intended meaning for Xtext.

**Comment by cdietrich** [comment]
i have no clue what the intended behaviour is here.

**Comment by LorenzoBettini** [comment]
What's in a Maven "resources" folder is meant to be accessible from the ClassLoader, so it must be in the target folder. The default behavior should be left intact, IMHO.

**Comment by cdietrich** [comment]
but how to solve your initial bug then?

**Comment by LorenzoBettini** [comment]
The wizard should not generate that lifecycle making exclusion, that's what I was suggesting

**Comment by cdietrich** [comment]
I am not firm with the lifecycle mappings but you remove it the original error should come back. At least when there is no m2e connector installed

**Comment by LorenzoBettini** [comment]
Sorry, probably I wasn't clear enough describing the problem, please let me try to explain it:

- The m2e builder takes care automatically of handing the standard `resources` and `testResources` goals of the `maven-resources-plugin`: it copies the contents of source folders, which are `resource` folders, into the `target` folder during the standard Eclipse building. In order to avoid conflicts with the JDT building mechanism (which copies all the contents of **any** source folder of an Eclipse project into the output folder, unless filters are explicitly specified), m2e excludes JDT copying mechanism for source folders that are Maven resource folders (by generating `classpathentry excluding="**"` for resource source folders in the `.classpath` file); this works out of the box for an Eclipse project with the Maven nature (meant to be handled by m2e). If you manually modify the `.classpath`, on the next "Maven update project" invocation, the `.classpath` is modified back. Again, the m2e FAQ explains why it should be like that.
- The Xtext project wizard generates an m2e lifecycle mapping configuration that prevents the m2e standard builder from performing the above copying. The final result, is that resources and test resources are not copied in the output folder(s) during the Eclipse building, breaking tests that rely on the resources being available through the class loader, which is the expected behavior. This leads to a bad Eclipse experience. By the way, when this happens, and you're not familiar with lifecycle mapping, it's quite hard to understand what's going on (that was also my case that led me to track the problem down to the generated lifecycle mapping exclusion, after studying a few bits of m2e lifecycle mapping and reaching the mentioned FAQ).

I was suggesting to remove the generation of such a lifecycle mapping exclusion in the parent POM, since it makes no sense: it only breaks the automatic (and expected) behavior in Eclipse without any benefit. Note that  since it's documented in m2e, I seem to understand that no additional connector is required: it's just plain m2e that handles those standard Maven plugin's goals.

The other generated lifecycle mapping exclusions (e.g., for build helper plugin) make sense because otherwise additional m2e connectors are required to be installed.

I also add @kthoms to the discussion in case my understanding of m2e is wrong.

**Comment by cdietrich** [comment]
I don’t understand. Some years ago you introduced the thing that’s here right now to get rid of an error so if you undo that change the error will be back. So you don’t plan to remove the mapping but do something else ?

**Comment by LorenzoBettini** [comment]
I was suggesting to remove only this part

```xml
<pluginExecution>
	<pluginExecutionFilter>
		<groupId>
			org.apache.maven.plugins
		</groupId>
		<artifactId>
			maven-resources-plugin
		</artifactId>
		<versionRange>
			[2.4.3,)
		</versionRange>
		<goals>
			<goal>resources</goal>
			<goal>testResources</goal>
		</goals>
	</pluginExecutionFilter>
	<action>
		<ignore></ignore>
	</action>
</pluginExecution>
```

not the other ones.

You mean I'm the author of such part? I don't remember O:)

In any case, I'll double check that in an Eclipse Xtext distribution with m2e (but no other manually installed connectors) there's no error in the POM if I remove that lifecycle exclusion.

**Comment by cdietrich** [comment]
Yes I saw you in git blame

**Comment by LorenzoBettini** [comment]
You're right, I'm to blame :)
Then sorry about that. The other mappings were introduced by @oehme and I think they still should be there. But the one I added breaks the above mechanism. I'll create a PR then, after checking that without additional connectors everything works with m2e alone, OK?

**Comment by cdietrich** [comment]
Would be ok with that but let’s see what Karaten and Sebastian think

**Comment by LorenzoBettini** [comment]
So I'm adding @szarnekow to the discussion as well

**Comment by szarnekow** [comment]
I'm not sure if removing the lifecycle mapping is really the right thing to do here, or not. In the end the .classpath and .project files should be created in the same way as the update classpath action would do it - e.g. there shouldn't be any changes by triggering update classpath. And of course the projects should work correctly: After an incremental build in Eclipse, everything should be put into the correct subdirs of target. Last but not least, there shouldn't be any errors or warnings in the generated projects.
@LorenzoBettini In a nutshell, I'm looking forward to the proposed changes given that we currently produce projects that are not 100% correct.

**Comment by LorenzoBettini** [comment]
OK, I'll do my experiments tomorrow.

Since I'm the original author of that lifecycle mapping exclusion I can add that at that time I didn't know much about m2e lifecycle mappings (sorry about that) and now I'm pretty sure that exclusion is not correct as I described above (again, sorry O:) I just have to check that without such an exclusion we get a 100% error free project with an Eclipse distribution with just Xtext and m2e.

Probably it hasn't been an issue so far because you're hit by this problem only if you have a project (Maven project, not Tycho) inheriting from the parent POM with Eclipse source folders corresponding to standard Maven resource folders (e.g., `src/main/resources` and `src/test/resources`) with unit tests expecting to find resources in the output folder (`target/classes` and `target/test-classes`, respectively). Indeed I was hit myself when implementing a Maven plugin for one of my Xtext DSLs.

**Comment by LorenzoBettini** [comment]
I confirm that with a DSL Eclipse distribution (which comes with m2e and its default connectors), after creating an Xtext project (with Maven support), removing that lifecycle exclusion still gives a 100% error free project :)

I'll provide a PR ASAP

**Comment by kthoms** [comment]
I think the intention is not to disable the resources plugin, but rather to enable it by default. The original exclusion was added because you get these annoying error markers in POMs for plugins that m2e has no lifecycle connector by default. I think with a plain Eclipse distro you will get the error markers again, as it won't contain the connectors by default.

From [m2e 1.7](https://www.eclipse.org/m2e/documentation/release-notes-17.html) on there is simplified way to add lifecycle mappings within the pom, see #1551. I think the appropriate mapping would be 
```
<?m2e execute onConfiguration,onIncremental?>
```

**Comment by LorenzoBettini** [comment]
@kthoms with the PR those "resource" goals are not excluded anymore and with m2e alone those are handled correctly (no other connectors are needed: as I said above, I tried that). As you said, those lifecycle mapping exclusions are usually added to remove errors in Eclipse, but for those goals of the standard Maven plugins, that's not needed (and, instead, adding the exclusions break a few things in Eclipse, as I said). Note that the other lifecycle mapping exclusions are still there (those that require additional connectors).

Which issue 1551 are you referring to?

**Comment by cdietrich** [comment]
@LorenzoBettini  this here: https://github.com/eclipse/xtext/issues/1551

**Comment by LorenzoBettini** [comment]
Interesting! However the resources plugin is handled by m2e, otherwise you wouldn't be able to create a simple maven project in eclipse without errors. That's why I was proposing to remove the lifecycle mapping exclusion.

**Comment by kthoms** [comment]
OK, could be that for standard plugins this is handled by m2e already without additional connectors. The POMs should just show no error with m2e but without additional connectors. If that's the case I'm fine with your change.

Which issue 1551 are you referring to?
[1551](https://github.com/eclipse/xtext/issues/1551)

**Comment by LorenzoBettini** [comment]
@kthoms OK, then I'm going to merge the PR
