### ISSUE TITLE
The new Xtext project wizard should create the xtend-gen folder only if necessary

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#1341]
Currently, the new Xtext project wizard creates the `xtend-gen` folder in all plug-ins, even if the corresponding `src` folder contains no `*.xtend` files.
![screenshot](https://user-images.githubusercontent.com/20393472/71882159-37a76880-3134-11ea-926a-72818e3e664d.png)

That behaviour should be improved to create the `xtend-gen` folder only if the corresponding `src` folder contains at least one `*.xtend` file.

**Comment by cdietrich** [comment]
@miklossy how will you find that out?

**Comment by miklossy** [comment]
I would suggest to modify the wizard that it does not create any `xtend-gen` folder. Executing the mwe2 workflow will create the `xtend-gen` folder on demand anyway. Moreover, if the user adds an `*.xtend` file to the `src` folder, the `xtend-gen` folder will be created automatically.

**Comment by szarnekow** [comment]
In that case, the order of src folders should be fixed first. The automatically created xtend-gen folder is usually added to the front of the list. This is not nice for end users. Maybe add it as the last source folder (immediately after the previously last classpath entry that is a source folder) instead?

**Comment by cdietrich** [comment]
in the past build.properties files always made problem when auto add xtend-gen folders. thus i dont see this as a viable alternative

**Comment by szarnekow** [comment]
That would need to be fixed, too

**Comment by miklossy** [comment]
- [ ] Ensure newly created `xtend-gen` folder (by Eclipse/MWE2) is added as the last entry of the classpath.
- [ ] Ensure the newly created `xtend-gen` folder (by Eclipse/MWE2) is added to the `build.properties` file.
- [ ] Ensure the New Xtext Project wizard does not create any `xtend-gen` folder by default.

**Comment by cdietrich** [comment]
@miklossy samw for maven and gradle build configs. i still have doubts it is worth it.

**Comment by miklossy** [comment]
I understand. Let's postpone it.

**Comment by szarnekow** [comment]
Please open a ticket in https://github.com/eclipse/xtext if you want to pick this up eventually.
