### ISSUE TITLE
XtextVersionTests fails with milestone versions

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1351]
the pattern in XtextVersionTests does not accept e.g. `2.21.0.M1`

**Comment by cdietrich** [comment]
cc @kthoms

**Comment by ArneDeutsch** [comment]
In `TargetPlatformProject` there is a conditino that selects update repositories based on this version string:

```
<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
	<unit id="org.eclipse.xtext.sdk.feature.group" version="0.0.0"/>
	«IF config.xtextVersion.isSnapshot»
		<repository location="https://download.eclipse.org/modeling/tmf/xtext/updates/nightly/"/>
	«ELSEIF config.xtextVersion.isStable»
		<repository location="https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/"/>
	«ELSE»
		<repository location="https://download.eclipse.org/modeling/tmf/xtext/updates/releases/«config.xtextVersion»/"/>
	«ENDIF»
</location>
```

Notable: e.g. `2.9.2.beta3` is considered stable by this code whereas `2.9.2` is NOT stable (but release). Considering this I would think `2.21.0.M1` should be considered to be stable, too. Then it will load from `milestones`.

**Comment by cdietrich** [comment]
has this changed? hmmmmm

**Comment by cdietrich** [comment]
@ArneDeutsch 

```
	public static void main(String[] args) {
		System.out.println(new XtextVersion("2.21.0.M1").isStable());
	}
```

gives true for stable

**Comment by ArneDeutsch** [comment]
Yes, just did the same test. But then I wonder where this ticket originates from. Seems the test works well ...

**Comment by cdietrich** [comment]
the test itself has a pattern.
and that one fails

**Comment by cdietrich** [comment]
(see PR)

**Comment by ArneDeutsch** [comment]
Ok, as the test is quite new I would say @kthoms has missed the milestone case and your fix is ok.

**Comment by cdietrich** [comment]
yes but i dont know if karsten had some intention behind the test this is why i wait for the review
