### ISSUE TITLE
Create named constant for language file extension

### ISSUE THREAD

**Issue by stevehickman** [eclipse/xtext-core#1356]
Whenever a new DSL is defined, it is associated with a file extension. That string is used throughout the generated code (e.g. in <DSL>FileTemplateProvider.xtend, <DSL>ProjectTemplateProvider.xtend, Abstract<DSL>RuntimeModule.java, <DSL>StandaloneSetupGenerated.java, and possibly other places). In each case, the raw string itself is inserted into the generated code. 

Further, if developers need to parse strings containing that language, they will use that same file extension to generate an appropriate URL. 

It would be nice if this file extension were stored in a named constant as part of the generated code. That would make it easy to guarantee that nothing breaks if the spelling/capitalization of that extension is changed.

**Comment by cdietrich** [comment]
as AbstractRuntimeModule / StandaloneSetupGenerated are generated this is fine.

for FileTemplateProvider / ProjectTemplateProvider i dont know why.

**Comment by miklossy** [comment]
I think the reason is that the File Templates are instantiated with the `new` keyword, (see the [statemachine example](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineFileTemplateProvider.xtend#L23)) and not created by guice, so the `FileExtensionProvider` cannot be injected into them.

@stevehickman Using the `FileExtensionProvider.getPrimaryFileExtension()` method would solve your problem?

**Comment by stevehickman** [comment]
I'll check. I'm using 3 different (related) languages in the same code, so I'll need to make sure I'm using the correct FileExtensionProvider.

**Comment by cdietrich** [comment]
IGlobalServiceProvider might help with that

**Comment by cdietrich** [comment]
@miklossy @ArneDeutsch but why are they created with new and not with a `Provider`

**Comment by miklossy** [comment]
Since the Wizard API is still considered as `@Beta`, we could change that without breaking the API.

**Comment by cdietrich** [comment]
isnt the file generate once.
so no problem?

**Comment by ArneDeutsch** [comment]
Your discussion is about this pieco of code, right?

**Comment by cdietrich** [comment]
yes. respecively the hardcoded e.fileextension in the wizard

**Comment by stevehickman** [comment]
I apologize if I should know this but...
I looked at the doc for IGlobalServiceProvider. There are 2 findService methods, each with 1 line of documentation.  Since I need the extension to construct a URI, I know I can't use the findService method that requires a URI.  The other findService appears to require an instance of a class from the language I want. I don't yet have any instances because I want to parse a string and create instances as a result - and I need the IResourceServiceProvider for that language to do that.

So it seems like I have a circular dependency.  Am I missing something?

**Comment by cdietrich** [comment]
you can call IGlobalServiceProvider with the URIs.
but if you know neither the languages
(so that you can ask each injector for an file extension)
 nor the file extensions (to use global service provider)
i dont see any chance.

so why dont you know the n injectors?

**Comment by stevehickman** [comment]
Currently I know the extension and am using that to create the injector.  However, I have the extension hard-coded as a plain string. What I was hoping for is a named constant to be generated by XText so that if someone decides to change the extension in the future, it won't break my code.

**Comment by cdietrich** [comment]
why dont you know the standalonesetups injectors?
i have no idea how you create the injectors knowing the file extensions

**Comment by stevehickman** [comment]
I apologize. I mistated. Here's what I'm doing:
`
	static IResourceServiceProvider sqlRSP;

		if (sqlRSP == null) {
			URI sqlURI = com.honeywell.common.util.File.genUniqueURI("file","fake","qbirtSQL");
			sqlRSP = IResourceServiceProvider.Registry.INSTANCE.getResourceServiceProvider(sqlURI);

		}
		resourceSet = sqlRSP.get(XtextResourceSet.class);
		validator = sqlRSP.get(IResourceValidator.class);
`

**Comment by cdietrich** [comment]
are you in eclipse or are you in standalone?

**Comment by stevehickman** [comment]
In eclipse - but I do need the ability to run standalone as well.

**Comment by cdietrich** [comment]
yes but these are 2 completely different usecases.
how do you know which of the 100 dsls installed to your eclipse are yours and which are others

**Comment by stevehickman** [comment]
For each DSL I want to process, I have a class that does what I show above. In each case, the extension is for the appropriate DSL.

**Comment by cdietrich** [comment]
Yes but then you can also use the n standalone setups ( standalone use case ) and Activator.getInjector (constant) in eclipse case

**Comment by stevehickman** [comment]
I will check it out. Thx.

**Comment by cdietrich** [comment]
as we have FileExtensionProvider i am inclined to close this
@szarnekow @kthoms what do you think?

**Comment by szarnekow** [comment]
Agreed. There is often not `the` file extension but multiple extensions. Some language even use content types. A single generated constant may be misleading.

**Comment by cdietrich** [comment]
how shall we proceed here

**Comment by ArneDeutsch** [comment]
I think you have decided to close this and I agree. I do not see what can be done here.
