### ISSUE TITLE
LSP4J: Find a Solution for Deprecation of Marked String in Hover

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1372]
org.eclipse.lsp4j.Hover uses MarkedString which is deprecated and replaced by MarkupContent
we should have a look on how we adapt

**Comment by cdietrich** [comment]
@tivervac do you make use of this?

**Comment by tivervac** [comment]
I’m on vacation right now, but I’ve informed my colleagues. Hopefully they’ll get back to you.

**Comment by davidmedinasigasi** [comment]
@cdietrich We use it in a very few places, so it should be easy to replace

**Comment by cdietrich** [comment]
@kittaakos would you be fine if i refactor hoverservice?

**Comment by kittaakos** [comment]
> would you be fine if i refactor hoverservice?

Please. Thank you! <3

**Comment by cdietrich** [comment]
Fixed with 2.21
