### ISSUE TITLE
Maven build for Language Server not working

### ISSUE THREAD

**Issue by hannesN** [eclipse/xtext-core#1382]
I created a new Xtext-Project using maven (tycho) and creating a regular language server.

After building the language server doesn't start (in target/languageserver/bin).
The reason is, that the repo folder contains the wrong jars. They contain a feature.xml instead of class files.

My solution adds a exclude rule to the copy-dependencies configuration:
<excludeGroupIds>p2.eclipse-feature</excludeGroupIds>
This filters the p2 feature dependencies and uses the eclipse-plugins instead.

I will provide a PR.

**Comment by cdietrich** [comment]
Fixed in 2.21
