### ISSUE TITLE
[lsp] support multi-root workspaces

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-core#1391]
LSP allows a workspace to be composed of multiple root folders. Xtext-based LSs should support that.

- [ ] properly report the capabilities in the initial handshake
- [ ] set up workspace/project config from multiple workspace roots
- [ ] support workspace folders change events

**Comment by JanKoehnlein** [comment]
Duplicate of #1238

**Comment by cdietrich** [comment]
@JanKoehnlein anything left?

**Comment by JanKoehnlein** [comment]
Nothing I am aware of. I will merge now.
