### ISSUE TITLE
Cleaning up all deprecated methods/classes in the xtext.ide.server package

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#1394]
See [comment](https://github.com/eclipse/xtext-core/pull/1393#pullrequestreview-361786523)

**Comment by JanKoehnlein** [comment]
I'd also want to deprecate and schedule for removal this single workspace root stuff. I'll create a PR

**Comment by cdietrich** [comment]
@JanKoehnlein can you please take care about the cleanup of the single root deprecations.
i should have cleaned up everything else if nothing slipped through

**Comment by JanKoehnlein** [comment]
I will, but not before Monday

Von meinem iPhone gesendet

**Comment by cdietrich** [comment]
any update @JanKoehnlein

**Comment by cdietrich** [comment]
Fixed in 2.22

thx @JanKoehnlein
