### ISSUE TITLE
2.10.1 is not published on maven central

### ISSUE THREAD

**Issue by akosyakov** [eclipse/xtext-core#141]
See: https://mvnrepository.com/artifact/org.eclipse.xtext/org.eclipse.xtext

**Comment by LorenzoBettini** [comment]
I seemed to remember that 2.10.1 was not meant to be released, was it?

**Comment by cdietrich** [comment]
Yes we discussed this 2 month ago. It seems the maintenance p2 repo for nightly or milestone contains this version but there never was a release

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-eclipse/issues/83 as well
