### ISSUE TITLE
Get rid of the Xtext IDEA generator

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#1427]
Since the Xtext Framework has already [dropped support](https://github.com/eclipse/xtext/issues/1278) for the IntelliJ IDEA, I think the [XtextProjectConfig.ideaPlugin](https://github.com/eclipse/xtext-core/blob/f9b6d1bebe09dc5775d45671d255384a8160015c/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/XtextProjectConfig.xtend#L40) field should be marked as `Deprecated`.

@cdietrich What do you think? If you agree, I can provide the corresponding PR.

**Comment by szarnekow** [comment]
Please delete it instead of marking as deprecated.

**Comment by miklossy** [comment]
Thanks for the PR @cdietrich ! I changed the title of this issue to better reflect to work to be done.

**Comment by cdietrich** [comment]
Fixed in .22
