### ISSUE TITLE
Synchronization strategy in ExecutorServiceProvider is flawed

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-core#1445]
Should be a ConcurrentHashMap, otherwise the synchronization attempt in get(String) is completely flawed

_Originally posted by @szarnekow in https://github.com/eclipse/xtext-core/pull/1442_

**Comment by cdietrich** [comment]
@nbhusare will work on this

**Comment by cdietrich** [comment]
@szarnekow @nbhusare anything left open?

**Comment by szarnekow** [comment]
Fixed. THank you @nbhusare
