### ISSUE TITLE
Offset error in VSCode

### ISSUE THREAD

**Issue by ewenmaclean** [eclipse/xtext-core#1451]
I am writing here on the suggestion of @akosyakov  - unfortunately I cannot share the exact code and I cannot make a minimal repro where the issue manifests. 

I am using a formatter declared in xtext  extending `AbstractFormatter2` and injecting the generated grammar access which extends `AbstractGrammarElementFinder` - this works very well in the web-baed monaco editor. 

I am now using the latest snapshot version of xtext 2.21 and lsp4j 0.9.0 - but the problem manifested itself first in 2.15.0 and lsp4j 0.4.0, and only seems to manfest in VSCode. The VSCode version I am using is `1.44.2`

When I use the xtext formatter in monaco or in tests everything works fine for our DSL - however in VSCode if do the following steps:
```
- format the code (This works fine)
- insert an error
- format the code (This works fine)
- undo the error insertion (using ctrl-Z) and revert to the original code
- format the code again
```
this results in the following error showing in VSCode - with no references to our specific project jars - only xtext library jars and deeper:
```
 [pool-1-thread-1] ERROR t.ide.server.concurrent.ReadRequest  - Error during request: 
java.lang.IndexOutOfBoundsException: Position [
  line = 26
  character = 34
]
	at org.eclipse.xtext.ide.server.Document.getOffSet(Document.java:76)
```

I realise this is very minimal detail, but I wondered if perhaps someone else had seen the same behaviour in VSCode and was aware of a way of controlling what looks to be erroneous offset data being sent. Many thanks indeed in advance for looking at this.

**Comment by cdietrich** [comment]
without any concrete hints how to reproduce i dont think we can do anything here

**Comment by ewenmaclean** [comment]
I appreciate that - alas I can't share the code publicly.  Thanks for looking - I asked just in case it might have been something observed before.

**Comment by cdietrich** [comment]
@ewenmaclean did you debug this locally?

**Comment by ewenmaclean** [comment]
Thanks for this I will study -  I did debug the ide project and by suspending the running VSCode process but could not reproduce. If I am able to get a more insightful trace I will post it but I appreciate you cannot do anything more without specific code. Thanks for the tips - I will study and see if I can any further debugging.

**Comment by cdietrich** [comment]
you should be able to set a breakpoint at the place the exception is thrown

**Comment by ewenmaclean** [comment]
Thanks for your help. I will report back if I can reproduce with a minimal example in debugging.

**Comment by cdietrich** [comment]
@ewenmaclean did you find out anything?

**Comment by ewenmaclean** [comment]
I'm afraid I haven't been able to reproduce while debugging but other developments have got in the way. I will try again when I get some time and report back anything I find.

**Comment by ewenmaclean** [comment]
@cdietrich sorry for the very late response on this. I did discover the reason, but as yet don't have a fix. In my implementation of the xtext server when I connect via websocket using monaco or VSCode, undo doesn't send a request and hence the offset error on hover or reformat - I would expect e.g. a `textDocument/didChange` RPC request (which would make the offsets consistent in the server) but it is not send (on inspecting network traffic). These are the capabilities send back from the server:
```
result: {capabilities: {textDocumentSync: 2, hoverProvider: true,…}}
capabilities: {textDocumentSync: 2, hoverProvider: true,…}
codeActionProvider: false
completionProvider: {resolveProvider: false, triggerCharacters: ["."]}
resolveProvider: false
triggerCharacters: ["."]
definitionProvider: true
documentFormattingProvider: true
documentHighlightProvider: true
documentRangeFormattingProvider: true
documentSymbolProvider: true
executeCommandProvider: {commands: []}
commands: []
hoverProvider: true
referencesProvider: true
renameProvider: {prepareProvider: true}
prepareProvider: true
semanticHighlighting: {scopes: []}
scopes: []
signatureHelpProvider: {triggerCharacters: ["(", ","]}
triggerCharacters: ["(", ","]
textDocumentSync: 2
workspaceSymbolProvider: true
```
I'll keep trying to work it out but I suspect some capability isn't set up in the server

**Comment by cdietrich** [comment]
if vscode does not send an undo, does not this seen to be a vscode bug then?

**Comment by cdietrich** [comment]
when i do undo in vscode i get

```
{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 8,
      "uri": "file:///home/dietrich/git/xtext-languageserver-example/demo/a.mydsl"
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 4,
            "character": 0
          },
          "end": {
            "line": 5,
            "character": 10
          }
        },
        "rangeLength": 11,
        "text": ""
      }
    ]
  }
}
```
which is a clear delete

**Comment by ewenmaclean** [comment]
Thanks very much for looking - sorry I am sure you are right it is/was a VSCode bug - it wasn't clear to me initially. In linked issue it seems to be monaco rather than VSCode and I'll investigate there - please feel free to close here obviously if feel that is right,

**Comment by szarnekow** [comment]
Closed as per the last comment.
