### ISSUE TITLE
Syntax errors will lead to unexpected calls to value converters

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-core#1462]
An input document with syntax errors may lead to value converters being called with the previous node rather than the real node of the value.

**Comment by ewillink** [comment]
This is a breaking API chnage that prevents most Xtext parsers built now beinbg used on any 2020-03 and earlier platform. See tail of https://bugs.eclipse.org/bugs/show_bug.cgi?id=563442

New code gets to see both setWithLastConsumed signatures and so does not box 'true' arguments. When run on an old Xtext without the signature the lack of boxing gives a NoSuchMethodError.

Please revert ASAP, (and avoid the need for boxing by using Boolean.TRUE.

**Comment by cdietrich** [comment]
@ewillink it would also help to actually describe the problem you have.
afaik we do not allow  Xtext Parsers generated with 2.22 to be run with Xtext 2.21

**Comment by szarnekow** [comment]
Ed,
this has been discussed extensively in the past. Xtext generators are forward compatible but code generated with version x is not supposed to be compatible to runtime version x-1. 
What you are suggesting is (a) that we cannot change anything ever or (b) need to maintain a generator flag similar to EMF GenModels runtime version. Both contradict the effort to avoid unnecessary maintenance costs. 
If you need to generate with Xtext 2.22, you can used patched versions of the generator fragments.
If you need to run Xtext 2.21, you can generate with Xtext 2.21.

**Comment by ewillink** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=563476 raised to at least document the compatibility problem, where Bugzilla searches will find it, and to identify workarounds that Xtext or users can pursue.
