### ISSUE TITLE
Global unique name validation

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-core#1466]
The NamesAreUniqueValidator allows to validate the exported objects from a single resource.

It is desired to have such a validation across file boundaries. The scope of the validation should be configurable, e.g. per Resource (cf NamesAreUniqueValidator), per xtext.IContainer, across all visible IContainers and globally across all the entire IResourceDescriptions.

Non-functional requirement: This should not impose a notable performance penalty.

Part of this will be a means to customise the logic of `IResourceDescription.Manager.isAffected` based on the semantics of validations. If a two resources export the same names and validation issues are created on these, both of them must be validated if one of them changes.

**Comment by szarnekow** [comment]
See also: UniqueClassNameValidator

**Comment by miklossy** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=327863

**Comment by miklossy** [comment]
Fixed in 2.22
