### ISSUE TITLE
Drop support for the old (Xpand-based) Xtext Generator infrastructure

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#1485]
**Xtext 2.9.0** (released on **16.11.2015**) has introduced a [new (Xtend-based) code generator infrastructure](https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2015-11-16-version-2-9-0.md#new-xtext-code-generator).

In favor of this new generator, the [old (Xpand-based) generator](https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2017-01-24-version-2-11-0.md#deprecated-components) has been deprecated since **Xtext 2.11.0** (released on **24.01.2017**).

Removing the deprecated generator from the Xtext code base became necessary, due to the [discussion about Xpand and EPL-2.0](https://github.com/eclipse/xtext/issues/1669).

**Comment by cdietrich** [comment]
also Xpand itself is discontinued and no longer maintained

**Comment by ewillink** [comment]
This breaks OCL and QVTd and .. that use the longstanding generator.

Where is the deprecation announcement?

**Comment by cdietrich** [comment]
E.g.

https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2019/12/03/version-2-20-0

**Comment by cdietrich** [comment]
And https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2017-01-24-version-2-11-0.md

**Comment by ewillink** [comment]
The new infrastructure is not yet useable in Xtext 2.22 since org.eclipse.xtext.xtext.generator.model.GuiceModuleAccess and org.eclipse.xtext.xtext.generator.model.TypeReference are not public API making it impossible to write warning free user fragments.

**Comment by miklossy** [comment]
You are right @ewillink , I also encountered this warnings in [DotGeneratorModule](https://github.com/eclipse/gef/blob/master/org.eclipse.gef.dot.generator/xtext-generator-extensions/org/eclipse/gef/dot/internal/generator/DotGeneratorModule.java) class of the `Eclipse GEF` project.

![screenshot](https://user-images.githubusercontent.com/20393472/84465144-92f6fd00-ac76-11ea-9a43-ed957a8ca631.png)


@cdietrich Can we improve the situation in Xtext 2.23?

**Comment by miklossy** [comment]
As a next step, the old (Xpand-based) generator has been made more optional: https://github.com/eclipse/xtext/issues/2042

**Comment by szarnekow** [comment]
I consider this done since Xpand is no longer mandatory and deleting the deprecated APIs is currently not worth the trouble.
