### ISSUE TITLE
'org.eclipse.xtext.testing' not added to MANIFEST of .ui.tests project

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#149]
regenerating an Xtext language changes the `MyLanguageUIInjectorProvider` to make use of `xtext.testing`. However, that bundle isn't automatically added to the MANIFEST.MF this leading to compile errors.

**Comment by cdietrich** [comment]
@meysholdt are you working on this?

**Comment by meysholdt** [comment]
if you have a minute it would be great it you could take a look

**Comment by cdietrich** [comment]
fixed with https://github.com/eclipse/xtext-core/pull/150
