### ISSUE TITLE
Missing 20* documents on the Xtext website.

### ISSUE THREAD

**Issue by letientai299** [eclipse/xtext-core#15]
Hi XText team , 

Thank you for your amazing work. I notice that the [Document](https://eclipse.org/Xtext/documentation/) page lists only 10* and 30* guide in  [this folder](https://github.com/eclipse/xtext/tree/maintenance/xtext-website/documentation). As a new user, I find those 20* guides  is more useful than the 30* guides.

Could you update the link to those pages? 

I'm not sure is this the right place to report issue for the XText website. If not, please point me to the correct place.

**Comment by svenefftinge** [comment]
The code that is descibed in these chapters lives in a separate repository and we want tohost and maintain the documentation there as well. There will be a link to that documentation however.
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=493370

**Comment by letientai299** [comment]
Thank you for your reply.
