### ISSUE TITLE
Bug in Validator vor Xtext-Grammar-Editor?

### ISSUE THREAD

**Issue by hannesN** [eclipse/xtext-core#1514]
Create a new project and copy the following grammar:

```grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	rules+=TestRule
	;

TestRule:
	TestRule1
	| TestRule2
	| TestRule3
;

fragment TestRule1:
	(value='test')
;
fragment TestRule2:
	(value='test2')
;
fragment TestRule3:
	(value='test3')
;´´´

The validator complains:
There may not be two features named 'value'	

However using only TestRule 1 and 2 is finde and inlining all fragments does not make any problems as well.

**Comment by szarnekow** [comment]
The validation is correct.
By using parser fragments, you introduce supertypes. The type hierarchy for your example is 

`TestRule extends TestRule1, TestRule2, TestRule3` all three TestRule1-3 introduce a feature called 'value' thus `TestRule` inherits it multiple times.

I get the same validation problem with 
```
TestRule:
	TestRule1
	| TestRule2
	//| TestRule3
;

fragment TestRule1:
	(value='test')
;
fragment TestRule2:
	(value='test2')
;
```

If you don't need the types TestRule1-3, you can use wildcard fragments, e.g. `fragment TestRule1 *: value='test1';`

If you still think this being a bug, please provide the grammar snippet for
> using only TestRule 1 and 2 is fine

too
