### ISSUE TITLE
Fix findings from conversion Xtend->Java

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-core#1517]
This will break if the region spans multiple lines. If the endOffset if larger than the document lenght, end should simply point the the last position in the document.

_Originally posted by @szarnekow in https://github.com/eclipse/xtext-core/pull/1507_

**Comment by loradd** [comment]
Hi all, can I work on this bug?

**Comment by szarnekow** [comment]
Sure, please go ahead
