### ISSUE TITLE
Clarify usage of (Import)Scope.getElements(EObject)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#152]
We stumbled over a bogus behaviour of `Scope.getElements(EObject)`.
If we have a Scope that contains two elements with the same name
then `Scope.getElements(EObject)` works for the first element only although the scope (`getAllElements`) actually contains both.

Is this intended behaviour? is this a bug? (the filtering is done at `ImportScope.getLocalElementsByEObject(EObject, URI)`)

Example Grammar:

```
Model: {Model}
    elements+=Element*
    refs+=Ref*
;

Element:
    'element' name=ID
;

Ref:
    "ref" ref=[Element]
;   
```

Test helping to show the problem

```
@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslParsingTest{

    @Inject
    ParseHelper<Model> parseHelper

    @Inject
    IScopeProvider scopeProvider

    @Test 
    def void loadModel() {
        val result = parseHelper.parse('''
            element A
            element A
            element B
            ref A
            ref B
        ''')
        Assert.assertNotNull(result)
        println(result.eResource.errors)
        val scope = scopeProvider.getScope(result, MyDslPackage.Literals.REF__REF)
        println(scope.allElements)
        println("========")
        for (element : result.elements) {
            //FIXME assertEquals(1, scope.getElements(element).size)
            println(scope.getElements(element))
        }
    }

}
```

**Comment by cdietrich** [comment]
p.s. the javadoc of the method says

> Find all descriptions that match the given instance.

but that does not hold true since the result does not contain all matches from "allElements"

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=428913 as well

**Comment by svenefftinge** [comment]
> If we have a Scope that contains two elements with the same name
> then Scope.getElements(EObject) works for the first element only although the scope (getAllElements) actually contains both.

You are asking by object so you only get the description for the given object not all description with the same name as the given object.

**Comment by cdietrich** [comment]
That's not the point you get nothing although the description is there

**Comment by svenefftinge** [comment]
Ah, ok, you meant don't get a description for the second element. 
It should only return those elements that you can later find again by name.

**Comment by cdietrich** [comment]
hmmm getElements(QualifiedName) gives both elements. getSingleElement(QualifiedName) the first one. so refer to the latter one?
then it seems intended.

so i assume this is about using the getElements method in cross reference serializer as stated in the bug mentioned above

**Comment by cdietrich** [comment]
ps: our actual problem is a asymmetric behaviour when refactoring.

```
element a //renaming a to b works
element b //renaming b to a not
ref a
ref b
```

**Comment by spoenemann** [comment]
Is there anything to do here, or can this be closed?

**Comment by cdietrich** [comment]
well at least the behaviour of the refactoring is bogus

**Comment by spoenemann** [comment]
Then please create a new issue for that (in xtext-eclipse?) describing how to reproduce the problem and close this one.

**Comment by cdietrich** [comment]
moved to https://github.com/eclipse/xtext/issues/2403
