### ISSUE TITLE
Version recognition does not work

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#154]
I tested the wizard as installed from the Jenkins update sites. The resulting build.gradle did not contain the correct version `2.11.0-SNAPSHOT`, but just `unknown`.

**Comment by cdietrich** [comment]
java.util.MissingResourceException: Missing properties: org/eclipse/xtext/util/plugin.properties

**Comment by cdietrich** [comment]
@spoenemann where the plugin.properties bulk deleted?
