### ISSUE TITLE
support configuring the entry parser rule on XtextResource

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#16]
Currently, XtextResource always parses documents starting with the first parser rule from the grammar. It would be nice if it could be configured what entry parser rule should be used. Downstream services, such as content assist, can obtain from the ParseResult which parser rule had been used. 

Use cases:
 - register one Xtext-Language (i.e. Grammar) for multiple file extensions and define a specific entry parser rule for each of them. This effectively allows to define multiple languages while only having one grammar. In some cases, this is more lightweight than using multiple grammars + grammar inheritance.
 - Invoke the Xtext EmbeddedEditor on a partial document. Currently, this can only be done by providing the full document and specifying a (small) visible range on this document. This causes the EmbeddedEditor to parse the full document which can be a performance issue when having large documents with many small EmbeddedEditor-Viewpoints. However, this github issue does not address the question how incomplete (because they're subtrees) ASTs should be handled.

**Comment by meysholdt** [comment]
see also https://bugs.eclipse.org/bugs/show_bug.cgi?id=403940

**Comment by meysholdt** [comment]
fixed

**Comment by cdietrich** [comment]
@meysholdt any plans to make this configurable in parsehelper?
