### ISSUE TITLE
Inconsistent naming of generated Eclipse plugin activator

### ISSUE THREAD

**Issue by king-tyler** [eclipse/xtext-core#1605]
When the Eclipse plugin project is not conventionally named, the package and name of the Xtext-generated activator class is inconsistent with the rest of the Xtext-generated classes.

Example:

Given the grammar `org.xtext.example.mydsl.MyDsl`, the conventional name of eclipse plugin project is `org.xtext.example.mydsl.ui`. If the project is unconventionally named to `example.mydsl.ui`, Xtext generates `example.mydsl.ui.internal.MydslActivator`, whereas every other Xtext-generated class in the project has the base package of `org.xtext.example.mydsl`. Furthermore, every other Xtext-generated class uses `MyDsl` instead of `Mydsl` in their class names.

See https://github.com/eclipse/xtext-core/blob/f90954624825a55e1232e1a3dd2397710f6d528b/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorNaming.java#L126-L135

**Comment by cdietrich** [comment]
i have doubts this is fixable without breaking existing clients.

**Comment by kthoms** [comment]
For your project you should be able to override XtextGeneratorNaming by your own implementation.
```
/**
 * Configuration of the names of the generated classes. Create a subclass and
 * register it with a specialized {@link DefaultGeneratorModule} in order to
 * customize some class or package names.
 */
```

As Christian points out if we would change this in the general implementation, all clients would experience surprises on their next update. We generally avoid to break clients if ever possible. So if you agree I tend to close this as WONTFIX.

**Comment by king-tyler** [comment]
That works for me. Thanks
