### ISSUE TITLE
Cleanup Xtext formatter (Java)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1625]
Findings from formatting grammar accesses

https://github.com/eclipse/xtext-eclipse/pull/1586
https://github.com/eclipse/xtext-core/pull/1616
https://github.com/eclipse/xtext-extras/pull/665
https://github.com/eclipse/xtext-xtend/pull/1140
https://github.com/eclipse/xtext-web/pull/272

https://github.com/eclipse/xtext-core/pull/1624/files#r527848735

https://github.com/eclipse/xtext-xtend/pull/1140/files#r528538843

https://github.com/eclipse/xtext-core/pull/1616/files#r528535270

extra spaces: https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524969980

https://github.com/eclipse/xtext-web/pull/272/files#r524985690

https://github.com/eclipse/xtext-extras/pull/665#discussion_r528543795

https://github.com/eclipse/xtext-extras/pull/665#discussion_r528544302

https://github.com/eclipse/xtext-extras/pull/665#discussion_r528544070

to be discussed: https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524971356

serializer bug ?!?: return keyword is missing https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524965534

**Comment by szarnekow** [comment]
Findings from xtext-extras that we need to look at:
https://github.com/eclipse/xtext-extras/pull/665/files#r525025543
https://github.com/eclipse/xtext-extras/pull/665/files#r528554752
https://github.com/eclipse/xtext-extras/pull/665/files#r528555084
https://github.com/eclipse/xtext-extras/pull/665/files#r528556142
https://github.com/eclipse/xtext-extras/pull/665/files#r528557245
https://github.com/eclipse/xtext-extras/pull/665/files#r528558082

**Comment by szarnekow** [comment]
Findings from xtext-eclipse that we need to look at:
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r528546666
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524969813
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524969980
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524971356
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r524972856
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r528546666
https://github.com/eclipse/xtext-eclipse/pull/1586/files#r528547068

**Comment by szarnekow** [comment]
Findings from xtext-xtend that we need to look at:
https://github.com/eclipse/xtext-xtend/pull/1140/files#r528566579
https://github.com/eclipse/xtext-xtend/pull/1140/files#r528576430

**Comment by szarnekow** [comment]
More findings:
- [ ] https://github.com/eclipse/xtext-xtend/pull/1157/files#r537318502
- [ ] https://github.com/eclipse/xtext-eclipse/pull/1607/files#r537319280
- [ ] https://github.com/eclipse/xtext-eclipse/pull/1607/files#r537323910
- [ ] https://github.com/eclipse/xtext-eclipse/pull/1607/files#r537324912

**Comment by cdietrich** [comment]
wonder what is left over here

**Comment by ArneDeutsch** [comment]
I would say we are done here. If no one disagree I would close this ticket.
