### ISSUE TITLE
[LS] Signature helper does not propose parameter hints when no-arguments are used on use-side but required according to definition-side

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#165]
This issue only applies to the test language.

Let assume the below DSL and ```<|>``` is the current location of the offset:
```
type A { op foo(a: A) { } } type Main { op main() { foo(<|>) } }
```

Then the signature helper should propose ```a: A``` but it does not.

Besides that, it would be great to rename the ```SignatureHelpService``` service interface to ```ISignatureHelpService``` to comply with the naming convention used overall in the Xtext project.

**Comment by kittaakos** [comment]
I will take care of this issue.

**Comment by kittaakos** [comment]
PR is available at [here].

[here]: https://github.com/eclipse/xtext-core/pull/166

**Comment by cdietrich** [comment]
seems to be fixed now
