### ISSUE TITLE
Typo for ANTLR Option k

### ISSUE THREAD

**Issue by Scholvac** [eclipse/xtext-core#1655]
Hi, 
there seems to be a small issue with the generation of ANTLR lookahead options. 

if the field k in generator options is > 0 (let's say 3), the code in: 
[AbstractAntlrGrammarGenerator](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend) line 118 will generate 
```
options {
    memoize=3
}
```
instead of: 
```
options {
    k = 3
}
```

**Comment by kthoms** [comment]
Looks for me indeed like a bug. Could you try to provide a patch for it? 

It should
- Fix the code in AbstractAntlrGrammarGenerator.xtend
- Also in AbstractAntlrGrammarGenerator.java
- Use the option in one of the test languages (project org.eclipse.xtext.testlanguages)
- Adjust generator expectation of the modified test language

**Comment by cdietrich** [comment]
@szarnekow before we start doing work here. can you please comment here

**Comment by szarnekow** [comment]
It is a bug that was introduced when the fragments have been rewritten

**Comment by szarnekow** [comment]
I tried to find the review for this but didn't manage to dig that out - only saw the commit from 2015

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/pull/676

**Comment by cdietrich** [comment]
Fixed in 2.25.0(.M2)
