### ISSUE TITLE
Hidden spaces not fully hidden from datatype rules

### ISSUE THREAD

**Issue by dpetroff** [eclipse/xtext-core#1659]
Any hidden white space present when parsing using a datatype rule seems to be trimmed to a single space instead of zero spaces:

    grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

    generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

    Model:
    	qualifiedNames+=QualifiedName*;
	
    QualifiedName:
    	ID'.'ID;
parses

    some.name
    another . name
    something                .     else
    and
    .
    this
as `[some.name, another . name, something . else, and . this]`. Note the single spaces surrounding the full stop in the latter three. 
If I used the rule for cross-references, any spaces or line breaks around the full stop would break the linking, and it crops up if I wanted to have floating point numbers with hidden white space around the full stop as well.

I can work around the issue with value converters in most cases but I really don't think it makes sense that I have to.

**Comment by szarnekow** [comment]
This works as designed and a ValueConverter is the correct approach to convert the text to a semantic value.

The problem cannot be easily generalized, e.g. a DT rule of the shape
```
SomeDT: ID ID;
```
with the input `a b` would yield the value `ab` if all hidden tokens would be completely removed in all cases. Obviously this would conflict with a regular terminal ID.

Binding the QualifiedNameValueConverter is what needs to be done for your case.
