### ISSUE TITLE
Accessing Standalone Index in O(n) instead of O(1)

### ISSUE THREAD

**Issue by kjuenemann** [eclipse/xtext-core#1683]
Hi,

I was under the impression that searching an item in the index (meaning an IResourceDescriptions instance) would be in O(1), if the fully qualified name is given. Under Eclipse, this seems to work fine.

However under Standalone, the access seems to be in O(n) (where n is the number of resources within the resourceSet). Am I doing something wrong or is this working as intended?

More details:
1. as index the class `ResourceSetBasedResourceDescriptions` is used.
2. the access is in O(n), because `ResourceSetBasedResourceDescriptions.getExportedObjects(EClass, QualifiedName, boolean)`  indirectly calls `ResourceSetBasedResourceDescriptions.getSelectables()` which then calls `ResourceSetBasedResourceDescriptions.getAllResourceDescriptions()` which iterates over all resources in order to create ResourceDescriptions. Details are listed below.
3. I call the index by making use of containers, in order to deal with classpath issues: 

```
	private def getVisibleEObjectDescriptionsByName(Resource r, EClass type, QualifiedName fqn) {
		val tmp = r.getVisibleContainers.flatMap [ c |
			c.getExportedObjects(type, fqn, false)
		]
		return tmp
	}
```

Listings for Point 2:
```
	@Override
	public Iterable<IEObjectDescription> getExportedObjects(EClass type, QualifiedName qualifiedName, boolean ignoreCase) {
		if (data != null) {
			return data.getExportedObjects(type, qualifiedName, ignoreCase);
		}
		return super.getExportedObjects(type, qualifiedName, ignoreCase);
	}
```

```
	@Override
	protected Iterable<? extends ISelectable> getSelectables() {
		return getAllResourceDescriptions();
	}
```

**Comment by cdietrich** [comment]
do you make use of resourcedescriptiondata as e.g. standalonebuilder does?

**Comment by kjuenemann** [comment]
> btw do you have resourcedescriptiondata installed?
> e.g. as org.eclipse.xtext.builder.standalone.StandaloneBuilder does?

I don't think so, as I don't know what that is. I guess the serialization of the index? The data-property was null while debugging, so I don't think so.
I did not even reference to the builder-plugin. I will look into the StandaloneBuilder.

FYI: I am on XText 2.16, so things might have changed already.

**Comment by cdietrich** [comment]
how do you use/build Xtext standalone?

**Comment by kjuenemann** [comment]
Well, now that I had a look into StandaloneBuilder, I do something very similar. I basically implemented it on my own (cause I did not know it existed). 

I basically create a new ResourceSet, then load files into it (by calling `rset.getResource(uri, true)`) and then call `IResourceValidator.validate(res, ALL, ...)` for all resources within the resourceSet. The IResourceValidator is injected, of course.

Does that answer your question?

**Comment by cdietrich** [comment]
can you then try to create a resourcedescription data, 
init it as
org.eclipse.xtext.builder.standalone.StandaloneBuilder.fillIndex(URI, Resource, ResourceDescriptionsData)
does.

and install it as adapter to the resourceset asorg.eclipse.xtext.builder.standalone.StandaloneBuilder.installIndex(XtextResourceSet, ResourceDescriptionsData) does

**Comment by kjuenemann** [comment]
OK, I will try that and come back here next week - I need some time to work this into my own code.

But I see that one has to / should initialize the index oneself in standalone, I did not know that. This will most likely be my issue. But I will tell you next week, if the issue persists. :-)

**Comment by kjuenemann** [comment]
Hi Christian,
the solution you proposed was exactly what I needed. To be clear, filling and installing the index as you described [here](https://github.com/eclipse/xtext-core/issues/1683#issuecomment-786740248) solved the issue. 

Thanks for that! 

On a side note: is it documented anywhere that you need to initialize / "install" the index manually in standalone? I read the book and documentation, but I don't recall reading about this. Might be my oversight, though. 

Still, much thanks for your very helpfull and quick support!

**Comment by kjuenemann** [comment]
Problem was solved by Christian.
