### ISSUE TITLE
[StandaloneSetup] Unnecessary trailing whitespaces

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#169]
The mwe2 workflow generates unnecessary trailing whitespaces into the <MyDsl>StandaloneSetup.java file.

![standalonesetup_trailing_white_spaces](https://cloud.githubusercontent.com/assets/20393472/20090635/ad1a616a-a58e-11e6-8fbc-402ff9376607.png)

xtext-core/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend

**Comment by cdietrich** [comment]
Fixed in Xtext 2.11
