### ISSUE TITLE
Serializer takes "forever"

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#17]
the serializer seem to take forever in 2.9+

using https://github.com/sculptor/sculptor/tree/develop/sculptor-eclipse with //github.com/vladdu/xtext.unittesting

and running SculptordslValidatorITest

it performs much better when using 

```
import org.eclipse.xtext.util.formallang.Cfg;
import org.eclipse.xtext.util.formallang.FollowerFunction;
import org.eclipse.xtext.util.formallang.FollowerFunctionImpl;
import org.eclipse.xtext.util.formallang.FollowerFunctionImpl.UnorderedStrategy;
import org.eclipse.xtext.util.formallang.Pda;
import org.eclipse.xtext.util.formallang.PdaFactory;
import org.eclipse.xtext.util.formallang.PdaUtil;

@SuppressWarnings("restriction")
public class MyDslPDAUtil extends PdaUtil {

    @Override
    public <S, P, E, T, D extends Pda<S, P>> D create(Cfg<E, T> cfg, FollowerFunction<E> ff,
            PdaFactory<D, S, P, ? super E> fact) {
        ((FollowerFunctionImpl<E, T>)ff).setUnorderedStrategy(UnorderedStrategy.SEQUENCE);
        return super.create(cfg, ff, fact);
    }

}
```

and

```
    public Class<? extends PdaUtil> bindPdaUtil() {
        return MyDslPDAUtil.class;
    }
```

**Comment by spoenemann** [comment]
@meysholdt you planned to work on this, right?

**Comment by cdietrich** [comment]
@meysholdt i had a look with 2.11 and the performance seems much better with 2.11. same for memory consumption

**Comment by kthoms** [comment]
@meysholdt Is this also related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=484465 and https://github.com/eclipse/xtext-core/commit/e8682fbfd30afa9f871250dd3df1774a4c62081a ?
Could this one be closed now?

**Comment by meysholdt** [comment]
from my side, this can be closed. @cdietrich, do you agree that the problem for which you filed this issue has been resolved?

**Comment by cdietrich** [comment]
yes looks good now
