### ISSUE TITLE
[Formatter2] Typo in the AbstractEObjectRegion class

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#170]
The AbstractEObjectRegion class contains the following typo: semantcElement
![typo_semantcelement](https://cloud.githubusercontent.com/assets/20393472/20090675/e63caf70-a58e-11e6-8da0-cc0956f3a7af.png)
xtext-core/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractEObjectRegion.java

**Comment by cdietrich** [comment]
fixed in xtext 2.11
