### ISSUE TITLE
org.eclipse.xtext.preferences is not api, but testing api uses it

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1703]
org.eclipse.xtext.preferences (e.g. MapBasedPreferenceValues) is not api (it is provisional), but testing api uses it

is there anything that speaks against making it api?

**Comment by kthoms** [comment]
What is the purpose of making it API? Which kind of clients would need to access these classes?

The only classes I would consider to possibly be API are `IPreferenceValues`, `IPreferenceValuesProvider` and `PreferenceKey`.

How about moving the others to an internal package. However, we would risk that clients break which are using those restricted classes on purpose.

**Comment by cdietrich** [comment]
see org.eclipse.xtext.testing.formatter.FormatterTestRequest.preferences(Procedure1<MapBasedPreferenceValues>)

**Comment by kthoms** [comment]
Yes, quite unfortunate. The method is no good, but why exposing the dirt even more?
The method getOrCreateMapBasedPreferences might get deprecated and another one provided that expose only the interface ITypedPreferences. The clients could assume to cast if really needed. I doubt there are some that really rely on having MapBasedPreferenceValues.

**Comment by cdietrich** [comment]
all tests that use it do and would break

**Comment by szarnekow** [comment]
>  I doubt there are some that really rely on having MapBasedPreferenceValues.

Quite the contrary. MapBasedPreferenceValues is the only API that allows to *set* preferences in the runtime case.

**Comment by szarnekow** [comment]
> What is the purpose of making it API? Which kind of clients would need to access these classes?

Putting it the other way round: Why keeping this internal? There haven't been any changes in ages.

**Comment by kthoms** [comment]
I have raised the questions that came in my mind, but if you feel comfortable with exposing this, then I don't care much. Please decide.

**Comment by cdietrich** [comment]
done
