### ISSUE TITLE
[LanguageServer] Init Request from VS Code no longer working

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#171]
The init request from VSCode is no longer working cause it is canceled in RequestManager.runWrite

java.util.concurrent.CancellationException: process canceled

**Comment by cdietrich** [comment]
it looks like textDocument/didOpen kills initialize

**Comment by svenefftinge** [comment]
Yes, it was much more. I will look into it. Thanks

**Comment by svenefftinge** [comment]
We have a default cancellation strategy in place, that cancels all read requests on write. I will disable that for now, as it seems to be too generic and erorprone

**Comment by cdietrich** [comment]
looks good. thx 👍
