### ISSUE TITLE
Deal with MergeableManifest/ManifestMergerTest on J16/J17

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1744]
MergeableManifest/ManifestMergerTest does no longer with with J16/J17
We have Marked it as Deprecated/forRemoval but have not delivered that yet.

My proposals are
- Delete the test and remove with the release after the current
- Detect Java version in test and skip
- Immediately delete everything

what do you think?

**Comment by LorenzoBettini** [comment]
I think it depends on how long it has been deprecated. If it was deprecated a long time ago I'd go for the third solution, otherwise, I'd go with one of the two first solutions...

**Comment by cdietrich** [comment]
fixed in 2.26
