### ISSUE TITLE
Semantic quickfix for generic IDEs: Command interface

### ISSUE THREAD

**Issue by imhotep82** [eclipse/xtext-core#1753]
Step backwards: What do you think about keeping the logic as is in this PR and discuss a potential change of the design in a subsequent, isolated ticket / pull request? @cdietrich @imhotep82

_Originally posted by @szarnekow in https://github.com/eclipse/xtext-core/issues/1597#issuecomment-718175071_

**Comment by szarnekow** [comment]
Unfortunately, no discussion happened. Please open a ticket in https://github.com/eclipse/xtext if you want to pick this up.
