### ISSUE TITLE
getURIFragmentRootSegment in DerivedStateAwareResource returns 0 instead of empty string for single root resources as expected by the contract

### ISSUE THREAD

**Issue by ghaith** [eclipse/xtext-core#176]
The documentation of Resource.getURIFragmentRootSegment implies that it would return an empty string if the root object is the only one in that resource
> Returns the URI fragment root segment for reaching the given direct content object. This default implementation returns the position of the object, if there is more than one object, otherwise, the empty string. As a result, the URI fragment for a single root object will be "/".

The current implementation will return a 0 instead resulting in URI fragments "/0":
```    
if (unloadingContents == null) {
	IParseResult parseResult = getParseResult();
	if (parseResult != null && eObject == parseResult.getRootASTElement()) {
            return "0"; 
    	}
}
```

**Comment by svenefftinge** [comment]
The documentation talks about the default implementation, it is not mandatory to implement it like that. Returning 0 even if it is the single element is more stable as the fragment doesn't change, once you add another element. Also there are many persisted EMF files out there with references to Xtext models, so changing this will break all of them.
