### ISSUE TITLE
Overriding DocumentSymbolMapper fails

### ISSUE THREAD

**Issue by nmaaiken** [eclipse/xtext-core#1779]
I have a problem with the xtext language server that provides language support via LSP:

I am trying to override the `DocumentSymbolMapper` class from org.eclipse.xtext.ide.server.symbol to accommodate more logic on how a `DocumentSymbol` is construed, so that the Outline-View provided to VS Code via LSP supports different Symbolkinds and does not display the whole qualified name of a symbol.
I have a custom class, that extends `DocumentSymbolMapper`:

```
@Singleton
@SuppressWarnings("all")
public class FrancaDocumentSymbolMapper extends DocumentSymbolMapper
```
It also includes overriding static nested classes DocumentSymbolKindProvider and DocumentSymbolNameProvider.

It is provided to the Guice Injector via a `@Provides` annotated method in Singleton scope:

```
@Singleton
    @Provides
    public DocumentSymbolMapper provideDocumentSymbolMapper() { return new FrancaDocumentSymbolMapper(); }
```

My problem is, that when Guice is first constructing the language server, the binding for `DocumentSymbolMapper` is correct. However, when instantiating `HierarchicalDocumentSymbolService`, which holds the dependency to `DocumentSymbolMapper`, Guice seemingly uses a different injector without reference to any previous custom bindings. Therefore, the default implementation is injected and not the custom one.

Is there any option on how to get around that?

**Comment by cdietrich** [comment]
maybe you can simply add a ususal bind method

```
public Class<? extends DocumentSymbolMapper> bindDocumentSymbolMapper() {
    return FrancaDocumentSymbolMapper.class;
}

**Comment by nmaaiken** [comment]
Unfortunately, that doesnt work either. I have also tried 
```
bind(DocumentSymbolMapper.class).to(FrancaDocumentSymbolMapper.class)
```
which also did not work.
To me it seems, that this part of the application is constructed by a different injector, but i might also be on the wrong path there...

**Comment by cdietrich** [comment]
where do you bind.
the stuff should be done in language specific injector?!?

**Comment by nmaaiken** [comment]
We use a ServerModule for the bindings, from which we later obtain the injector and instantiate the server.

```
Injector injector = Guice.createInjector(new ServerModule());
LanguageServerImpl languageServer = injector.getInstance(LanguageServerImpl.class);
```

We followed this example: [https://github.com/itemis/xtext-languageserver-example](https://github.com/itemis/xtext-languageserver-example)

**Comment by cdietrich** [comment]
yes but all methods in LanguageServerImpl should use IResourceServiceProvider to obtain a language specific service.
so i wonder which place does not.

**Comment by nmaaiken** [comment]
Oh i see, what you mean. In this case, the language server does not use a language specific service (presumably by default), if you refer to the method `getIDocumentSymbolService()` you will find this (not edited by us):

```
	protected IDocumentSymbolService getIDocumentSymbolService(IResourceServiceProvider serviceProvider) {
		if (serviceProvider == null) {
			return null;
		}
		if (isHierarchicalDocumentSymbolSupport()) {
			return serviceProvider.get(HierarchicalDocumentSymbolService.class);
		} else {
			return serviceProvider.get(DocumentSymbolService.class);
		}
	}
```

**Comment by cdietrich** [comment]
yes. but the serviceProvider is per language and all obtainings of the services should go through it, and also seem to be with the quick scan i did. so binding in IdeModule of the lang should work.

**Comment by nmaaiken** [comment]
Alright, we'll look into that! Thank you for the help!

**Comment by nmaaiken** [comment]
The fix worked, thanks a lot. I'll close here.
