### ISSUE TITLE
xtext.qn.interning should be evaluated later

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-core#1787]
Xtext provides the system property `xtext.qn.interning` for interning the Strings used in `org.eclipse.xtext.naming.QualifiedName`.

Unfortunately this property is evaluated when the class is loaded as it's a static final constant.

The only way how to set this property is using a -D JVM parameter. I would like to use System.setProperty or I would like to be able to configure it by any other way like binding some other implementation.

We ship our application with an Xtext interpreter and we have some communication efforts and error sources, if the application's operators have to pass the JVM property externally.

**Comment by cdietrich** [comment]
am not sure if it would be a good idea to call System.getProperty a gazillion of times.

**Comment by OLibutzki** [comment]
Maybe my use case is limited, but initialization on first usage would help, too.

**Comment by OLibutzki** [comment]
Any further ideas how to solve this?

**Comment by cdietrich** [comment]
still waiting for feedback from @szarnekow

**Comment by szarnekow** [comment]
> but initialization on first usage would help, too.

Are you sure? This is required extremely early in the lifecycle, e.g. basically together with the Injector instantiation. 

What we could do is making the boolean field writable. I wouldn't make it volatile, though.

Did you experiment with enabling interning? What was the net-benefit?

**Comment by OLibutzki** [comment]
> Are you sure? This is required extremely early in the lifecycle, e.g. basically together with the Injector instantiation.

Well, in a standalone scenario its up to the developer when to initialize the language. Before I run the StandaloneSetup I could set the system property. I did not try it, but I'm quite sure that it should work. 

> Did you experiment with enabling interning? What was the net-benefit?

I'd like to share some numbers after I read our model and resolved **all** proxies.

The node model takes about 168 MB.
The (index, semantic model,...) takes about 225 MB.

Just by interning the strings in the QualifiedNames we have been able to reduce this to 
168 MB (no changes) and 166 MB (-59 MB).

For sure this is highly related to the DSL design, but we have a lot of elements with qualified names having a lot of equal segments in the index.

**Comment by szarnekow** [comment]
> Before I run the StandaloneSetup I could set the system property.

Can you give this a try?

**Comment by OLibutzki** [comment]
> Can you give this a try?

I have done so, I set a breakpoint in `org.eclipse.xtext.naming.QualifiedName.intern(String)`. The method is called for the first time as part of the injector creation (exactly as you assumed).

Here is the (truncated) stack:
```
Thread [main] (Suspended (breakpoint at line 142 in QualifiedName))	
	owns: Class<T> (com.google.inject.internal.InternalInjectorCreator) (id=132)	
	QualifiedName.intern(String) line: 142	
	QualifiedName.create(String...) line: 125	
	Conventions.<clinit>() line: 42	
	VarianteFestlegungZuordnungen.<init>() line: 49	
	NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
	NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
	DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
	Constructor<T>.newInstance(Object...) line: 423	
	DefaultConstructionProxyFactory$1.newInstance(Object...) line: 85	
	ConstructorInjector<T>.construct(Errors, InternalContext, Class<?>, boolean) line: 85	
	ConstructorBindingImpl$Factory<T>.get(Errors, InternalContext, Dependency<?>, boolean) line: 254	
	SingleFieldInjector.inject(Errors, InternalContext, Object) line: 53	
	MembersInjectorImpl<T>.injectMembers(T, Errors, InternalContext, boolean) line: 110	
	ConstructorInjector<T>.construct(Errors, InternalContext, Class<?>, boolean) line: 94	
	ConstructorBindingImpl$Factory<T>.get(Errors, InternalContext, Dependency<?>, boolean) line: 254	
	ProviderToInternalFactoryAdapter$1.call(InternalContext) line: 46	
	InjectorImpl.callInContext(ContextualCallable<T>) line: 1031	
	ProviderToInternalFactoryAdapter<T>.get() line: 40	
	Scopes$1$1.get() line: 65	
	InternalFactoryToProviderAdapter<T>.get(Errors, InternalContext, Dependency<?>, boolean) line: 40	
	InternalInjectorCreator$1.call(InternalContext) line: 204	
	InternalInjectorCreator$1.call(InternalContext) line: 198	
	InjectorImpl.callInContext(ContextualCallable<T>) line: 1024	
	InternalInjectorCreator.loadEagerSingletons(InjectorImpl, Stage, Errors) line: 198	
	InternalInjectorCreator.injectDynamically() line: 179	
	InternalInjectorCreator.build() line: 109	
	Guice.createInjector(Stage, Iterable<Module>) line: 95	
	Guice.createInjector(Iterable<Module>) line: 72	
	Guice.createInjector(Module...) line: 62	
	LFISpecStandaloneSetup(LFISpecStandaloneSetupGenerated).createInjector() line: 27	
	LFISpecStandaloneSetup(LFISpecStandaloneSetupGenerated).createInjectorAndDoEMFRegistration() line: 21	
	LFISpecStandaloneSetup.xtend line: 16	
	[...]
```

I could set the system property in _LFISpecStandaloneSetup_ just before `new LFISpecStandaloneSetup().createInjectorAndDoEMFRegistration()` is called in order to enable string interning in the standaline context.

**Comment by OLibutzki** [comment]
Ah, wait! In the test scenario it works to set the property in _LFISpecStandaloneSetup_ as the _QualifiedName_ class is not loaded yet...

I guess you are right: Doing this lazily might not be sufficient.

In the Conventions class you can find in the stack we have such a constant:
`public static final QualifiedName MY_NAME = QualifiedName.create( "MyName" );`

If `Conventions` would have been loaded earlier, `QualifiedName` would have been initialized earlier...

**Comment by OLibutzki** [comment]
> What we could do is making the boolean field writable. I wouldn't make it volatile, though.

Making the field writable should do the trick. Maybe some Strings which are used before setting the property might not benefit, but I'm sure that this will happen rarely. The majority of created qualified names are those that are put into the index and are used for scoping.

**Comment by cdietrich** [comment]
Made field non final. Fixed in 2.26

**Comment by OLibutzki** [comment]
Thanks!

Why don't you add a public setter or make the field public?

**Comment by cdietrich** [comment]
how about providing a PR?

**Comment by OLibutzki** [comment]
Done: #1803
