### ISSUE TITLE
Update to LSP4J 0.13.0 / LSP 3.17.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1793]

**Comment by cdietrich** [comment]
TODO: Change Workspace Symbol Service to use WorkspaceSymbols instead of Symbol information

**Comment by cdietrich** [comment]
timeline for protocol 3.17 unclear

**Comment by cdietrich** [comment]
complete changelog
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#version_3_17_0

**Comment by cdietrich** [comment]
@rubenporras can you do some contributions here?

**Comment by rubenporras** [comment]
Hi @cdietrich , we are still busy making our customization of the Xtext Language Server work as we need and then moving our DSL customization to the new API. By looking at the list I have not seen any new feature that we would need for the time being, so our contributions will still focus on ironing out existing features, in case we face some problem.
For later I could image the new diagnostic capabilities or the handling of stale request would useful, but at the moment I cannot tell.

**Comment by cdietrich** [comment]
Fine I will just fix the compile errors myself and will see if one of us finds time to work on deprecations and new features

**Comment by cdietrich** [comment]
created https://github.com/eclipse/xtext/issues/2438 for the cleanup

**Comment by cdietrich** [comment]
@rubenporras @tivervac @szarnekow if have updated to lsp4j 0.13.0
and the new version should be available with the latest nightly
i did not address the deprecations yet
non the less it would be nice if you could test with your usecases
thanks

**Comment by rubenporras** [comment]
I will be on holidays until the 1st of june, but then I will test it.

**Comment by cdietrich** [comment]
ok, this will be too late anyway
