### ISSUE TITLE
Suspicious code in HiddenRegionFormatting's mergeValuesFrom

### ISSUE THREAD

**Issue by LawrenceGoossens** [eclipse/xtext-core#1798]
The `mergeValuesFrom` method never updates the priority of `this`. This could cause especially weird results in `HiddenRegionFormattingMerger`'s merge method, where the resulting priority could depend on the number of conflicts, and the priority of 3 or more merged conflicts will always be 0. I think fixing this would also fix the `// TODO: don't do this` in `HiddenRegionFormattingMerger`.

**Comment by LawrenceGoossens** [comment]
The way `strategy` is calculated can also generate overflows if high priority values are used.

**Comment by LawrenceGoossens** [comment]
I made a pull request with a fix.

**Comment by cdietrich** [comment]
@szarnekow @LawrenceGoossens anything left?

**Comment by szarnekow** [comment]
I don't think so. Should be fine now. Closing. @LawrenceGoossens Please reopen if something is missing.

**Comment by cdietrich** [comment]
fix causes https://github.com/eclipse/xtext/issues/2462
