### ISSUE TITLE
DslFormatter as a cli call

### ISSUE THREAD

**Issue by r4mtor** [eclipse/xtext-core#1813]
Is there a way to use the formatter as a standalone formatter for the command line.

When I generate the stubs, eclipse behaves with the formatting as I want 
```
formatter = {
generateStub = true
}
```
But for my CI integration it would be good if I could call the same formatting via commandline.
```
formatter = {
generateJavaMain = true
}
```
like `clang` versus `clang-format`

Maybe there are some tips what I can do.

**Comment by cdietrich** [comment]
you need to write a java main that calls the formatter yourself

**Comment by r4mtor** [comment]
That's what I did, however I use the `generatorJavaMain` and injected the formatter in the main

**Comment by cdietrich** [comment]
why do you want to?

**Comment by r4mtor** [comment]
I used the LSP that works for me. Thanks for your replies.
