### ISSUE TITLE
[generator] Unnecessary trailing whitespaces in plugin.xml_gen

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#183]
The mwe2 workflow generates unnecessary trailing whitespaces into the plugin.xml_gen file.

![plugin_xml_gen_trailing_whitespace](https://cloud.githubusercontent.com/assets/20393472/20661214/e7dcdf20-b54d-11e6-8a99-56324c57f2d3.png)

xtext-core/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend

**Comment by dhuebner** [comment]
@miklossy Would you like to prepare a PR with a fix?

**Comment by spoenemann** [comment]
https://github.com/eclipse/xtext-core/blob/4de451dd36a0616301ecac8273824da7de0dd01b/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend#L133

**Comment by kthoms** [comment]
fixed in 2.11 4b5bcc1d6fb9cee7ff5b0aa04e4e575243a3d04c
