### ISSUE TITLE
MWE Workflow generates an invalid method in AbstractSyntacticSequencer when using unordered groups

### ISSUE THREAD

**Issue by lukasf98** [eclipse/xtext-core#1848]
When a grammar is large enough (e.g. by using unordered groups), the MWE Workflow generates an init method in AbstractSyntacticSequencer  larger than the maximum allowed size for java (>64kb).

The error reads:
`The code of method init(IGrammarAccess) is exceeding the 65535 bytes limit. `

**Comment by cdietrich** [comment]
Fixed in 2.27
