### ISSUE TITLE
[LanguageServer] Define a way for code lens resolution with the Xtext Language Server

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#185]
According to the [LSP specification]; for performance reasons the creation of the code lenses and their resolution should be done in two separate stages.

The creation process is pretty straightforward. The `CodeLensParams` has a `TextDocumentIdentifier` property which can be used to get the URI of the text document and on the server-side the proper language specific implementation could be dispatched with this URI.

The resolution phase is a bit more complicated because only the already created `CodeLens` is available on the server-side which does not know anything about the underlying text document. Hence the language specific service cannot be dispatched without the URI.

A possible solution could be to use the `data` field of the `CodeLens` to store the URI of the text document when the code lenses are instantiated. With this additional URI information,  the language specific service can be discovered and dispatched during the resolution phase.

This task should be used to define a way how to handle the code lens resolution with the Xtext Language Server.

[LSP specification]: https://github.com/Microsoft/language-server-protocol

**Comment by spoenemann** [comment]
A possible solution: change the current Xtext LanguageServerImpl to support exactly one language and move the dispatching mechanism to a higher level.

**Comment by kittaakos** [comment]
This was done via 139d01f7036f94c1aec5fa01dc25c8cb698becb6, right? @svenefftinge, could you please glance into your commit and update this ticket according to it? Thanks!

**Comment by svenefftinge** [comment]
Yes, indeed got solved with that commit.
