### ISSUE TITLE
Codehaus workaround and new maven versions dont see to like each other with exec-maven-plugin and tycho

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1851]
Codehaus workaround and new maven versions dont see to like each other with exec-maven-plugin and tycho

```
11:10:35  [DEBUG] Using mirror maven-default-http-blocker (http://0.0.0.0/) for codehaus-snapshots (http://nexus.codehaus.org/snapshots/).
...
11:11:55  [WARNING] Could not transfer metadata org.antlr:antlr-runtime/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/org/antlr/antlr-runtime/maven-metadata.xml
11:11:55  org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata org.antlr:antlr-runtime/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/org/antlr/antlr-runtime/maven-metadata.xml
```

is the codehaus workaround still needed?

**Comment by cdietrich** [comment]
was introduced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=481478

**Comment by cdietrich** [comment]
if i remove i still get
```
11:22:01  [DEBUG] Writing tracking file /home/jenkins/.m2/repository/org/codehaus/codehaus-parent/4/_remote.repositories
11:22:01  [DEBUG] Writing tracking file /home/jenkins/.m2/repository/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom.lastUpdated
11:22:01  [DEBUG] Using mirror maven-default-http-blocker (http://0.0.0.0/) for codehaus-snapshots (http://nexus.codehaus.org/snapshots/)
```

**Comment by cdietrich** [comment]
these also seems to be a diff between debug and non debug log

**Comment by cdietrich** [comment]
```
11:52:50  [INFO] --- exec-maven-plugin:3.0.0:java (mwe2Launcher) @ org.xtext.example.mydsl ---
11:52:50  [WARNING] Could not transfer metadata org.antlr:antlr-runtime/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/org/antlr/antlr-runtime/maven-metadata.xml
```
have no idea why this comes not in non tycho

**Comment by LorenzoBettini** [comment]
@cdietrich I'm not sure I understand your last comment.

Anyway, I struggled with this in the past, before http was banned. I tracked down the problem to the antlr generator. I solved this by disabling a few other repositories, see the last part of the POM https://github.com/LorenzoBettini/xtext-build-utils/blob/master/xtext-maven-parent/io.github.lorenzobettini.xtextutils.xtext-maven-parent/pom.xml

**Comment by cdietrich** [comment]
@LorenzoBettini  the problem is that we "need" the snapshot repo to test xtext snapshots

**Comment by cdietrich** [comment]
looks like matching is done by id, not url, so adding two more disablings might work

**Comment by LorenzoBettini** [comment]
@cdietrich indeed in my solution I disable by id the HTTP snapshots (I also disabled the HTTPS ones because I don't need them, but that's not needed in our case)

I have no idea why it's a Tycho-only problem... I could only guess that the classpath resolution is different, so Tycho might drag in additional dependencies...

**Comment by cdietrich** [comment]
done
