### ISSUE TITLE
Serialization of parsed model leads to invalid code

### ISSUE THREAD

**Issue by lukasf98** [eclipse/xtext-core#1853]
Given the following grammar:
```
grammar org.eclipse.xtext.example.fowlerdsl.Statemachine with org.eclipse.xtext.common.Terminals

generate statemachine "http://www.eclipse.org/xtext/example/fowlerdsl/Statemachine"

Statemachine :
	{Statemachine}
	(('events' ('{'
		events+=Event*
	'}'))? &
	('resetEvents' ('{'
		resetEvents+=[Event]*
	'}'))? &
	('commands' ('{'
		commands+=Command*
	'}'))? &
	states+=State* )
;

Event:
	name=ID code=ID
;

Command:
	name=ID code=ID
;

State:
	'state' name=ID
		('actions' '{' actions+=[Command]+ '}')?
		transitions+=Transition*
	'end'
;

Transition:
	event=[Event] '=>' state=[State]
;
```
If i parse and the serialize tho following code:
```
resetEvents {
	doorOpened
}

events {
	doorClosed		D1CL
	drawerOpened	D2OP
	lightOn			L1ON
	doorOpened		D1OP
	panelClosed		PNCL
}

commands {
	unlockPanel PNUL
	lockPanel	NLK
	lockDoor	D1LK
	unlockDoor	D1UL
}

state idle
	actions {unlockDoor lockPanel}
	doorClosed => active
end

state active
	drawerOpened => waitingForLight
	lightOn		 => waitingForDrawer
end

state waitingForLight
	lightOn => unlockedPanel
end

state waitingForDrawer
	drawerOpened => unlockedPanel
end

state unlockedPanel
	actions {unlockPanel lockDoor}
	panelClosed => idle
end
```
The serialization of the parsed model leads to invalid code:
```
resetEvents
	{
	doorOpened
}

resetEvents {
}

events
	{
	doorClosed   D1CL
	drawerOpened D2OP
	lightOn      L1ON
	doorOpened   D1OP
	panelClosed  PNCL
}

events {
}

commands
	{
	unlockPanel PNUL
	lockPanel   NLK
	lockDoor    D1LK
	unlockDoor  D1UL
}

state idle
	actions {unlockDoor lockPanel}
	doorClosed => active
end

state active
	drawerOpened => waitingForLight
	lightOn      => waitingForDrawer
end

state waitingForLight
	lightOn => unlockedPanel
end

state waitingForDrawer
	drawerOpened => unlockedPanel
end

state unlockedPanel
	actions {unlockPanel lockDoor}
	panelClosed => idle
end

```
Ass seen above the first to statements are duplicated with an empty statement.
Attached below is an example project to reproduce the issue. 
See teste `org.eclipse.xtext.example.fowlerdsl.tests.StatemachineParsingTest`
[IssueDuplicate.zip](https://github.com/eclipse/xtext-core/files/8183827/IssueDuplicate.zip)

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/issues/2580
might be related.
throwing away the nodemodel seems to help here too

**Comment by lukasf98** [comment]
> eclipse/xtext#2580 might be related. throwing away the nodemodel seems to help here too

Thanks a lot for your reply. I tested it and it solves the problem I described above. However I ran into an issue with a comma seperated list. If I for example change the grammar for resetEvents to a comma seperated list:

```
('resetEvents' ('{'
	(resetEvents+=[Event] (',' resetEvents+=[Event])*)?
'}'))? &
```

And I execute the test `org.eclipse.xtext.example.fowlerdsl.tests.StatemachineParsingTest` (see attachement) I get two resetEvents Statements:

```
resetEvents { 
	doorOpened 
} 
resetEvents { 
	doorClosed 
}
```

[IssueDuplicate2.zip](https://github.com/eclipse/xtext-core/files/8196078/IssueDuplicate2.zip)

**Comment by cdietrich** [comment]
If metamodel does not matter can you move each clause to extra rule

**Comment by lukasf98** [comment]
> If metamodel does not matter can you move each clause to extra rule

What do you mean exactly? Extracting `(resetEvents+=[Event] (',' resetEvents+=[Event])*)?` into a seperate rule?

**Comment by cdietrich** [comment]
yes

**Comment by lukasf98** [comment]
@cdietrich 

I have one problem left:
If I throw away the nodemodel and then serialize my code I loose my comments.
Do you have an idea how I can retain them?

**Comment by cdietrich** [comment]
no, none besides make them exlicit

**Comment by szarnekow** [comment]
I don't see something here that's different from eclipse/xtext#2580. Closing
