### ISSUE TITLE
Missing exported packages in xtext.ide

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-core#1857]
The manifest exports for the following packages is missing:
* org.eclipse.xtext.ide.editor.folding
* org.eclipse.xtext.ide.editor.quickfix
* org.eclipse.xtext.ide.server.folding

This makes it impossible to access some crucial classes e.g. IQuickFixProvider

**Comment by cdietrich** [comment]
@tivervac are going to provide a pr?

**Comment by tivervac** [comment]
@cdietrich Damn, since I forgot to push to a branch...

I can revert and try it on a branch if you want

**Comment by cdietrich** [comment]
no its fine
