### ISSUE TITLE
Hotfix release 2.26.1 with fix for Outline and Quickfix missing export

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1867]
Please, create a hotfix release 2.26.1 with https://github.com/eclipse/xtext-core/commit/8ee47b86df5df032544f71177255a2219c7862d6

See https://www.eclipse.org/forums/index.php/t/1110515/ for the discussion that happened so far

**Comment by cdietrich** [comment]
@rubenporras can you check if c&p would work for you?

**Comment by cdietrich** [comment]
you mean milestone?

**Comment by rubenporras** [comment]
Seeing the repo name, yes, something in https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/

**Comment by rubenporras** [comment]
@cdietrich , yes coping the files works for me, if you like, I can close the issue.

As a side not, if it matters, since there will be no hotfix, I think it makes sense to pickup SimRel 2022-06 or have a new release sooner than several months down the road.

**Comment by cdietrich** [comment]
@rubenporras as always this is a cappa problem
and we dont know what else will cause problem
currently it is asm 9.3

**Comment by rubenporras** [comment]
@cdietrich , I see there is 2.27 M1, does it means that you will pick up SimRel 2022-06?
