### ISSUE TITLE
API for textual Code Actions missing

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1876]
I have noticed that there is no API for textual Code Actions, the current DiagnosticResolution takes for granted the code action will work on the EObject, and changes will be serialized to create the WorkspaceEdit.

We have a very big application based on Xtext-Eclipse, and we have both model and textual based quickfixes, and we cannot migrate the textual QFs to model based ones, so we will add support for textual quickfixes.

I assume that the support for textual based QFs is feature you would like to support as well for the LS and patches would be welcome. Is this right? I so I would prepare some. Just let me know.

**Comment by cdietrich** [comment]
i fear there is nobody who cares. contributions to lsp are always welcome
@tivervac how do you deal with that`?

**Comment by tivervac** [comment]
So far we use a very limited amount of LSP code actions. The ones we do have work on the EMF model. Though you can of course get the corresponding text for the EObject using the node model, wouldn't that fit the OP's issue?

OTOH: Code Action range -> EObject -> text through node model might not return the exact same text as was captured by the code action range, I'm guessing that's the issue then?

**Comment by rubenporras** [comment]
@tivervac , @cdietrich , https://github.com/eclipse/xtext-core/pull/1881 is how I would do it.
There is a TODO comment left that I will resolve as well, and I would add some test, but it it would be nice to have some feedback already.
Regards

**Comment by rubenporras** [comment]
I did also the refactor, it looks like it is a small change and it brings a new feature with not much effort. I will write the test if you agree.

**Comment by cdietrich** [comment]
fixed in 2.27. thx for your contribution

**Comment by cdietrich** [comment]
@rubenporras if you like you can write some line to
https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2022-05-30-version-2-27-0.md
