### ISSUE TITLE
Replace (not)equal operators by triple (not)equals refactoring broke the code!

### ISSUE THREAD

**Issue by Xpitfire** [eclipse/xtext-core#189]
Several expressions have been modified and caused the xtend to java code compilation to break!

E.g.:
java code is generated with !== expressions --> if (errorAcceptor !== null)

Caused by:
Merge pull request #188 from kthoms/kth/xtext-1089
[eclipse/xtext#1089] Replace (not)equal operators by triple (not)equals
Commit: https://github.com/eclipse/xtext-core/commit/e65030a2127855bb71c8e1190d1132520ba3545d?diff=split

Please fix this urgent bugs!

**Comment by svenefftinge** [comment]
Thanks for reviewing the change. @kthoms are you able to fix this soon or should we revert the change?

**Comment by svenefftinge** [comment]
I see @cdietrich took care of it in #190 already. Thanks

**Comment by kthoms** [comment]
Sorry for the trouble. I did not read mail until now. Thanks again @cdietrich for the immediate fix.
