### ISSUE TITLE
Storing a binary resource should remove its URI from the SourceLevelURIs

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1917]
by doing that we increase the performance of the builder because it will be possible to use binary
models from resources which has already been built and stored.

**Comment by rubenporras** [comment]
for https://github.com/eclipse/xtext-core/pull/1916

**Comment by cdietrich** [comment]
@rubenporras is there anything left?

**Comment by rubenporras** [comment]
no, it is all done. Thanks
