### ISSUE TITLE
LanguageServerImpl.codeAction no longer sets document (and resource)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1946]
LanguageServerImpl.codeAction no longer sets document (and resource)
@rubenporras any idea?

**Comment by cdietrich** [comment]
how to properly implement 
https://github.com/cdietrich/xtext-languageserver-example-simple/blob/cd_228/org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslCodeActionService.java

**Comment by rubenporras** [comment]
@cdietrich , yes, that looks good to me. Are you waiting on my comment to close the ticket? I think you have already implemented it, right?

**Comment by cdietrich** [comment]
yes but i am not sure if we should write a sentence or 2 to the releasenotes. as this is "kind of" breaking change
