### ISSUE TITLE
Use the cancelIndicator to stop creation of completion proposals

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1957]
Since any write request waits for all existing read request to be canceled before the build is started, for build request to start quickly, computing the proposals must be canceled during the computation loop.

Otherwise, if computation takes too long, one can have the following scenario:
1) User ask for content assist
2) It takes too long, so he continues typing and saves
3) He will not see any markers in a long time (until content assist computes all proposals). Thus markers might appear with a long delay, which is very confusing to him

**Comment by cdietrich** [comment]
Thx for the fix @rubenporras
