### ISSUE TITLE
java.lang.IllegalArgumentException thrown when applying quickfix 

### ISSUE THREAD

**Issue by agonzalezgaliana** [eclipse/xtext-core#1964]
Currently using Xtext version 2.28.0.

The language server shows a` java.lang.IllegalArgumentException` when executing a quickfix on a context with more than 1 error (more than one Diagnostic present). By taking a look on the code I think I've narrowed the problem to the `DiagnosticResolution `class where the following code seems to be incorrect:

`Diagnostic diagnostic = params.getContext().getDiagnostics().stream().collect(MoreCollectors.onlyElement());`

Apparently the current implementation only expects one diagnostic in the stream (`MoreCollectors.onlyElement()`) however the LSP standard allows a list of `Diagnostic` as part of the `CodeActionContext` object in the `CodeActionParams` ([see documentation ](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionContext))

Kind regards.

**Comment by cdietrich** [comment]
cc @rubenporras

**Comment by rubenporras** [comment]
I can take a look next week. As far as I recall, the pattern of just dealing with one diagnostic was present before my changes, but it might have ignored the rest instead of throwing the exception (I was not aware that `MoreCollectors.onlyElement()` would throw the exception).

**Comment by cdietrich** [comment]
fixed in 2.29. thx for the fix @rubenporras
