### ISSUE TITLE
UriExtensions decodes URI twice

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1968]
If there are files in the LS Client with URIs like

_schema:/.../abc%23xyz.foobar_

the client will encode such URIs before sending the request to

_schema:/.../abc%2523xyz.foobar_

%25 is how % encoded.

The current version of UriExtensions will decode the URI twice as part in the `toEmfUri ` method, first to the original _schema:/.../abc%23xyz.foobar_ and then again to _schema:/.../abc#xyz.foobar_. That would already result in the wrong URI, but the URI might be handled to org.eclipse.xtext.ide.server.WorkspaceManager.read(URI), the `trimFragment` is called, stripping all characters beginning on the last '#'. As a consequence exceptions like the following are thrown:

```
java.lang.RuntimeException: Cannot create a resource for 'schema:/.../abc'; a registered resource factory is needed
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:263)
```

**Comment by cdietrich** [comment]
can you give detail where the decoding is happening twice?

**Comment by rubenporras** [comment]
Hi @cdietrich , see the PR I have just created. I would like to do a test for the PR but I will not get to do that until tomorrow.

**Comment by cdietrich** [comment]
@szarnekow @rubenporras  is this fixed now?

**Comment by rubenporras** [comment]
I think so, closing the issue
