### ISSUE TITLE
IllegalStateException when using reference finder in validation during initial build

### ISSUE THREAD

**Issue by dpetroff** [eclipse/xtext-core#1987]
I have a validation that uses `IReferenceFinder#findAllReferences`. However, the builder installs `ResolvedResourceDescription`, which logs `IllegalStateException` as soon as the reference finder touches it:

https://github.com/eclipse/xtext-core/blob/6252f44af9d8e236bafe5c830958d43e1bf9113b/org.eclipse.xtext/src/org/eclipse/xtext/build/ResolvedResourceDescription.java#L81-L85

What is considered the "correct" way to have validations that care about references without spamming my log with thousands of `IllegalStateException`s?

At the moment I simply check if any `ResolvedResourceDescription`s are present and bail from the validation, but it seems wrong that the exception is not thrown when the thing is considered so wrong that it was necessary to log an entire stack trace whenever you touch it. The fact that the exception is not thrown but only used for logging seems to imply that it's really not an illegal state but maybe something I should only see at the debug log level. If it really is an illegal state, it would make more sense to actually throw the exception.

**Comment by cdietrich** [comment]
Normally during build / validation not all references are built (yet - depending on the order of files) and thus the index is not complete. was this ever working / is the a regression or is that something new you try?
cc @szarnekow

**Comment by szarnekow** [comment]
@dpetroff I'm sorry to let you know that this was never supported in Xtext. Validations are triggered per resource, meaning there might be more resources in the queue that wait to be linked. The reference information that's available to the validation is therefore not guaranteed to be complete.

There are viable workarounds for this if you know which kind of references are requested. But if general reference-search is strictly necessary for your validation (e.g. for global unused declarations), you'd need to apply some serious customizing to the builder(s) and editor.

**Comment by dpetroff** [comment]
It sounds like that exception should be thrown instead of just logged.

I know I was being naughty and I was aware that strictly speaking validations are not guaranteed to run after all the linking is done, but in my specific use case, it looks like the indexer is figuring out the correct dependency order in which to build the resources in a way that my validation works regardless. Maybe there are some corner cases where that doesn't quite work out, but for this particular use case, I can live with that.

> There are viable workarounds for this if you know which kind of references are requested.

It'd be good to know what are the workarounds for future reference.

**Comment by cdietrich** [comment]
depending on how your references look like you can store the references names (using `NodeModelUtils`) in the UserData of the IndexEntries (created by `IDefaultResourceDescriptionStrategy`) and then query the index to find out if and where elements are referenced

https://stackoverflow.com/questions/28051108/inverse-reference-lookup

**Comment by cdietrich** [comment]
@dpetroff any update here? can we close?

**Comment by dpetroff** [comment]
It still seems odd to me to log the exception without throwing it there, but if you think it should stay that way, you can close it.

**Comment by cdietrich** [comment]
the question is still is: how can we solve your usecase (the workarounds i referred to)

**Comment by szarnekow** [comment]
This works like it was designed. The exception is logged for stability reasons to guard users against faulty language implementations. Language developers will see the exception usually quite early and can fix their implementations accordingly.
I'll close the ticket here. Please reopen in https://github.com/eclipse/xtext if you have new information.
