### ISSUE TITLE
The IDE ContextAssistService wrongly flags all answers as incomplete

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1999]
The IDE ContextAssistService wrongly flags all answers as incomplete, it should rather set to incomplete only those which truly are incomplete, either because they have been cancelled or because the acceptor reached its upper limit.

**Comment by LorenzoBettini** [comment]
@rubenporras can it be you inadvertently pushed directly to master some of the ongoing work? I have compilation failure in xtext.ide because of couldAcceptAllProposals cannot be found

**Comment by rubenporras** [comment]
I do not have the rights to do that, but yes, a PR was merged with compilation failures. https://github.com/eclipse/xtext-core/pull/2002 should fix it.

**Comment by szarnekow** [comment]
I merged the stuff obviously too eagerly. Sorry about that
