### ISSUE TITLE
Make core-tests run

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-core#2]
From https://github.com/eclipse/xtext-core/tree/master/org.eclipse.xtext.tests we need to make pass as many tests as possible and delete the rest (they will be maintained in downstream repositories)

**Comment by svenefftinge** [comment]
Is there still something to do here?

**Comment by cdietrich** [comment]
nope

**Comment by spoenemann** [comment]
Thanks for the effort!
