### ISSUE TITLE
Wrong version of com.google.inject in generated .target file

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#2014]
The wizard of 2.29.0.M3 generates this requirement in the .target file

```xml
<unit id="com.google.inject" version="5.0.1.v20221112-0806"/>
```

But the used location

```xml
<repository location="https://download.eclipse.org/tools/orbit/downloads/2022-12"/>
```

only provides this version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<p2:Requirement
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:p2="http://www.eclipse.org/oomph/p2/1.0"
    name="com.google.inject"
    versionRange="[5.0.1.v20210324-2015,5.0.1.v20210324-2015]"/>
```

I guess this is due to https://github.com/eclipse/xtext-core/commit/906d30380c2b81e1af2181ee5c262fc6123035bc that did not consistently reverted the change.

On a side note: it's very unmaintainable to specify versions in the target platform, especially since we already use versioned p2 repositories.

It is even more unmaintainable because we never automatically test that what the wizard generates can be built correctly.

Should I help provide a PR for this specific issue?

**Comment by cdietrich** [comment]
looks like you missed the orbit discussion
/2022-12 with the new timestamps will show up somewhen today
https://github.com/eclipse/xtext/issues/2112#issuecomment-1313135190

**Comment by cdietrich** [comment]
@LorenzoBettini are you still involved in parsley? did you see Eds message?

**Comment by LorenzoBettini** [comment]
@cdietrich yes I am, and I've already answered in the mailing list. I'll get to that in the next few days hopefully
