### ISSUE TITLE
Cross-References in context object of QuickfixProvider are not resolved

### ISSUE THREAD

**Issue by agonzalezgaliana** [eclipse/xtext-core#2032]
To give an overview of the problem:

- Language Server that works with a DSL
- The DSL metamodel references a secondary metamodel
- During runtime we have XMI files declaring models of the secondary metamodel
- Using my DSL I'm able to cross-reference objects of the XMI files

I want to write a quickfix that modifies the linked object of a cross-reference when a validation error occurs. Example:

`Boolean myBoolean = 1;`

Where:

- "Boolean" is a cross-reference to an XMI existing object (Boolean).
- The literal (1) has an implicit cross-reference to an XMI existing object (Integer).

As a result of applying the quickfix I want to get:

`Integer myBoolean = 1;`

The problem comes in the QuickfixProvider where the "context" object does not have information about the cross references (they are pointing to objects with null properties). By taking a look on the status of the resource set of the context object I can see that there is only one resource and none of the XMI resources available appear in there.

By debugging a little, I was able to see that the class "DiagnosticResolution" generates a new resource set and a new resource out of the document URI and later returns the context object using the new resource:

```
private EObject getContextObject() {
		ResourceSet resourceSet = access.newLiveScopeResourceSet(uri);
		XtextResource tmpResource = (XtextResource) resourceSet.getResource(uri, true);
		EObjectAtOffsetHelper eObjectAtOffsetHelper = tmpResource.getResourceServiceProvider().get(EObjectAtOffsetHelper.class);
		if (eObjectAtOffsetHelper == null) {
			return null;
		}
		int offset = document.getOffSet(diagnostic.getRange().getStart());
		return eObjectAtOffsetHelper.resolveContainedElementAt(tmpResource, offset);		
	}
```

By doing this, we're losing all information of the original resource (including the resolved references).

My questions would be:

- is this intended? How can a context object be helpful for the quickfix if we're missing information about "the context"?
- what's the need of creating the context object out of a new resource and resource set?
- is there a possibility to use my "resolved" resource set in the quick fix provider?

Many thanks in advance.

**Comment by cdietrich** [comment]
@szarnekow @rubenporras  any idea?

**Comment by szarnekow** [comment]
@agonzalezgaliana I'd be interesting to understand how the linking is performed in your case. Usually the EMF proxies would be resolved on demand when the objects are traversed - also in a fresh resource set.

**Comment by agonzalezgaliana** [comment]
@szarnekow we're not doing anything special for the linking apart from the custom scoping. Usually during runtime my resource set is filled with the XMI resources (located in the same workspace folder) + LazyLinkingResource representing my DSL file. Linking works fine there. However in the quickfix scenario the object I get as context belongs to a new LazyLinkingResource in a resource set without other resources. Perhaps this last thing is the one preventing the EMF proxies to be resolved?

@cdietrich at this moment I have no reproducible code to hand over since it happens in our company project. Let's see if I can find time to build something from scratch.

**Comment by cdietrich** [comment]
i assume you also have to prepare the temp resourcesets then.

**Comment by agonzalezgaliana** [comment]
@cdietrich not sure if we need to customize something since, by debugging, I can see that the new index is passed in when creating the new resource set:

```
public XtextResourceSet createNewResourceSet(ResourceDescriptionsData newIndex) {
		XtextResourceSet result = resourceSetProvider.get();
		projectDescription.attachToEmfObject(result);
		ProjectConfigAdapter.install(result, projectConfig);
		ChunkedResourceDescriptions index = new ChunkedResourceDescriptions(indexProvider.get(), result);
		index.setContainer(projectDescription.getName(), newIndex);
		externalContentSupport.configureResourceSet(result, openedDocumentsContentProvider);
		return result;
	}
```
The new index actually contains all IObjectDescription objects from all XMI files. However the returned XtextResouceSet has only one resource set.

**Comment by cdietrich** [comment]
yes but why cannot it be resolved

**Comment by agonzalezgaliana** [comment]
> so the question is: how you you make the xmi files visible so that they are indexed an can be resolved.

In the standalone setup of the DSL project we added the following:


```
@Override
public void register(Injector injector) {
	if (!EPackage.Registry.INSTANCE.containsKey(SecondaryMetamodelPackage.eNS_URI)) {
		EPackage.Registry.INSTANCE.put(SecondaryMetamodelPackage.eNS_URI, SecondaryMetamodelPackage.eINSTANCE);
	}

	IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);

	IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("xmi", serviceProvider);

	super.register(injector);
}
```

With this we get that automatically (nothing customized on our side)

**Comment by cdietrich** [comment]
then the question is why resolving in the temp resource does not work.

**Comment by rubenporras** [comment]
I came late to the discussion but I agree with the last comment, the question is why resolving in the temp resource does not work. I do not think it has anything to do with the standalone setup of the DSL, that is the same regardless the resourceSet.

**Comment by agonzalezgaliana** [comment]
> I came late to the discussion but I agree with the last comment, the question is why resolving in the temp resource does not work. I do not think it has anything to do with the standalone setup of the DSL, that is the same regardless the resourceSet.

Hi @rubenporras I have a little understanding of Xtext and the resolution process, but I think that in order to resolve things in the temp resource we would need to have other resources in the same "temp resource set", correct? in my case that resource set contains just one resource. Is it expected that we manually enhance the temp resource set or is it something that Xtext should do and it is not working?

**Comment by szarnekow** [comment]
@agonzalezgaliana The Xtext / EMF default semantics would load the "missing" referenced XMI resource on demand. I strongly suspect that your project linking is somehow customized or works by accident in the incremental build.

To move forward with this ticket: Please attach a self contained reproducer that illustrates the misbehavior with a somewhat default setup.
To the best of my / our knowledge, there's no difference between a fresh temporary resource set and a random other resource set used during the build.

To move forward with the problem in your project context: There's professional support available from different involved parties (e.g. via @cdietrich  or me).

**Comment by rubenporras** [comment]
@agonzalezgaliana , 

> I think that in order to resolve things in the temp resource we would need to have other resources in the same "temp resource set", correct?

The resources must not be in the resource set, the only requirement is that the builder can load them on demand when needed. It is very hard to give advice without a reproducer and your customization, but you can step through the code and check why demand load is not working.

**Comment by agonzalezgaliana** [comment]
Currently trying to reproduce the same behavior in a smaller project. Surprisingly it works on that one. I'm trying to find out what the difference are so we can get an explanation of the wrong behavior.

**Comment by agonzalezgaliana** [comment]
I'm closing the issue cause we found the issue that was actually on our scope resolution. Anyways I'd like to thank your support and contribution.
