### ISSUE TITLE
Switch to Maven/Tycho (EXPERIMENT)

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#2052]
As said here https://github.com/eclipse/xtext/issues/2133 I'd like to try to switch to Maven/Tycho

**Comment by LorenzoBettini** [comment]
I started working on that in my fork, this branch https://github.com/LorenzoBettini/xtext-core/tree/lb_2052_maven_tycho

For the moment org.eclipse.xtext.util and org.eclipse.xtext are compiling!

I also set up a GitHub Actions workflow since I'll deal with Jenkins later.
In case, later, we can remove the GitHub Actions workflow.

**Comment by LorenzoBettini** [comment]
This is the build log https://github.com/LorenzoBettini/xtext-core/actions

**Comment by LorenzoBettini** [comment]
@cdietrich in xtext.ide the MANIFEST wants org.eclipse.lsp4j with at least 0.19. I can't find a p2 repo providing that. Do you know where I can find it?

**Comment by cdietrich** [comment]
Please check Xtext.setup it contains the url

**Comment by LorenzoBettini** [comment]
Right! Thanks! I'm currently not using Xtext.setup and haven't thought about that.

**Comment by LorenzoBettini** [comment]
`org.eclipse.xtext.testing` builds and tests run!

**Comment by LorenzoBettini** [comment]
@cdietrich should the Xtend files be processed during the build? If so, I guess I should use the latest released version of the `xtend-maven-plugin`, because it's not in this repo, right

**Comment by LorenzoBettini** [comment]
`org.eclipse.xtext.xtext.generator` and `wizard` build!

**Comment by cdietrich** [comment]
regarding xtend: yes we do the same with the gradle build.
in xtext-eclipse and xtext-xtend we had a https://github.com/eclipse/xtext-xtend/blob/8521139f5652be55444114de850af23aee37ab47/releng/org.eclipse.xtend.tycho.parent/pom.xml#L13 property

**Comment by LorenzoBettini** [comment]
`xtext.ide.tests` run and pass in the Maven build! :)

**Comment by LorenzoBettini** [comment]
Build and tests are performed also on macOS and Windows

**Comment by LorenzoBettini** [comment]
In the current maven build script I see

```
-Dmaven.repo.local=.m2/repository
```

I guess it's useless since the Jenkins workspace is ephemeral anyway, so I removed that.

It's installing in

```
/home/jenkins/.m2/repository/org/eclipse/xtext/
```

but it should not harm anything else...

do you want to me to put it back anyway?

**Comment by cdietrich** [comment]
i assume its there to be on safe side also in local builds

**Comment by cdietrich** [comment]
looks like there are still 7 tests missing

**Comment by LorenzoBettini** [comment]
OK, I'll create the WIP PR, detailing first the (temporary) manual steps to use the project from Eclipse and then, hopefully later today, I'll leave a few notes in the PR on the relevant changes and things that I think are still left to do

**Comment by LorenzoBettini** [comment]
> looks like there are still 7 tests missing

I'll write a few additional details about that in the PR.
However, I detected a few duplicates (at least, comparing the run tests in Eclipse), which are correctly discarded during the Maven build.

**Comment by cdietrich** [comment]
for missing tests. might be a naming convention problem e.g. LexerSLComment

**Comment by cdietrich** [comment]
i also see diffs in
org.eclipse.xtext.parser.unorderedGroups
org.eclipse.xtext.testing.tests	
org.eclipse.xtext.testing.tests.junit5
org.eclipse.xtext.validation.junit5	
but did not look into that yet
[a.txt](https://github.com/eclipse/xtext-core/files/10427657/a.txt)
[b.txt](https://github.com/eclipse/xtext-core/files/10427658/b.txt)

**Comment by cdietrich** [comment]
in gradle this executes the junit5 tests from junit4
in eclipse it works when you select junit4 in the launch config dialog

**Comment by LorenzoBettini** [comment]
But why do we want to do that?
JUnit 4 tests are expected to be executed from JUnit 5 (if the vintage dependency is there), but the other way around makes no sense...

**Comment by cdietrich** [comment]
we have 1 billion junit4 tests, so we run all tests as junit4. and a handful of junit5 api that also _wants_ to be tested. so we tell gradle junit4 to run them with that bridge.

**Comment by LorenzoBettini** [comment]
In the current build, they are run with JUnit 5 (if it's in classpath of the project), which can run also JUnit 4 tests with the vintage engine

**Comment by cdietrich** [comment]
but then the should be run?

**Comment by cdietrich** [comment]
looks like they are, but https://ci.eclipse.org/xtext/job/xtext-core/job/master/lastCompletedBuild/testReport/org.eclipse.xtext.testing.tests.junit5/InjectionExtensionStaticInnerClassesTest$StaticInnerClassTest/
is missing

**Comment by LorenzoBettini** [comment]
yes, I spotted now that one as well, looks like

> The Surefire Plugin excludes nested classes by default: http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludes ; By removing all default exclusions the nested classes get executed too, JUnit 4 and JUnit 5.

I'm trying that now...

**Comment by cdietrich** [comment]
what is with FileAwareTestLanguageValidationJunit5Test?

**Comment by LorenzoBettini** [comment]
> yes, I spotted now that one as well, looks like
> 
> > The Surefire Plugin excludes nested classes by default: http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludes ; By removing all default exclusions the nested classes get executed too, JUnit 4 and JUnit 5.
> 
> I'm trying that now...

Yes, that was the culprit: all tests in .xtext.testing are now executed just like in Eclipse.

**Comment by LorenzoBettini** [comment]
Now it's 4736 instead of 4738.

The two tests of FileAwareTestLanguageValidationJunit5Test are missing.

In the Maven output, I see that JUnit 4 is used (while in .xtext.testing JUnit 5 was used).

I'll have to investigate that (maybe tomorrow or this evening)

**Comment by LorenzoBettini** [comment]
Done! 4738 as before! :)

It took me the whole evening to solve that, so further notes on the PR will have to wait til tomorrow.

**Comment by SimonCockx** [comment]
@LorenzoBettini Just out of curiosity: why are you switching to Maven/Tycho?

We've been working with Maven/Tycho for a couple of years now, and we are actually at this point planning to switch to Gradle. We've had too many problems with Tycho in the past (e.g., corrupting the `.m2/repository` folder when switching versions, having problems with transitive dependencies when a pure Maven project relies on our Tycho project, etc etc)

**Comment by cdietrich** [comment]
there are multiple problems with gradle
- knowledge
- xtend-gradle plugin unmaintained (knowledge problem)
- ability to create artifacts for eclipse and maven/gradle
- the current sign and deploy process will explode sooner or later https://github.com/eclipse/xtext/issues/2065
- we plan to do a repo merge. see also discussion in https://github.com/eclipse/xtext/issues/2133

**Comment by SimonCockx** [comment]
@cdietrich thanks for the update, that's interesting. Luckily for me, all of these problems don't apply, so that's a reassurance. :)

This still means that building Xtext projects with Gradle is supported, right?

**Comment by cdietrich** [comment]
well at least when nobody shows mercy and fixes https://github.com/xtext/xtext-gradle-plugin/issues/207 and https://github.com/xtext/xtext-gradle-plugin/issues/203 only if you wont use any xtend at all in your codebase

**Comment by SimonCockx** [comment]
@LorenzoBettini well, if we ignore performance for a moment, for one the documentation on Gradle is fantastic, which I really can't say about Tycho. ;)

Seriously though, I know there are solutions to the problems I've mentioned, but there are really no good guides explaining them, and our team probably lacks a person with good knowledge about it. Which is another important reason for our plan to switch to Gradle.

I get your point on having too much flexibility, but as someone relatively new to Java build systems, I must say that a graph-based representation of tasks comes much more naturally to me than a (seemingly arbitrary, at least for me :) ) rigid lifecycle line.

That being said, I lack experience of working with Gradle in a big project though, so I'll stop fighting. Maybe in a couple of years I'll get back in the ring ;)

**Comment by minesh-s-patel** [comment]
@LorenzoBettini I totally agree with your mvn vs gradle argument. I have seen massively over engineered build systems built with gradle ('with great power comes the ability to screw things up'). That being said - using maven tycho has been a PITA for @SimonCockx and our team and we want to move off it. We thought that gradle was the strategic way forward but it sounds like we just need to convert out build to be pure (no tycho) mvn.

**Comment by cdietrich** [comment]
with repo merge this is done
