### ISSUE TITLE
Why does `org.eclipse.xtext` export packages it doesn't have?

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#2057]
While working on https://github.com/eclipse/xtext-core/issues/2052 I noted that `org.eclipse.xtext` exports tons of packages it doesn't have in the MANIFEST. No error is reported because in that project, that PDE problem is suppressed.

**Comment by cdietrich** [comment]
can you give a list of these?

**Comment by LorenzoBettini** [comment]
Just an idea:

```
   org.eclipse.xtext.junit4,
   org.eclipse.xtext.testing,
   org.eclipse.xtext.tests,
   org.eclipse.xtext.xbase,
...
   org.eclipse.xtext.junit4,
   org.eclipse.xtext.tests,
   org.eclipse.xtext.xbase,
...
```

Note: they are also repeated!

**Comment by cdietrich** [comment]
arent these xfriends?

**Comment by szarnekow** [comment]
They're xfriends: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/META-INF/MANIFEST.MF#L11

**Comment by LorenzoBettini** [comment]
Sorry, maybe I'm too tired O:)
I didn't notice the indentation and that they refer to friend packages
