### ISSUE TITLE
[formatting2] `assertAllWhitespaceIsFormatted` fails if input was already formatted

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xtext-core#2058]
When setting `allowUnformattedWhitespace` to `false` in `FormatterTestHelper::assertFormatted`, I would expect the test to succeed if all hidden nodes have a `IHiddenRegionFormatting` defined. However, instead the assertion fails whenever there is a hidden node that doesn't have a `ITextReplacement`, which can be for two reasons:
1. The formatter didn't define a `IHiddenRegionFormatting` for it.
2. The hidden node is already in the right format.

I think only the first case is interesting to check, and that the current implemented way greatly limits the usefulness of the assertion, i.e., to verify whether you didn't miss any hidden nodes in you formatter.

In the [FormatterTestHelper](https://github.com/eclipse/xtext-core/blob/0a6606ee5091c48a716f74932bb6dd693cbee227/org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/formatter/FormatterTestHelper.java), you can see on line 111 that `assertAllWhitespaceIsFormatted` takes a list of `ITextReplacements` instead of looking at the `IFormattableDocument`.

**Comment by cdietrich** [comment]
do you mean you dont format the whitespace if it is already formatted in your formatter code
aka

`if (is already formatted { /*do nothing*/}`

can you again provide a hello world reproducer?

**Comment by SimonCockx** [comment]
Yes, that's what I mean. I'll create a repro in a sec.

**Comment by cdietrich** [comment]
i assume the assertion is: you need to specify explicit ws for all places even if it is already formatted
=> you would need a 

if (is already formatted { detect the current formatting and apply it, (dont know if adding an empty hiddenregionformatter would also work (just [])}

**Comment by cdietrich** [comment]
unfortunately i cannot find any tests for it in Xtext code base so it is hard to tell what the goal is/was with this feature

**Comment by SimonCockx** [comment]
Small other point: I'm pretty sure [the docs on AbstractJavaFormatter](https://github.com/eclipse/xtext-core/blob/9bd94bbb3aa1edfb9766f1fd11c6eb36d59bd78f/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractJavaFormatter.java#L46) are wrong. The example defines formatting methods as `_format`, but they should be named `format`, otherwise they don't work. See also the [definition of the dispatcher](https://github.com/eclipse/xtext-core/blob/9bd94bbb3aa1edfb9766f1fd11c6eb36d59bd78f/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractJavaFormatter.java#L136), which searches for methods called `format`, not `_format`.

**Comment by cdietrich** [comment]
the dispatcher searches both _format and format

```
m -> ("format".equals(m.getName()) && m.getParameterCount() == 2
						&& m.getParameterTypes()[0] != Object.class // do not polymorphic dispatch on the api method itself
						&& m.getParameterTypes()[1] == IFormattableDocument.class)
					|| ("_format".equals(m.getName()) && m.getParameterCount() == 2
						&& m.getParameterTypes()[1] == IFormattableDocument.class),
```

**Comment by SimonCockx** [comment]
Oh, you're right, I was too fast. :) Although my minimal repro did not work when I named the method `_format` for some reason...

**Comment by cdietrich** [comment]
can you try a formattertesthelper subclass with

```
	protected void assertAllWhitespaceIsFormatted(ITextRegionAccess access, List<ITextReplacement> replacements) {
		List<ITextSegment> expected = Lists.newArrayList();
		IHiddenRegion current = access.regionForRootEObject().getPreviousHiddenRegion();
		while (current != null) {
			for (ITextSegment s : current.getMergedSpaces()) {
				if (s.getLength() > 0) {
					expected.add(s);
				}
			}
			current = current.getNextHiddenRegion();
		}
		List<ITextSegment> missing = TextRegions.difference(expected, replacements);
		if (!missing.isEmpty()) {
			TextRegionsToString toString = new TextRegionsToString().setTextRegionAccess(access);
			for (ITextSegment region : missing)
				toString.add(region, region.getClass().getSimpleName());
			String msg = "The following regions are not formatted:\n" + toString;
			System.err.println(msg);
			Assert.fail(msg);
		}
	}
```

**Comment by cdietrich** [comment]
org.eclipse.xtext.formatting2.FormatterRequest.allowIdentityEdits might be the culprit

**Comment by cdietrich** [comment]
can you also test this patch https://github.com/eclipse/xtext-core/commit/d251508008dde5ae3e97da5445774683c5f5fe02
