### ISSUE TITLE
[LanguageServer] it looks like the hover has a off by one problem

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#22]
```
/** This is a test */
Hello World!
```
Hovering on `d` does not give the expected hover.

**Comment by cdietrich** [comment]
see https://github.com/Microsoft/language-server-protocol/issues/26 as well

**Comment by spoenemann** [comment]
So is this an Xtext Language Server problem or a VS Code problem?

**Comment by cdietrich** [comment]
It is a follow up problem using xtext in vs code. This is a tracking ticket for users complaining on hover not working in xtext in vs code

**Comment by spoenemann** [comment]
If it's not an Xtext problem we should close the issue.

**Comment by cdietrich** [comment]
Can you verify our API does not crash when queried out of range

**Comment by spoenemann** [comment]
`org.eclipse.xtext.ide.server.Document#getOffSet(Position)` throws IndexOutOfBoundsException if the offset is out of range, but I think that's ok. The server then sends an error response.
