### ISSUE TITLE
Company specific code templates

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#221]
Some projects have checked in company specific code templates. These settings should be removed.

E.g. https://github.com/eclipse/xtext-core/blob/4270986cba1dc9d811dad148f93e11bbc7193fa2/org.eclipse.xtext/.settings/org.eclipse.jdt.ui.prefs, `org.eclipse.jdt.ui.text.custom_code_templates` contains TypeFox.

**Comment by kthoms** [comment]
Searching the workspace reveals quite some entries. I found 57 entries for search string `Copyright (c) ${year}`.

We may extend the Oomph setup by a variable and use it to create a workspace specific preference.

**Comment by svenefftinge** [comment]
I have seen other projects using a generic copyright header, i.e. something like
"Copyright (c) 2017 by Eclipse Xtext contributors"
I am not sure if that is a valid copyright, though.

**Comment by kthoms** [comment]
According to https://www.eclipse.org/legal/copyrightandlicensenotice.php I doubt that this is valid.

> {INITIAL COPYRIGHT OWNER} is the copyright owner that created the initial content.
[...]the copyright owner is usually the employer

**Comment by waynebeaton** [comment]
The information on the copyright and license notice page is based on the advice of our IP Lawyer. At this point in time, it stands. This question has come up a couple of times recently, so we have asked our IP Lawyer for an opinion. I'll let you know what we learn.

FWIW, the author is not necessarily the copyright owner. Very often the employer owns the copyright for work done by their employees.
