### ISSUE TITLE
XtextGeneratorLanguage.generateXtendStubs used inconsistently

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#223]
`XtextGeneratorLanguage.generateXtendStubs` is used by `XtextGeneratorTemplates`, while the fragments use `CodeConfig.preferXtendStubs`. Is it really necessary for clients to use different settings per language? I propose to remove `XtextGeneratorLanguage.generateXtendStubs`. If you really need that setting, you can still use `XtextGeneratorLanguage.guiceModule` to bind a different CodeConfig for each language.

**Comment by cdietrich** [comment]
is this documented somewhere?

**Comment by spoenemann** [comment]
I don't think `XtextGeneratorLanguage.generateXtendStubs` is documented anywhere.  `CodeConfig.preferXtendStubs` is documented here: https://www.eclipse.org/Xtext/documentation/302_configuration.html#generator

**Comment by cdietrich** [comment]
no i mean the existence of the `XtextGeneratorLanguage.guiceModule`

**Comment by spoenemann** [comment]
We could add some documentation about it.

**Comment by cdietrich** [comment]
close as wontfix
