### ISSUE TITLE
Junit4Fragment2 added dependencies for .tests project

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#230]
The Xtext project wizard in Xtext 2.11, when it creates a new .tests project automatically adds these deps

```
 org.eclipse.xtext.testing,
 org.eclipse.xtext.xbase.testing
```

The Junit4Fragment2 only makes sure to add `org.eclipse.xtext.testing` but not the other one, while it should also add `org.eclipse.xtext.xbase.testing` so that, when run on a project created with a previous version of Xtext, it will make sure the .tests project have up to date dependencies

**Comment by cdietrich** [comment]
should happen for xbase projects only

**Comment by cdietrich** [comment]
ok

**Comment by LorenzoBettini** [comment]
@cdietrich please review

**Comment by cdietrich** [comment]
Looks good, I still wonder if we want to make that skipppable. If I remove the dependency and run it again will it come back @spoenemann what do you think?

**Comment by LorenzoBettini** [comment]
sorry, I forgot to create the PR: https://github.com/eclipse/xtext-core/pull/232
