### ISSUE TITLE
[LanguageServer] Workspace Symbol service not working

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#24]
VSCode does not how Workspace Symbols although Xtext Sends them

```
Client Request:
	{"jsonrpc":"2.0","id":4,"method":"workspace/symbol","params":{"query":"S"}}
Server Response:
	{"id":"4","result":[{"name":"S1","kind":0,"location":{"uri":"file:///Users/dietrich/git/xtext-languageserver-example/demo/demo.statemachine","range":{"start":{"line":0,"character":6},"end":{"line":0,"character":8}}}}],"jsonrpc":"2.0"}

```

i dont know if the response is invalid or vscode is buggy

**Comment by cdietrich** [comment]
Document Symbol Service is running fine

**Comment by cdietrich** [comment]
P.S: it seems to work with the Insider build

**Comment by svenefftinge** [comment]
Is this solved now that we return SymbolKind.Property by default?

**Comment by svenefftinge** [comment]
We should file an issue over at vscode

**Comment by cdietrich** [comment]
No it is fixed by the newest vs code version and the enum return. I am not sure how the protocol handles Enums when not specified.

**Comment by svenefftinge** [comment]
So what would be the concrete action for this ticket?

**Comment by cdietrich** [comment]
do we ensure we return a valid enum value? if so we can close.

**Comment by svenefftinge** [comment]
we never send 0 but null in case the kind is not set. Should be handled generically in ls-api.
See https://github.com/TypeFox/ls-api/issues/1
