### ISSUE TITLE
[LSP] ServerLauncher validates messages

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#241]
Messages from VSCode are validated in ServerLauncher.

The messages LSP4J Expects and the ones VSCode dont fit.
See https://github.com/eclipse/lsp4j/issues/50

maybe we can disable validation locally

or introduce a param to the main method so that i can decide from outside

**Comment by cdietrich** [comment]
workaround for user: create own serverlauncher class that has validation false.
maybe we can make this parametrizable via arg to main method

**Comment by cdietrich** [comment]
the bug in LSP4J is fixed. so what is left to decide if we want to introduce a arg for that. might be decided after 2.11

**Comment by svenefftinge** [comment]
We should have 0.1.1 release of LSP4J also I'm fine with additional optional arguments for the main method

**Comment by spoenemann** [comment]
I'm closing this as it's not Xtext related. We'll include the LSP4J fix in the Xtext 2.11.0 release.
