### ISSUE TITLE
[Wizard] Use newest xtext-gradle-plugin

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#250]
we currently use `1.0.2` instead of `1.0.15` which gives

Cannot install debug information into bytecode, because 'org.eclipse.xtext.smap' is missing on the classpath. Please add 'org.eclipse.xtext.smap' to your plugin classpath.

**Comment by spoenemann** [comment]
> we currently use 1.0.2 instead of 1.0.15

Where have you found that? The plugin version is defined in versions.gradle and is currently set to `1.0.15`.

**Comment by cdietrich** [comment]
dont we have an update site with the nightly? http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/ is >1 week old

**Comment by cdietrich** [comment]
@dhuebner do you know why this is not updated?

**Comment by spoenemann** [comment]
There were problems with the signing service. I hope it will be fixed with the next nightly build. Can this issue be closed?

**Comment by cdietrich** [comment]
yes it can.

still the questions: why does the feature have an older timestamp than the plugin?

**Comment by spoenemann** [comment]
Plugin and feature timestamps can differ because they are created by different build jobs. No idea how the plugin timestamp can be *older*, though.
