### ISSUE TITLE
Document testing API

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#253]
We should have some basic documentation on the testing API 

e.g. https://www.eclipse.org/forums/index.php/t/1083745/

**Comment by miklossy** [comment]
@erogleva Do you have any progress on this?

**Comment by erogleva** [comment]
No, sorry, since there was no answer, I hadn't really started working on this.

**Comment by miklossy** [comment]
Are you still interested in providing a contribution? It would be awesome.

But if not, no problem, I can take over this.

**Comment by erogleva** [comment]
Yes, I could still provide a contribution. I will do it in the next few days :)

**Comment by miklossy** [comment]
[PR](https://github.com/eclipse/xtext/pull/1727) has been created that adds ValidationTestHelper  documentation to the Xtext Domainmodel tutorial.

**Comment by miklossy** [comment]
[PR](https://github.com/eclipse/xtext/pull/1728) has been created that adds
- CompilationTestHelper documentation to the Xtext Domainmodel tutorial
- Automated UI testing documentation to the Eclipse Support webpage

**Comment by miklossy** [comment]
Fixed in 2.22.
