### ISSUE TITLE
[wizard] Optimize dependencies produced for new projects

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#254]
The wizard adds the following dependencies to build.properties:
```
additional.bundles = org.eclipse.xtext.xbase,\
                     org.eclipse.xtext.common.types,\
                     org.eclipse.xtext.xtext.generator,\
                     org.eclipse.emf.codegen.ecore,\
                     org.eclipse.emf.mwe.utils,\
                     org.eclipse.emf.mwe2.launch,\
                     org.eclipse.emf.mwe2.lib,\
                     org.objectweb.asm,\
                     org.apache.commons.logging,\
                     org.apache.log4j,\
                     com.ibm.icu
```

From this list it is not necessary to add
- org.eclipse.xtext.xbase
- org.eclipse.xtext.common.types
- org.objectweb.asm
since they are already dependencies by Require-Bundle.

Since org.apache.log4j would be added as imported package anyway with running the generator the wizard could already add this dependency to the runtime project.

**Comment by spoenemann** [comment]
The Require-Bundle dependencies are very likely to be modified by users after project creation. If someone removes xbase and common.types because he's sure he won't use those in his DSL, he might get problems running the workflow if common types is not in the additional.bundles.

**Comment by kthoms** [comment]
Good point. So we just leave it as is?

**Comment by spoenemann** [comment]
Yes, as long as there are no complains from users.
