### ISSUE TITLE
API errors: "The re-exported type ... has been removed from ..."

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#259]
After a fresh Oomph setup the projects `org.eclipse.xtext` and `org.eclipse.xtext.ide` contain a lot of API errors:

![screenshot 62](https://cloud.githubusercontent.com/assets/265597/22284938/d6400304-e2e9-11e6-97f0-b220090d4490.png)

**Comment by LorenzoBettini** [comment]
Yes, we also discussed that in the past but I think we never came to a possible solution...  IIRC there was a proposal of simply removing API baseline. I think we can't get rid of those errors since now the core projects are not PDE projects anymore so API tooling will just never work...

**Comment by kthoms** [comment]
Removing API tooling is not a solution. How should we detect API breakages or the need to declare @since tags then properly?

**Comment by spoenemann** [comment]
We could use the api-diff Hudson job instead:
https://hudson.eclipse.org/xtext/job/xtext-xtend-api-diff/lastSuccessfulBuild/artifact/output/changes.html

**Comment by svenefftinge** [comment]
We could also just be careful when changing signatures and review them. 
API tooling is eclipse only, which is why it doesn't work for us.

**Comment by cdietrich** [comment]
we no longer have api tooling. thus this is obsolete
