### ISSUE TITLE
[LanguageServer] Consider Providing "Additional Proposal Info" through completionItem/resolve

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#26]
We should evaluate if we can do something similar we do with the additional proposal info stuff in eclipse with the completionItem/resolve service in language server

**Comment by spoenemann** [comment]
The *resolve* request is only required if it's too expensive to compute all details of each proposal at once (e.g. complex text replacements). However, our current content assist infrastructure in xtext.ide does not allow this kind of deferred proposal computation. I think we should reconsider this when we face performance problems in some application.
