### ISSUE TITLE
 A different resource with the URI was already registered from vs code

### ISSUE THREAD

**Issue by akosyakov** [eclipse/xtext-core#267]
I am getting the following exception in vs code: 
```
[Error - 15:02:23] Request textDocument/definition failed.
  Message: java.lang.IllegalStateException: A different resource with the URI 'file:///Users/kosyakov/git/...' was already registered.
  Code: -32603 
```

Probable ServerModule should use the synchronized resource set.

**Comment by cdietrich** [comment]
@akosyakov DefaultRuntimeModule already uses

```
	public Class<? extends XtextResourceSet> bindXtextResourceSet() {
		return SynchronizedXtextResourceSet.class;
	}
```

**Comment by akosyakov** [comment]
@cdietrich I tried it did not fix an issue

**Comment by cdietrich** [comment]
how often does this problem happen?

**Comment by akosyakov** [comment]
It seems that several read requests are processed in parallel and both are trying to load the same resource. The root cause that [the default lsp4j launcher uses a cached thread pool executor](https://github.com/eclipse/lsp4j/blob/932cf512317e60723ecaf429f012071b1daa5e2a/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/Launcher.java#L67) when Xtext language server assumes that all requests come sequential, using a single thread executor eliminates the issue.

**Comment by cdietrich** [comment]
Interestingly I never saw this problem 
Can you elaborate what the steps are you do in vscode

**Comment by akosyakov** [comment]
I do the following several times before i get the exception:
1. Open file
2. Hover over the cross reference
3. Clock on the cross reference
4. Close files
I am not sure that it is reproducible without my language. Generally read requests should not load any resources but reuse resources loaded during the build.

**Comment by akosyakov** [comment]
Ok, my assumptions is wrong, the build is always done with a fresh resource set, so only resources which are required for the build is loaded. I don't think that the synchronized resource set is going to help, since proxies resolution still can happen in parallel.

**Comment by akosyakov** [comment]
[This PR](https://github.com/eclipse/xtext-core/pull/237) looks like a fix.

**Comment by cdietrich** [comment]
with open i file you mean "open a file in code or open a file within a opened folder in code?

hmmm i cannot reproduce this with my example however i dont get it to slow down hover fast enhough i think

**Comment by svenefftinge** [comment]
Yes, that PR is a fix that assumes all resources are loaded. However, this might not be a scalable solution, so it should be possible to disable it in which case we need to disallow concurrent read.

Since the change has too much impact I didn't merge it before 2.11.

**Comment by akosyakov** [comment]
fixed with https://github.com/eclipse/xtext-core/commit/1c2b7a49f33ecde7e5bd860644fff0fa9318ef3a
