### ISSUE TITLE
[LanguageServer] Provide DocumentHighlight Service (Mark Occurrences)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#27]

**Comment by cdietrich** [comment]
https://github.com/Microsoft/language-server-protocol/issues/32

**Comment by cdietrich** [comment]
https://github.com/TypeFox/ls-api/issues/40

**Comment by kittaakos** [comment]
I will look into this.

**Comment by cdietrich** [comment]
i hat a look at this and it looks good. is there anything that is still left to do?

**Comment by spoenemann** [comment]
I'd say it's done.
