### ISSUE TITLE
[Wizard] Broken Launch Configs

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#273]
The 2.11 Xtext Wizard created the launch config as

```
<stringAttribute key="org.eclipse.jdt.launching.JRE_CONTAINER" value="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/J2SE-1.8"/>
```
but i think it should be
```
<stringAttribute key="org.eclipse.jdt.launching.JRE_CONTAINER" value="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
```

**Comment by LorenzoBettini** [comment]
Yes, I agree, it should be JavaSE-1.8 as it is in the .classpath

**Comment by cdietrich** [comment]
![bug3](https://cloud.githubusercontent.com/assets/238736/22638773/a75c48d0-ec4a-11e6-86b0-f0c04ad67694.png)

**Comment by cdietrich** [comment]
Fixed with a31ea41

**Comment by spoenemann** [comment]
Can't we just remove the launch config? PDE can create one automatically with right-click &rarr; Run As &rarr; Eclipse Application

**Comment by cdietrich** [comment]
as i said: this is already fixed. i thought there were some discussions on the launch config before and we decided to keep
