### ISSUE TITLE
[Language Server] Syntax Highlighting Support

### ISSUE THREAD

**Issue by chetanladdha** [eclipse/xtext-core#283]
AFAIK, Xtext is not providing Syntax highlighting in a case of Language Server protocol.
As this is a very important feature for domain specific language, do we have any plan for providing syntax highlighting for Xtext generated LSP?

**Comment by cdietrich** [comment]
This is https://github.com/Microsoft/language-server-protocol/issues/18

**Comment by chetanladdha** [comment]
@cdietrich : Do you know any workaround by which I can get the Syntax highlighting working in Xtext based language server? Is there any way through which I can get the the List<SymbolInformation>?

**Comment by cdietrich** [comment]
Since this is. Client side thing you should look for how to do this on Che.

**Comment by cdietrich** [comment]
I don't know if Che supports the symbol lookup from language server protocol.

**Comment by chetanladdha** [comment]
Thanks for reply. I still have some problem in understanding:
1. Does it mean Microsoft/language-server-protocol#18 has bug in itself for syntax highlighting implementation?
2. Is there any enhancement request exist for supporting syntax highlighting in Xtext LSP?

**Comment by cdietrich** [comment]
no this means: Microsoft says Syntax Highlighting is a Client Side Thing so it is part of the Che / VSCode what ever plugin and not the LS itself.

As long as LSP does not support it and thus no client supports it ....

LSP4j has LanguageClientExtensions anyway which offers you a server to client push regarding coloring. Xtext Basically supports/Implements that (you need actually to bind it)

```
 def Class<? extends IColoringService> bindIColoringService() {
    	return ColoringServiceImpl;
    }
```

But as said before: if you dont have a client that understands that .....
