### ISSUE TITLE
[generator] Support Tracing in Code Generators

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-core#287]
We have a bit of infrastructure for tracing in core, but some important pieces are still burried in xbase. I'd like to add support for tracing for any language (not only xbase), by adding the missing pieces to core.

**Comment by cdietrich** [comment]
related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=474469 https://bugs.eclipse.org/bugs/show_bug.cgi?id=471147 https://bugs.eclipse.org/bugs/show_bug.cgi?id=448853
