### ISSUE TITLE
Unable to build complete xtext p2 locally

### ISSUE THREAD

**Issue by vgirishkumar** [eclipse/xtext-core#308]

**Comment by cdietrich** [comment]
Hi can you please give mote context what you mean by this

**Comment by vgirishkumar** [comment]
I mean, earlier with 2.8.4, i was able to download complete source code and build the p2 cache locally.
now the structure is completely different and i see target pointed to some location, which does not even exists

**Comment by cdietrich** [comment]
Which target do you mean. Did you have a look at the repo split. The repo split of course makes building a complete repo locally a pain like hell but that is a side effect you pay for having a bunch of split repos

**Comment by vgirishkumar** [comment]
I mean target is the maven locations specifying the plugins.

>but that is a side effect you pay for having a bunch of split repos
I dont understand this.

But let me put this way. I have a PR against xtext-core, so can i have a Private build, which i can use it as p2 cache

**Comment by cdietrich** [comment]
I don't get you point can you please give pointers to files

**Comment by vgirishkumar** [comment]
Ok my requirement is to build p2 repo of xtext locally. The reason is with slf4j and xtext reexporting org.apache.log4j(https://github.com/eclipse/xtext-core/pull/309). I am not able to do so because of repo split. can i have a private build just for the above change. It doesn't have to be merged

**Comment by cdietrich** [comment]
to you have an issue/bug for the slf/log4j problem filed? simply removing it from exports/uses clause might have some bad/unwanted side effects.

well there are actually mutiple components that do the build. first one there is xtext-core. if you call `./gradlew clean cleanGenerateXtext build createLocalMavenRepo -PuseJenkinsSnapshots=true -PcompileXtend=true --refresh-dependencies --continue` + `mvn -f releng --batch-mode --update-snapshots -Dmaven.repo.local=.m2/repository clean install` (see `Jenkinsfile`) then the xtext-core part will be built. for the complete part you need https://github.com/eclipse/xtext-umbrella/. there you can find `https://github.com/eclipse/xtext-umbrella/blob/master/releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target`. you can change it to include the locally built core repo.

**Comment by cdietrich** [comment]
@vgirishkumar what is the state of thos issue?

**Comment by cdietrich** [comment]
since no feedback from user i will close this for now
