### ISSUE TITLE
[Language Server] Formatting and hover is not working.

### ISSUE THREAD

**Issue by chetanladdha** [eclipse/xtext-core#311]
I have created simple Xtext Project and created Xtext LanguageServer and integrated with Visual Code and Che.  Default Formatting is not working in Visual code and Che. It's working as Eclipse plugin.
I also observed hover is not working.

I have tried with multiple examples but it's not working. Let me know if you want sample code where it is reproducible.

**Comment by cdietrich** [comment]
Can you please share a small exampe Xtext project and the vs code extension code you use

**Comment by cdietrich** [comment]
p.s. the default hover not to work is expected since there is no dummy line aka `Greeting World`

**Comment by cdietrich** [comment]
and regarding Formatting: make sure you use latest 0.1.x lsp4j version. (https://github.com/eclipse/xtext-core/issues/196) 

And: LSP uses IFormatter2 and it was a design by choice to do so (https://github.com/eclipse/xtext-core/issues/21 / https://github.com/eclipse/xtext-core/pull/54)
=> you need to implement it.

**Comment by chetanladdha** [comment]
Thanks for the comment related to Formatter. I will attempt that.

Meanwhile, https://github.com/chetanladdha/apamatrailProject/tree/master/Xtext_With_LSP/org.example.entities.Entities.parent here is the code 
and https://github.com/chetanladdha/apamatrailProject/tree/master/Xtext_With_LSP/languageserver-example_vscode is the vs code extension.

I have not got your hover related comment. Do you mean hover will not work except documentation hover?  I want exact same hover as eclipse, how to get it?

**Comment by cdietrich** [comment]
you dont implement a formatter2 => nothing will happen => works as designed
regarding hover => you need to customize `IEObjectDocumentationProvider` (e.g. subclass `MultiLineCommentDocumentationProvider`) or `org.eclipse.xtext.ide.server.hover.HoverService`

**Comment by chetanladdha** [comment]
Thanks for your comment.  I will try them.

Could you please describe why we need to do all these thigs? Can't Xtext's HoverService handle this kind of things at framework level itself? 
I was under the assumption that when Xtext LSP is compatible with Feature like Hover, formatting etc then we don't need to do anything like we don't do anything for autocompletion, error markers? Isn't this a bug/enhancement?

**Comment by cdietrich** [comment]
How does your formatting implementation look like?

**Comment by cdietrich** [comment]
And as I said both formatter and hover work fine if you understand what to implement and or to expect from the default impl
