### ISSUE TITLE
[Language Server] Rename Feature

### ISSUE THREAD

**Issue by chetanladdha** [eclipse/xtext-core#312]
I am really interested in rename feature which works in Xtext Eclipse.  I know current Xtext LSP doesn't support this feature OOTB.  Can someone describe how to support this feature in language server for our own language? Do we have any plan for this feature in near future?

**Comment by svenefftinge** [comment]
We have plans to reimplement the refactoring infrastructure in an Eclipse independent way. But I cannot provide a concrete delivery date yet.

**Comment by cdietrich** [comment]
@JanKoehnlein can we consider this fixed?

**Comment by JanKoehnlein** [comment]
I'd love to wait until https://github.com/eclipse/xtext-core/pull/523 is resolved. I'd have a look at that next week.

**Comment by JanKoehnlein** [comment]
Fixed
