### ISSUE TITLE
Enabling the customization of the org.eclipse.xtext.testing.validation.ValidationTestHelper.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-core#315]
The current implementation of the ValidationTestHelper class also accepts part of the issue messages and does not differentiate between the lower case and the upper case notation.
![validationtesthelper](https://cloud.githubusercontent.com/assets/20393472/24552033/3b1a6b70-1625-11e7-9a31-6d98e5ca13d2.png)
As a workaround I know that it is possible to provide a custom implementation of the ValidationHelper that's better tailored to our needs, but it may be useful to have that customization directly in the Xtext framework (e.g: introducting a boolean/enum parameter in the ValidationTestHelper class to configure the validation to be more strict/lenient).

**Comment by svenefftinge** [comment]
Yes, why not. Could you create a PR?

**Comment by miklossy** [comment]
Thanks for the quick reply! I will create a Pull Request.

**Comment by miklossy** [comment]
I think this issue could be closed, since the PR has been already merged into master.

**Comment by meysholdt** [comment]
agree
