### ISSUE TITLE
Fix Xtext tests

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#32]
New test failures after fixing #28, currently set to `@Ignore`:

org.eclipse.xtext.generator.grammarAccess.ParserTest.testInstantiate
```
org.eclipse.xtext.parser.ParseException: java.lang.IllegalStateException: Unresolved proxy http://www.eclipse.org/xtext/tests/grammarAccess/subpackage#////subsubpackage/AnotherType. Make sure the EPackage has been registered.
```

org.eclipse.xtext.mwe.UriBasedReaderTest.testTransitiveReferences (fails on server only)
```
java.io.FileNotFoundException: /var/jenkins_home/workspace/xtext-core/msp/testWorkflows/org.eclipse.xtext.tests/src/org/eclipse/xtext/mwe/importUriSubfolder/Start.importuritestlanguage (No such file or directory)
```

**Comment by cdietrich** [comment]
@spoenemann  looks like there was a migration issue with org.eclipse.xtext.xtext.generator.grammarAccess.FragmentFakingEcoreResource.calculateURIFragment(EPackage, StringBuilder, Set<EPackage>)

the append("//") should happen in only 3 else cases not 4

**Comment by cdietrich** [comment]
```
def private void calculateURIFragment(EPackage ePackage, StringBuilder result, Set<EPackage> visited) {
		if (!visited.add(ePackage)) {
			throw new IllegalStateException
		}
		if (ePackage.ESuperPackage !== null) {
			if (ePackage.eResource === ePackage.ESuperPackage.eResource) {
				calculateURIFragment(ePackage.ESuperPackage, result, visited)
				if (!ePackage.EClassifiers.empty) {
					if (result.length !== 0) {
						result.append(ePackage.name).append('/')
						return
					} else {
						result.append('//')
					}
				}
			} else {
				result.append('//')
			}
		} else {
			result.append('//')
		}
	}
```

**Comment by spoenemann** [comment]
Thanks. It's very good that migrating the test languages actually reveals bugs in the new generator (see also eclipse/xtext-core#33).

**Comment by spoenemann** [comment]
```
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_B FAILED
    org.junit.ComparisonFailure at SerializerTest.java:47
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_C FAILED
    org.junit.ComparisonFailure at SerializerTest.java:53
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_D FAILED
    org.junit.ComparisonFailure at SerializerTest.java:59
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_2_A_B_A_B FAILED
    org.junit.ComparisonFailure at SerializerTest.java:150
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_B_C FAILED
    org.junit.ComparisonFailure at SerializerTest.java:120
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_B_D FAILED
    org.junit.ComparisonFailure at SerializerTest.java:127
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_C_D FAILED
    org.junit.ComparisonFailure at SerializerTest.java:134
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_1_B_C_D FAILED
    org.junit.ComparisonFailure at SerializerTest.java:113
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testNoValueAssigned FAILED
    org.junit.ComparisonFailure at SerializerTest.java:35
org.eclipse.xtext.parser.unorderedGroups.SerializerTest > testSerialize_2_A_B_A_B_A_B FAILED
    org.junit.ComparisonFailure at SerializerTest.java:161
```

**Comment by cdietrich** [comment]
UriBasedReaderTest fails when the branch name contains a /

**Comment by cdietrich** [comment]
@spoenemann @meysholdt the workaround from eclipse/xtext-core#17 solves the serializer issues.
(using `UnorderedStrategy.SEQUENCE`)

**Comment by meysholdt** [comment]
that 'workaround' turns UnorderedGroups into regular Groups for the serializer. That defeats the intention of the tests, so it's not a solution here. Let's track the serializer tests with a dedicated Github issue.

**Comment by cdietrich** [comment]
@meysholdt can you tell how jenkins creates the xxxx%2Fyyyy folder when the branch name contains a /

**Comment by meysholdt** [comment]
I have not investigated that yet. Please file another issue for it and in case the URL is not computed by our own code, you might want to google quickly whether it's known Jenkins problem. 

Let's stay on-topic in this Github issue.

**Comment by spoenemann** [comment]
```
org.eclipse.xtext.parsetree.impl.CommentAssociationTest > testSerializeReplacement FAILED
    org.junit.ComparisonFailure at CommentAssociationTest.java:135

org.eclipse.xtext.parsetree.impl.CommentAssociationTest > testCommentsAtEndOfFile FAILED
    org.junit.ComparisonFailure at CommentAssociationTest.java:164
```

**Comment by spoenemann** [comment]
I'm not sure whether we should remove the parse tree reconstructor related tests or just adapt their expectations (they now run with the new serializer). For now I gather the failing tests here.
```
org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTest > testRefList2 FAILED
    org.junit.ComparisonFailure at HiddenTokensMergerTest.java:88
org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTest > testValueList1 FAILED
    org.junit.ComparisonFailure at HiddenTokensMergerTest.java:82
org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTest > testCommentable1 FAILED
    org.junit.ComparisonFailure at HiddenTokensMergerTest.java:55
org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTest > testCommentable2 FAILED
    org.junit.ComparisonFailure at HiddenTokensMergerTest.java:61
org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTest > testCommentable3 FAILED
    org.junit.ComparisonFailure at HiddenTokensMergerTest.java:67
org.eclipse.xtext.parsetree.reconstr.HiddenTokensMergerTest > testCommentable4 FAILED
    org.junit.ComparisonFailure at HiddenTokensMergerTest.java:76
org.eclipse.xtext.parsetree.reconstr.PartialSerializationTest > testSimpleSurroundComments2 FAILED
    org.junit.ComparisonFailure at PartialSerializationTest.java:47
org.eclipse.xtext.parsetree.reconstr.PartialSerializationTest > testSimpleSurroundComments3 FAILED
    org.junit.ComparisonFailure at PartialSerializationTest.java:54
org.eclipse.xtext.parsetree.reconstr.PartialSerializationTest > testSimple FAILED
    org.junit.ComparisonFailure at PartialSerializationTest.java:35
org.eclipse.xtext.parsetree.reconstr.SimpleReconstrTest > testLoop1 FAILED
    org.junit.ComparisonFailure at SimpleReconstrTest.java:225
org.eclipse.xtext.parsetree.reconstr.SimpleReconstrTest > testLoop2 FAILED
    org.junit.ComparisonFailure at SimpleReconstrTest.java:230
org.eclipse.xtext.parsetree.reconstr.SimpleReconstrTest > testLoop3 FAILED
    org.junit.ComparisonFailure at SimpleReconstrTest.java:235
org.eclipse.xtext.parsetree.reconstr.SimpleReconstrTest > testLoop4 FAILED
    org.junit.ComparisonFailure at SimpleReconstrTest.java:240
```

**Comment by meysholdt** [comment]
The PTC tests should run against the PTC, not the new serializer. 
If that's not feasible we can discuss deleting them. The new serializer has pretty good test coverage, I don't expect an improvement in terms of coverage if we move the tests over.

**Comment by cdietrich** [comment]
move the tests to extras?

**Comment by meysholdt** [comment]
the PTC tests? no. They have no business in 'extras' since the code-user-test is in 'core'.

**Comment by cdietrich** [comment]
well then we should live with the upstream dependency to the old generator

**Comment by cdietrich** [comment]
@spoenemann what do you think of https://github.com/eclipse/xtext-core/commit/fa84a99b5683f9bc3c5961478897636e462f0f19

**Comment by spoenemann** [comment]
If it fixes the issue I think it's good.

The PTC has been deprecated for a long time now. If we don't want to use the PTC tests for the new serializer as @meysholdt stated, we should delete them, since IMO supporting the PTC in the test languages would not be worth the effort. Keeping the dependency to the old generator is also not feasible, since eliminating that dependency was the main goal of the test language migration (see eclipse/xtext-core#28).

**Comment by cdietrich** [comment]
but why not move then?

**Comment by meysholdt** [comment]
because
1) the tests for bundle <foo> should be in bundle <foo>.tests and no where else. Leave alone another repository.
2) The new serializer does have good test coverage already. Adding the PTC tests does not improve test coverage. So I don't see the value of keeping the tests. Deleted code is good code :)

**Comment by meysholdt** [comment]
However, there may be classes of the PTC that are used outside of the PTC, such as 
org.eclipse.xtext.parsetree.reconstr.impl.NodeIterator
we must keep their tests

**Comment by cdietrich** [comment]
so we live with the old fragment and runtime being untested?

**Comment by spoenemann** [comment]
`org.eclipse.xtext.parsetree.reconstr.Serializer` has been deprecated in May 2014 and has not been changed since then. I could live with that class being untested.

**Comment by meysholdt** [comment]
maybe we can replace the PTC fragment with a dummy that generates nothing but an error which reminds people to use the new serializer. I think most people who have the PTC fragment in their workflow have it because the New Project Wizard put it there long time ago but they never really used the serializer. Otherwise they would have run in to one of these issues:
The PTC 
- has a terrible runtime complexity (execution time), 
- does not support parser rule parameters
- does not support grammar fragments
- does not support the new formatter
- IIRC has bad support for unordered groups
- IIRC has plenty of glitches when it's about considering the node model

**Comment by cdietrich** [comment]
well i have seen people using the old fragment to circumvent issues (e.g. taking forever) in the new one

**Comment by cdietrich** [comment]
so what i dont get i why dont we simply move the "generated" ParseTreeReconstructor to the test plugin and call/register the old serializers for the tests

**Comment by meysholdt** [comment]
because we just noticed that we'll need to invest time into maintaining this ancient code (the PTC) and we think it's a really bad investment of our time. Deleting it is far more appealing because it will allow us to move faster in the future. 

Obviously, we'll need to find a solution wich 
1) does not break binary compatibility of runtime artifacts (this excludes xtext.generator)
2) provides a smooth and intuitive migration path for source compatibility. A workflow log output such as "please do XYZ" is as smooth as it gets IMHO.

If there are performance issues in some cases with the new serializer, please file issues for them (if you haven't already done so) and indicate their importance. Also, well need to distinguish
1) runtime performance issues
3) workflow fragment performance issues. 
For (2) it is possible, if you didn't use it's the generated API, to simple use no serializer fragment at all. At runtime, the serializer will still be operational.

**Comment by cdietrich** [comment]
so then delete the tests and really reprecate the fragment

**Comment by spoenemann** [comment]
>org.eclipse.xtext.parsetree.impl.CommentAssociationTest > testSerializeReplacement FAILED
>    org.junit.ComparisonFailure at CommentAssociationTest.java:135

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=475457

**Comment by spoenemann** [comment]
The fragment is already deprecated. I removed the failing PTC tests. I created a separate issue for the serializer tests (#39).
