### ISSUE TITLE
Generated code for the `UriExtensions` is out-of-sync

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#323]
It seems one forgot to check-in the generated code for the `UriExtensions`. At least I am [missing] the `try-catch` block from the generated `.java` resource although it is [there] in the `.xtend` file.

One could also fix the whitespaces in the `.xtend` file.

If you think the generated code is just correct, please close this ticket.

[missing]: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/UriExtensions.java#L31
[there]: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend#L33

**Comment by kittaakos** [comment]
PR: https://github.com/eclipse/xtext-core/pull/324

**Comment by cdietrich** [comment]
Fixed with Xtext 2.12
