### ISSUE TITLE
Greedy dependencies in Xtext : can't prevent JDT installation

### ISSUE THREAD

**Issue by yanntm** [eclipse/xtext-core#345]
Hi,

org.eclipse.xtext has (optional, greedy) transitive dependencies to jdt.core. 
This means it's very difficult not to install jdt when deploying a DSL, even though it might not be needed at all.

This bug is discussed here : https://bugs.eclipse.org/bugs/show_bug.cgi?id=464344

I'd just like to revive this issue, which is still a problem for any RCP type of build.
I'm currently building a custom update site that prevents resolution of these optional dependencies as a workaround, but setting greedy false in the Manifest would really help much more for a provider of tools that use XText in their fabrication process. 

Thanks for the new separation of build-time vs runtime dependencies in the language plugins, that really helped cut some deps away already.

**Comment by cdietrich** [comment]
hi, which bundle/feature are you referring to?

**Comment by yanntm** [comment]
This is a screenshot of what dependencies I'm dragging in currently from org.eclipse.xtext 
![deps](https://cloud.githubusercontent.com/assets/15147867/26275669/61df5b4a-3d66-11e7-8c05-5053fe70616f.png)

It seems the problematic greedy flags are in https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/META-INF/MANIFEST.MF

thank you for the quick reply and for building Xtext in the first place, cool piece of software.

**Comment by cdietrich** [comment]
hmm i'd have expected to see the error from xtext.ui or something like that.

all the old xtend/xpand stuff should not be needed at all at runtime.
this is why i thought the wizard generates them as add. deps in build.properties nowadays.
i have no idea why we still do this this way.

but i am not sure what will explode if we remove the greedy there and on other places

**Comment by cdietrich** [comment]
p.s: what do you use to build your rcp. if you use tycho you may have a look at filters on target platforms https://wiki.eclipse.org/Tycho/Target_Platform#Filtering

**Comment by yanntm** [comment]
I don't actually build an RCP, I download minimal eclipse platform (25 megs) and install my "application" with command-line update eclipse from update site requests that cite eclipse/release and myDSL/last as update sites. This drags JDT and a bunch of gui stuff in, bloating my install.

The scenario is that I want to offer command-line usage of tools for my DSL, but I'm so deeply embedded in eclipse that it's simpler to build an application than any other scenario (it also lets me reuse my code base fully in cl scenario).
But currently, due to these greedy dependencies, despite not depending on any .ui or .ide in my .application plugin, I'm dragging 70 megs of plugins in which is much more than I need.

My current workaround idea involves building a custom update site that only carries mirrors of XText itself, but not of e.g. JDT and use that instead of eclipse/release update site. 
This is a workaround suggested here : 

But I don't like the solution that much, hence this RFE.

PS: Yes, I would be a bit worried about breaking things by brutally setting greedy false everywhere.

From  what I've seen, just cutting the critical greedy flag that drags org.eclipse.emf.mwe.utils in from org.eclipse.xtext would be enough to severe the most worrisome transitive chain of deps. 
My screenshot is on latest XText nightly-build, I believe in 2.11 the path through xtend.typesystem.emf was not there. But this one might need to be non-greedy as well (either in org.eclipse.xtext or in typesystem.emf). 
Cutting higher (close to org.eclipse.xtext) is probably preferable to setting false in a lot of places at once imo.

**Comment by yanntm** [comment]
just as feedback, my DSL now runs fine with this minimal set of plugins 
id="org.eclipse.xtext"
id="org.eclipse.xtext.xbase.lib"
id="org.eclipse.xtend.lib"
id="org.eclipse.xtend.lib.macro"
id="com.google.inject"
id="com.google.guava"

I've built a minimal update site XText light to serve my needs, for reference or if someone else wants to use it its here : https://github.com/yanntm/Xtext-Light

It leverages travis to build a minimal XText update site hosted here :  https://yanntm.github.io/Xtext-Light/
Currently aligned on 2.11. Since it's all on github/travis it could help someone running itno the same issues it's reproducible easily.

A nicer solution still would be to remove greedy flag please.

**Comment by yanntm** [comment]
Hi, 
my solutions are mostly falling flat, though I do get a leaner version with the update site approach.
But not having the normal eclipse update site selected breaks my headless app builds.

I could submit this as a pull request if that helps

best regards

**Comment by yanntm** [comment]
sorry had trouble signing the commit, can't do it from EGit unfortunately.

**Comment by cdietrich** [comment]
You should be actually able to sign off from eclipse https://wiki.eclipse.org/EGit/User_Guide/Commit#Signing_off_commits

**Comment by yanntm** [comment]
Hi, ok I kind of tried that, but it didn't work before I finally did it from command line on a linux box.

Concerning RCP scenario with tycho, your tip was good 
I'm using:
					<filters>
						
						<filter>
							<type>eclipse-plugin</type>
							<id>org.eclipse.jdt.core</id>
							<removeAll />
						</filter>
						
						
						<filter>
							<type>eclipse-plugin</type>
							<id>org.eclipse.xtend</id>
							<removeAll />
						</filter>
					</filters>

This removes the unwanted optional things due to a cascade of failing dependencies in them.

There still remains the plain eclipse update scenario, where any plugin depending on org.MyDSL (not ide or ui stuff) depends on o.e.xtext, thus brings in JDT and Xtend if you have "normal" update site configured.
If the dependency is just to use the generated EMF model or the parse/serialize/validate API we certainly don't need this.

**Comment by yanntm** [comment]
I left a greedy flag on org.eclipse.core.runtime, the only way I can see this not being available is if we are not within eclipse at all, but then greedy or not it would not be resolved.

**Comment by cdietrich** [comment]
fixed in 2.13
