### ISSUE TITLE
Encoding Test Fails on Windows from gradle

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#348]
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.eclipse.xtext.parser.encoding.EncodingTest.testSetup(EncodingTest.java:67)

**Comment by cdietrich** [comment]
this is caused by the encoding beeing windows-1252
should we set a encoding in gradle?

The test currently does
`assertTrue(Charset.defaultCharset().name().equals(UTF_8) || Charset.defaultCharset().name().equals(ISO_8859_1));` 

or is the user obliged to hande the prblem him/herself

**Comment by spoenemann** [comment]
Strange... why does the test make assertions about the default charset? Is that really necessary?

**Comment by cdietrich** [comment]
i dont know. maybe to prevent follow up problems?

**Comment by cdietrich** [comment]
I have deleted the Test => Problem "Solved"
