### ISSUE TITLE
Update to Mwe 2.9.1

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#355]
needs to be done in other components like xtext-extras, xtext-xtend, xtext-web, xtext-idea, xtext-umbrella as well. and the wizard needs to be changed

**Comment by kthoms** [comment]
I think this was it.

**Comment by cdietrich** [comment]
the wizard part for maven/gradle is missing

**Comment by kthoms** [comment]
ah ok, thx for the pointer

**Comment by kthoms** [comment]
Done.
