### ISSUE TITLE
DefaultGlobalScopeProvider must not rely on injected IResourceDescription.Manager

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-core#381]
The [DefaultGlobalScopeProvider](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/DefaultGlobalScopeProvider.java) uses an injected `IResourceDescription.Manager` for creating `IResourceDescriptions` in the method [getVisibleContainers(Resource)](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/DefaultGlobalScopeProvider.java#L65). IMO that's wrong, und because of the caching in [DefaultResourceDescriptionManager](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/DefaultResourceDescriptionManager.java#L59) that corrupted `IResourceDescriptions` may exist for longer.

In contrast, in [ClusteringBuilderState](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java) the resource description creation is done correctly by querying the correct `IResourceDescription.Manager`, see [here](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java#L231).

Hence, I suggest to replace the injected `descriptionManager` by one obtained via
```
@Inject
IResourceServiceProvider.Registry managerRegistry

managerRegistry.getResourceServiceProvider(uri).getResourceDescriptionManager()
```
and maybe use the injected one as default of no specific one can be found.

**Comment by cdietrich** [comment]
isnt DefaultGlobalScopeProvider language specific?

**Comment by sailingKieler** [comment]
It is I guess.
But when I've cross references to resources of other languages, the configs of those languages should be respected.

**Comment by cdietrich** [comment]
can you give an example of what you do.
each language configures its scoping

**Comment by sailingKieler** [comment]
Sure. Tomorrow ;-)

In may case the globalScopeProvider of lang A is asked to look something up in registered containers with a context resource of lang B.
Is that against the contract?

**Comment by cdietrich** [comment]
i think so. @svenefftinge @szarnekow do you know?

**Comment by sailingKieler** [comment]
I just talked to @meysholdt and we come to the conclusion that it is more appropriate to log a warning of wrong usage of the globalScopeProvider, as clients may have their own workarounds that might break.

**Comment by svenefftinge** [comment]
The containers are language specific and the requesting language need to make sure it sees what it wants to see. So the current code is correct and if the container manager of A doesn't find the resources of B you need to change it so it does. I suggest to close this.

**Comment by cdietrich** [comment]
so let us close this issue
