### ISSUE TITLE
Improve updating of textual changes after modifications of the AST

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#387]
The most convenient way to implement refactorings and quick fixes is to programmatically modify the EMF model. Xtext should take care of the rest:
* update the textual representation (documents) of the EMF model.
* execute the formatter locally as needed
* update cross references that point to the modified part of the EMF model

Requirements:
* updates to the documents should be as minimal as possible
* the implementation should be as robust as possible regarding syntax errors and broken models.
* handle changes that span multiple EMF resources, both XtextResources and XMIResources.

**Comment by cdietrich** [comment]
some changes were done. will close as nothing more planned
