### ISSUE TITLE
[textRegionAccess] Allow to create semantic regions for hidden nodes

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse/xtext-core#408]
`NodeModelBasedRegionAccessBuilder` lacks protected getters/setter for state, which would make it easier in a subclass to create semantic regions for hidden nodes.

**Comment by kthoms** [comment]
Merged.

**Comment by AlexTugarev** [comment]
PR https://github.com/eclipse/xtext-core/pull/410 to fix missing import.
