### ISSUE TITLE
o.e.xtext.ide depends on Equinox

### ISSUE THREAD

**Issue by sjka** [eclipse/xtext-core#446]
I'm currently trying to get LSP support into Eclipse SmartHome (eclipse/smarthome#4148). 
However, as it turned out, the `org.eclipse.xtext.ide` has a "require bundle" dependency to `org.eclipse.core.runtime` which in turn drags the whole equinox enchilada in. As it claims to provide "Platform-independent language support.", this is somewhat surprising.

There was a related issue for the xtext core in bugzilla (https://bugs.eclipse.org/bugs/show_bug.cgi?id=434490). Would it be possible to factor out the eclipse specific stuff into an optional eclipse-related bundle? Or at least make this stuff optional?

**Comment by cdietrich** [comment]
it uses org.eclipse.core.runtime.IProgressMonitor /NullProgressMonitor from equinox common but this change wouldnt help you neither correct?

and org.eclipse.xtext has the same dependency (although its optional)

**Comment by sjka** [comment]
> from equinox common 

looking at its dependencies: nope 😄 

> and org.eclipse.xtext has the same dependency (although its optional)

An optional dependency is perfectly fine - as long as the stuff really doesn't fail without it. Our use-case is to run an embedded language server, so no Eclipse extension points are registered. Therefore I assume we should be reasonably safe...

**Comment by cdietrich** [comment]
no i mean: replacing that dependency with equinox common: will it help you or not?
or is that  == equinox enchilada

**Comment by sjka** [comment]
No, it won't help:

o.e.equinox.commons imports

```
# Bad:
org.eclipse.equinox.log;version="[1.0,2.0)",
org.eclipse.osgi.framework.log;version="[1.1, 2.0)"
org.eclipse.osgi.service.datalocation
org.eclipse.osgi.service.debug
org.eclipse.osgi.service.localization
org.eclipse.osgi.service.urlconversion
org.eclipse.osgi.util

# Good:
org.osgi.framework
org.osgi.service.log;version="[1.3.0, 2.0)"
org.osgi.service.packageadmin
org.osgi.service.url
org.osgi.util.tracker
```

**Comment by cdietrich** [comment]
but org.eclipse.xtext has the same required dependency

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/blob/077b26c5caad58f0e07b35e7001415b8db93bc33/org.eclipse.xtext/META-INF/MANIFEST.MF#L106

**Comment by sjka** [comment]
I just learned that there is the o.e.equinox.supplement bundle which fulfills all those requirements if o.e.equinox.common has to run on another framework. 
With this knowledge a dependency to o.e.equinox.common indeed would help.

**Comment by maggu2810** [comment]
Hi @cdietrich,
can you explain me why you use Require-Bundle instead of Import-Package at all?
Shouldn't be the "import package" directive be preferred to not depend on the bundle that adds the implementation at all?

**Comment by cdietrich** [comment]
i havo no idea. i just try to be consitent to xtext-core

**Comment by cdietrich** [comment]
doesnt the discussion in the attached bugziilla give any clues

**Comment by cdietrich** [comment]
fixed in xtext 2.13

**Comment by sjka** [comment]
Wow, that was quick. Thanks!

What is the timeline for 2.13? Or rather: any chance to get this change in a more-or-less official build (i.e. a p2 repository that can be referenced) before the  ~~pluto~~ the-other-word-with-"p"-release?

**Comment by cdietrich** [comment]
good question does the xtext snapshot repo already contain 2.13? have no p2 browser to look here

**Comment by sjka** [comment]
@svenefftinge do you already have a plan? Will there be a 2.12.1 bugfix release? Or for what timeframe is 2.13 scheduled otherwise?

**Comment by kthoms** [comment]
Next release is 2.13. Official release date is not terminated yet.

**Comment by svenefftinge** [comment]
We try to get it out before End of October.
