### ISSUE TITLE
UriExtensionsTest fails on windows

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#459]
org.junit.ComparisonFailure: expected:<[file://]/dir/name.ext> but was:<[]/dir/name.ext>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.xtext.ide.tests.server.UriExtensionsTest.testFileUriConversion(UriExtensionsTest.java:204)

**Comment by kittaakos** [comment]
I can look into this.

**Comment by cdietrich** [comment]
Would be nice to know what is needed on windows to get nice runtime behavior 
Maybe we need some integration tests.
Or do we already have

**Comment by kittaakos** [comment]
I have to admit, I am a bit surprised about the Windows test failure, because I have checked out the branch with the changes yesterday and run the gradle build from termina on  Windowsl. Anyway, I try to reproduce it first.

**Comment by kittaakos** [comment]
I can confim it.
