### ISSUE TITLE
PartialSerializerTest / ChangeSerializer*Test / FileAwareTestLanguageImportTest / IndentationAwareCompletionPrefixProviderTest fail on windows

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#460]
FileAwareTestLanguageImportTest. testMoveIntoLocalPackage
FileAwareTestLanguageImportTest. testMoveToNewPackage
FileAwareTestLanguageImportTest. testNestedPackage
FileAwareTestLanguageImportTest. testRenameGlobal1
IndentationAwareCompletionPrefixProviderTest. testLastCompleteNode_4_0
IndentationAwareCompletionPrefixProviderTest. testLastCompleteNode_4_0c
IndentationAwareCompletionPrefixProviderTest. testLastCompleteNode_4_0d
IndentationAwareCompletionPrefixProviderTest. testLastCompleteNode_6_0
IndentationAwareCompletionPrefixProviderTest. testLastCompleteNode_6_0b
IndentationAwareCompletionPrefixProviderTest. testLastCompleteNode_7_0
ChangeSerializerTest. testDeleteChild
ChangeSerializerTest. testDeleteTwoChildren
ChangeSerializerTest. testInsertBeforeComment
ChangeSerializerTest. testInsertOneChild
ChangeSerializerTest. testInsertTwoChild
ChangeSerializerTest. testRenameGlobal1
ChangeSerializerTest. testRenameLocal
ChangeSerializerTest. testResourceURIChange
ChangeSerializerTest. testSimple
ChangeSerializerTest. testTwoChildren
ChangeSerializerWithEmfTest. testRefFromXML
ChangeSerializerWithEmfTest. testRefToXML
ChangeSerializerWithImports. testRenameGlobal1
PartialSerializerTest. testMandatoryChildChange
PartialSerializerTest. testMandatoryValueChange
PartialSerializerTest. testMoveInList1
PartialSerializerTest. testOptionalChildChange
PartialSerializerTest. testOptionalChildInsert
PartialSerializerTest. testOptionalChildListInsertIntoEmpty
PartialSerializerTest. testOptionalChildListInsertIntoEmpty2
PartialSerializerTest. testOptionalChildListInsertIntoEndOne
PartialSerializerTest. testOptionalChildListInsertIntoEndThree
PartialSerializerTest. testOptionalChildListInsertIntoEndTwo
PartialSerializerTest. testOptionalChildListInsertIntoFirst
PartialSerializerTest. testOptionalChildListInsertIntoMiddle
PartialSerializerTest. testOptionalChildRemove
PartialSerializerTest. testOptionalChildRemoveListAllOne
PartialSerializerTest. testOptionalChildRemoveListAllTwo
PartialSerializerTest. testOptionalChildRemoveListFirstTwo
PartialSerializerTest. testOptionalChildRemoveListLastTwo
PartialSerializerTest. testOptionalChildRemoveListMiddleTwo
PartialSerializerTest. testOptionalValueChange
PartialSerializerTest. testOptionalValueInsert
PartialSerializerTest. testOptionalValueRemove

**Comment by cdietrich** [comment]
maybe

```
	def void ===(Collection<IEmfResourceChange> actual, CharSequence expected) {
		val actualString = new TextDocumentChangeToString().add(actual).toString
		Assert.assertEquals(expected.toString.trim.replaceAll("\r\n","\n"), actualString.trim.replaceAll("\r\n","\n"))
	}

	def void ===(ITextRegionAccess actual, CharSequence expected) {
		val actualString = new TextRegionAccessToString().withRegionAccess(actual).hideColumnExplanation().toString
		Assert.assertEquals(expected.toString.trim.replaceAll("\r\n","\n"), actualString.trim.replaceAll("\r\n","\n"))
	}
	def void +=(InMemoryURIHandler handler, Pair<String, String> file) {
		val f = handler.getInMemoryFile(URI.createURI(file.key))
		f.contents = file.value.replaceAll("\r\n","\n").bytes
		f.exists = true
	}
```

does the trick

cc @meysholdt

**Comment by cdietrich** [comment]
Unfortunately the same fix does not work on FileAwareTestLanguageImportTest

**Comment by cdietrich** [comment]
and i am not sure why we have the formatter preferences and ILineSeparatorInformation

**Comment by kittaakos** [comment]
The problem is in the [TextDocumentChangeToString](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/debug/TextDocumentChangeToString.java#L52;), right? Is it allowed to always use `"\n"`?

**Comment by kittaakos** [comment]
Also when we join the results.

**Comment by cdietrich** [comment]
I have no idea this is why I need somebody with insights in the serializer formatter stuff

**Comment by cdietrich** [comment]
so what strikes me is the strategy to tackle this problems

(1) make the inputs and behaviour the same one win and linux/mac and make sure result comparison works
(2) find a strategy to make a operating system dependent result ist correct computation

**Comment by cdietrich** [comment]
org.eclipse.xtext.parser.indentation.NodeModelTest affected as well

**Comment by cdietrich** [comment]
+ RegionAccessBuilderTest

**Comment by cdietrich** [comment]
@meysholdt @JanKoehnlein can you please comment on how to deal with the non indention tests

**Comment by cdietrich** [comment]
cc @svenefftinge how to fix these issue in test?

**Comment by cdietrich** [comment]
cc @meysholdt

**Comment by cdietrich** [comment]
unfortunately still open

**Comment by meysholdt** [comment]
I'll take a look
