### ISSUE TITLE
[Tracing] Allow to specify UseForDebugging

### ISSUE THREAD

**Issue by NDuemmel** [eclipse/xtext-core#467]
org.eclipse.xtext.generator.trace.node.GeneratorNodeProcessor.doProcess(TraceNode, Context) sets useForDebugging to false. active annotations dont offer to customize this. (#467)

Hi,

I have written a generator following this example: [](https://typefox.io/generate-traced-code-with-xtext
)
The issue is that the attribute useForDebugging for TraceRegions is always set to false, and there seems to be now way to change it. 

In the attachments you can see the difference in the trace files generated by xbase and my generator.
Regions with useForDebugging set to true have the D marker next to them.

![xbase_generated_trace](https://user-images.githubusercontent.com/20279179/30734874-48b36e44-9f7d-11e7-90b1-8a31d3422bc8.png)

![my_generated_trace](https://user-images.githubusercontent.com/20279179/30734876-48d978be-9f7d-11e7-9603-d91e70170255.png)

The code shows an excerpt from my generator.
`
override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val program = resource.contents.head as Program

		if (program !== null) {
			val programName = resource.URI.lastSegment.nameWithoutExtension.toFirstUpper

			AthenaUtilGenerator.generateUtilFile(resource, fsa, context)
			TurtleUtilGenerator.generateUtilFile(resource, fsa, context)

			fsa.generateTracedFile("generated/" + programName + ".java", program, '''
				package generated;
				
				import java.util.ArrayList;
				import java.util.Arrays;
				
				/*
				* Generated Java file, do not modify it!!!
				*/
				
				@SuppressWarnings("all")
				public class «programName» {
					static AthenaUtil util = new AthenaUtil();
					
					«FOR typeDec : program.typeDeclarations»
						«IF typeDec instanceof Composition»
							«fsa.generateTracedFile("generated/" + typeDec.name + ".java", program, '''
								package generated;
								/*
								* Generated Java file, do not modify it!!!
								*/
								public class «typeDec.name» {
									«FOR attr : (typeDec as Composition).attributes»
									«attr.generateAttribute»
									«ENDFOR»
								}
							''')»
						«ENDIF»
						«IF typeDec instanceof Enumeration»
							«fsa.generateTracedFile("generated/" + typeDec.name + ".java", program, '''
								package generated;
								/*
								* Generated Java file, do not modify it!!!
								*/
								public enum «typeDec.name» {
									«FOR value : (typeDec as Enumeration).values»
										«value.name.toUpperCase»
										«IF !(typeDec as Enumeration).values.get((typeDec as Enumeration).values.size-1).equals(value)», «ENDIF»
									«ENDFOR»
								}
							''')»
						«ENDIF»
					«ENDFOR»
					
					«FOR op : program.operations»
						«op.generateOperation»
					«ENDFOR»
					
					«IF program.mainBlock !== null»
						«program.mainBlock.generateMainMethod»
					«ENDIF»
				}
				
			''')
		}
	}

	@Traced def private generateOperation(Operation op) {
		'''
			«op.generateMethodSignature»{
				«FOR s : op.block.statements»
					«s.generateStatement»
				«ENDFOR»			
			}
		'''
	}

	def private generateStatement(Statement s) {
		val n = s.trace
		switch s {
			VariableDeclaration: {
				s.generateVariableDeclaration(n)
				n.append(";")
			}
			Assignment: {
				s.generateAssignment(n)
				n.append(";")
			}
			OperationCall: {
				s.generateOperationCall(n)
				n.append(";")
			}
			Conditional: {
				s.generateConditional(n)
			}
			WhileLoop: {
				s.generateWhileLoop(n)
			}
			ForEachLoop: {
				s.generateForEachLoop(n)
			}
			Return: {
				n.append("return ")
				s.expression.generateExpression(n)
				n.append(";")
			}
		}
		return n
	}
`

**Comment by cdietrich** [comment]
@meysholdt @svenefftinge @spoenemann any hints on how to best solved this?

**Comment by cdietrich** [comment]
@NDuemmel if you want to play alpha-tester: http://services.typefox.io/open-source/jenkins/job/xtext-umbrella/job/cd_issue467/lastSuccessfulBuild/artifact/build/p2-repository/

there is now `@Traced(useForDebugging=true)` and you can call the `_`methods with debug flag as well `_name(true)`

**Comment by cdietrich** [comment]
@NDuemmel would be nice if you could finalize this soon to make sure it gets part of the 2.13 release and supports everything you need

**Comment by NDuemmel** [comment]
First of all thank you for the quick fix.
I have tried it and it works, the D flags are present now.
However it seems I now need to rewrite my generator, so that the DSL statements get the @Traced(useForDebugging=true) annotation in order to get correct smap data.
I will look into it tomorrow.

**Comment by cdietrich** [comment]
depends on how you wrote your generator i think

**Comment by NDuemmel** [comment]
I have changed the generator so that statements have the @Traced(useForDebugging=true) annotation, and now correct smap data is generated as far as I can see. For now I've tested it only with variable declarations.

Placing a breakpoint in Java code and pressing debug now shows my DSL code with the correct line. 

Thank you very much!

P.S.: Here is what my generator looks like now:
`	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val program = resource.contents.head as Program

		if (program !== null) {
			val programName = resource.URI.lastSegment.nameWithoutExtension.toFirstUpper

			AthenaUtilGenerator.generateUtilFile(resource, fsa, context)
			TurtleUtilGenerator.generateUtilFile(resource, fsa, context)

			fsa.generateTracedFile("generated/" + programName + ".java", program, '''
				package generated;
				
				@SuppressWarnings("all")
				public class «programName» {
					«IF program.mainBlock !== null»
						«program.mainBlock.generateMainMethod»
					«ENDIF»
				}				
			''')
		}
	}

	@Traced def private generateMainMethod(Block block) {
		'''
			public static void main(String[] args){
				«FOR s : block.statements»
					«s.generateStatement»
				«ENDFOR»
			}
		'''
	}

	def private generateStatement(Statement s) {
		switch s {
			VariableDeclaration: {
				s.generateVariableDeclaration
			}
		}
	}

	@Traced(useForDebugging=true) def private generateVariableDeclaration(VariableDeclaration s) {
		'''
			«s.type.generateType» «s.vars.get(0).name» = 0;
		'''		
	}
`

**Comment by cdietrich** [comment]
ok so i assume we are good enhough to release this in 2.13

**Comment by cdietrich** [comment]
Fixed in Xtext 2.13
