### ISSUE TITLE
Eliminate error marker on XtextValidationTest.ecore

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#47]
The file `XtextValidationTest.ecore` in org.eclipse.xtext.tests is marked with an error because of the `classpath` URIs contained there. The error should be eliminated.

**Comment by cdietrich** [comment]
isnt the intention of the test to test the classpath uris?

**Comment by spoenemann** [comment]
Yes, but it would be nice to get rid of the error marker. It pollutes the workspace.

**Comment by cdietrich** [comment]
@spoenemann i could modify the test and use a modified classloader to provide this ecore. what do you think?

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-core/tree/cd_issue47 to get an idea

**Comment by spoenemann** [comment]
If the test still covers the same functionality, it's ok from my side.

Just an idea for a simpler solution: Move the ecore file to an Xtend rich string, write it out just before the test is run, and delete it afterwards?

**Comment by cdietrich** [comment]
i'll have a look

**Comment by kthoms** [comment]
Tests are failing:
- XtextValidationTest#testBug322875_01
- XtextValidationTest#testBug322875_01b
