### ISSUE TITLE
Support EMF's ResourceLocators in XtextResourceSet

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/xtext-core#476]
Since release 2.8 EMF supports the concept of ResourceLocators (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=367569 and especially https://bugs.eclipse.org/bugs/show_bug.cgi?id=367569#c7 for details). It would be nice if XtextResourceSet could leverage these.

At the moment this doesn't seem to be possible, because XtextResourceSet#getResource(URI, boolean) only delegates to the super class when there is getURIResourceMap() returns null:
https://github.com/eclipse/xtext-core/blob/c1014a09722b04352b06706d04419288405b92e6/org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResourceSet.java#L235-L236

But if getURIResourceMap() returns null there are problems with ResourcesList#doClear():

https://github.com/eclipse/xtext-core/blob/c1014a09722b04352b06706d04419288405b92e6/org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResourceSet.java#L176-L182

I suspect a lot of the URI mapping / caching logic could be simplified by leveraging EMF's ResourceLocators.

**Comment by cdietrich** [comment]
Fixed in 2.14
