### ISSUE TITLE
Determine Fate of ConcreteSyntaxValidator

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#48]
The ConcreteSyntaxValidator is intended to determine whether an EMF model can be serialized or not. The CSV was also intended to provide better error messages than the serializer does. The idea was to run the CSV before serialization. The CSV was able the fulfill these goals more or less with the old serializer, the parse tree constructor.

Today, and when working with the new serializer, however, the CSV
- does not produce better error messages
- is functionally incomplete, since it doesn't support assigned actions, parser rule fragments and parser rule parameters.
- sometimes produces false positives

In consideration of this I can say that:
- There is no value in running the CSV before serialization
- There may still be the use case to determine if a model can be serialized without actually serializing it. For example, in a (graphical) model editor to detect quickly if the user has made a mistake that would prevent him/her from saving the model.

Proposed solution: Exchange the implementation of the CSV to basically a stripped-down version of the serializer. The CSV would only run the SematicSequencer and use a null-impl for the SequenceAcceptor. This would be faster than running the serializer itself, because the serializer runs the SemanticSequencer, the the SyntacticSequencer, the HiddenTokenSequencer and the formatter.

**Comment by meysholdt** [comment]
won't fix: https://bugs.eclipse.org/bugs/show_bug.cgi?id=324297

**Comment by meysholdt** [comment]
won't fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=341155

**Comment by svenefftinge** [comment]
sounds good to me

**Comment by cdietrich** [comment]
i will close as wontfix
