### ISSUE TITLE
Improve performance of ResourceStorageLoadable

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/xtext-core#481]
I ran some primitive performance tests and noticed that `ResourceStorageLoadable` is rather slow in loading the binary models. Experiments indicate that by wrapping the `ZipInputStream` in a `BufferedInputStream` inside `loadEntries()` before passing it to the `readXyz()` methods the performance is improved by quite a bit (around 4x on MyMachine(tm)).

https://github.com/eclipse/xtext-core/blob/25e2d9d3816077db66d53ff1a17b3ae2c2e4b43e/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.xtend#L52-L63

**Comment by kthoms** [comment]
Could you prepare a test case with zipped models of some testing language, large enough to see an effect?

**Comment by knutwannheden** [comment]
I need to set my environment up for this. But tests show that on MyOtherMachine(tm) I also notice a rough 4x speed improvement when using a BufferedInputStream. Here is a test case I added to `org.eclipse.xtend.core.tests.resource.ResourceStorageTest`:

```xtend
	@Test def void testLoadPerformance() {
		val contents = CharStreams.toString(new FileReader('../../xtext-core/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend'))
		val file = file(contents)
		
		val bout = new ByteArrayOutputStream;
		(resourceStorageFacade as ResourceStorageFacade).storeNodeModel = true
		resourceStorageFacade.createResourceStorageWritable(bout).writeResource(file.eResource as StorageAwareResource)
		
		val resource = file.eResource.resourceSet.createResource(URI.createURI("synthetic:/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend")) as StorageAwareResource
		// set a synthetic converter so we can obtain the text by the URI
		val converter = new InMemoryURIConverter()
		resource.resourceSet.URIConverter = converter
		
		file.eResource.resourceSet.resources += resource;
		
		Stopwatches.enabled = true
		
		for (var i = 0; i < 20; i++) {
			val in = resourceStorageFacade.createResourceStorageLoadable(new ByteArrayInputStream(bout.toByteArray))
			converter.addModel(resource.URI.toString, contents)
			resource.loadFromStorage(in)
			resource.unload
		}

		System.out.println(Stopwatches.printableStopwatchData)
		Stopwatches.resetAll
	}
```

**Comment by cdietrich** [comment]
do we have some xtend performance tests that cover the resource storage facade @szarnekow ?

**Comment by knutwannheden** [comment]
BTW, same 4x improvement in this [SO question](https://stackoverflow.com/questions/4438085/seeking-out-the-optimum-size-for-bufferedinputstream-in-java). The problem seems to be that if the DataInputStream sits directly on top the ZipInputStream then only very small amounts of data will be decompressed at the time, while processing larger chunks appears to be way more efficient.

From my experience using the BufferedInputStream's default buffer size of 8 KiB works just fine. And this should also be applied to `BatchLinkableResourceStorageLoadable#readAssociationsAdapter()` (using ObjectInputStream rather than DataInputStream).

I will try to create two corresponding PRs.

**Comment by cdietrich** [comment]
Fixed in 2.13

**Comment by cdietrich** [comment]
on my machines i see an inprovement of 30% only but this is still significant

**Comment by knutwannheden** [comment]
@cdietrich Strange. Did you measure that using this primitive performance test I showed? Adding some warmup iterations to that I would often measure up to 7x improvement. I wonder why the big discrepancy?

**Comment by cdietrich** [comment]
no i measured in our production environment.

**Comment by knutwannheden** [comment]
OK. But were the measurements you compared also those of the "Loading from storage" task measured by `Stopwatches`? How much performance is increased for larger grained tasks as e.g. incremental builds I have no idea about. Probably not very much...

**Comment by cdietrich** [comment]
no i measured with yourkit. its the loadResource method

**Comment by cdietrich** [comment]
with your test i see a speedup of 300%

**Comment by knutwannheden** [comment]
OK. Thanks for the clarification.

Measurements in YourKit often surprise me a bit, especially when sampling. I have in the past often got strange results for native method calls and also it doesn't seem like YourKit consistently measures all native blocking I/O calls using wall time, some common ones appear to be missing (i.e. measured using CPU time).
