### ISSUE TITLE
[releng] add missing @since tags to new ChangeSerializer classes

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-core#489]

**Comment by szarnekow** [comment]
Some more JavaDoc on the methods and interfaces in the new API/SPI would be great, too.

**Comment by cdietrich** [comment]
`@since` still missing

**Comment by cdietrich** [comment]
Moved to 2.15

**Comment by cdietrich** [comment]
Moved to 2.16

**Comment by cdietrich** [comment]
Moved to 2.18

**Comment by cdietrich** [comment]
Moved to 2.19

**Comment by miklossy** [comment]
Based on the Git history and on the [blog post](https://www.typefox.io/blog/xtext-2-13-0-released-semantic-editing-made-easy) I find out that this feature has been added to Xtext 2.13.

**Comment by miklossy** [comment]
Fixed in 2.22.
