### ISSUE TITLE
org.eclipse.xtext.ide.server.rename not exported

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#498]

**Comment by cdietrich** [comment]
@JanKoehnlein @meysholdt please have a look

**Comment by kthoms** [comment]
If this package becomes public API, consider to mark elements `@Beta`.

If not, make sure that new projects don't use this API by default.

**Comment by cdietrich** [comment]
There is other ide stuff not exported as well
So bad for customization

@svenefftinge what is the policy here

**Comment by cdietrich** [comment]
Problem is without export wizard creates bad code

**Comment by kthoms** [comment]
Sounds to me that it should be an opt-in option to the generator. If users would really like to use this new API they can define access rules.

**Comment by szarnekow** [comment]
In the past we exported new packages as internal in many cases.

**Comment by JanKoehnlein** [comment]
https://github.com/eclipse/xtext-core/pull/502

**Comment by JanKoehnlein** [comment]
We may have overlooked that because we usually don't develop language servers as PDE plug-ins. Of course, generating broken code is a no go.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/commit/3ffea25e435223d2498f6981920ff466fcc41a77
