### ISSUE TITLE
[gradle] ignore optional problems attribute for source folders

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-core#5]
Eclipse supports ignoring optional warning per source folder:

in .classpath:

```
<classpathentry kind="src" path="emf-gen">
    <attributes>
        <attribute name="ignore_optional_problems" value="true"/>
        <attribute name="FROM_GRADLE_MODEL" value="true"/>
    </attributes>
</classpathentry>
```

It's a very helpful eclipse feature and should be used for *-gen src folders or at least be configurable in gradle build file.

**Comment by spoenemann** [comment]
@kthoms Changing the `.classpath` files directly is problematic if someone reruns the Gradle import wizard, which has generated the current version of those files. It would be better to add this option through the Gradle build files, if that's not too complicated.

**Comment by kthoms** [comment]
Any pointer where this has been done before? I don't know yet how to achieve that.

**Comment by cdietrich** [comment]
maybe @oehme can help with this. is https://docs.gradle.org/current/userguide/eclipse_plugin.html used in this case as well? it allows to "Partial overwrite of existing content" if i read the docs correct that could be used in this case

**Comment by oehme** [comment]
See the Buildship 1.0.18 release notes for a snippet:
https://discuss.gradle.org/t/buildship-1-0-18-is-now-available/19012

2016-10-06 21:24 GMT+02:00 Christian Dietrich <notifications@github.com>:

**Comment by kthoms** [comment]
Thx, I'll try that.

**Comment by cdietrich** [comment]
@kthoms is this still on your worklist?

**Comment by kthoms** [comment]
Yes, but has to wait after EclipseCon

**Comment by kthoms** [comment]
@oehme Sorry for asking noob questions.
I have tried now to add the snippet you mentioned. It had no effect. I tried to add it for testing on eclipse/xtext-lib into `gradle/eclipse-project-layout.gradle`(I felt that this should be the right place). Then I tried it also in the subprojects section in the parent build.gradle and also in the subproject itself. All without the desired effect.
Then I created a sample gradle project, applied it to there, and then it worked.
What am I missing?

**Comment by oehme** [comment]
@kthoms It's Gradle 3.0+. As far as I recall Xtext is still on 2.14, so that won't work until you upgrade.

**Comment by kthoms** [comment]
Sounds indeed as if this would be the reason. Would it make sense to upgrade Xtext's build to 3.x? How about Buildship?

**Comment by oehme** [comment]
The latest 2.0 milestone supports the new composite builds, so once you have that in place upgrading would be a good idea.

**Comment by cdietrich** [comment]
we have it in place anyway cause we use the milestone update site @kthoms

**Comment by spoenemann** [comment]
Updating to Gradle 3.2 sounds good, I'll check it out.

**Comment by cdietrich** [comment]
@kthoms  adding the following snippet to `gradle/eclipse-project-layout.gradle` looks promising. @oehme what do you think?
```
eclipse {
	classpath {
	  file {
			whenMerged {
				entries.each {
					source ->
					if (source.kind == 'src' && source.path.endsWith('-gen')) {
						source.entryAttributes['ignore_optional_problems'] = 'true'
					}
					
				}
			}
		}
	}
}
```

**Comment by kthoms** [comment]
Yes, this works in principle. Until now we did not exclude optional problems on xtend-gen, so we have to add ` && !source.path.equals('xtend-gen')` to the condition.

I will now update my PRs.

**Comment by cdietrich** [comment]
@dhuebner what do you think?

**Comment by dhuebner** [comment]
@cdietrich Looks good to me. Looking forward to trying it out. Additional question: Why the additional slash for the JRE_CONTAINER? Will other have this as well?

**Comment by cdietrich** [comment]
this is buildship. see discussion in slack

**Comment by kthoms** [comment]
This is how buildship generates the .classpath file on when importing the parent as Gradle project.

**Comment by dhuebner** [comment]
If it works 👍
