### ISSUE TITLE
Enabling formatter2 autowrap whenever possible

### ISSUE THREAD

**Issue by l-wi** [eclipse/xtext-core#505]
Hi,

We would like to enable autowrapping inside our DSL whenever the line becomes longer than lets say 120 characters (formatter2 API; xtext 2.12). The DSL element behind which we linebreak does not matter in our case.

For that we are currently using the following code in the first format call of the formatter in question:
  ```
  val regions = textRegionAccess.regionForRootEObject.allSemanticRegions;
    regions.forEach [
        it.append[autowrap]
    ]
```

And we override the initialize method to set the desired line width:
```
override void initalize(FormatterRequest request) {
        val values = new MapBasedPreferenceValues
        values.put(FormatterPreferenceKeys.maxLineWidth, 120)
        request.preferences = values

        super.initalize(request)

}
```

Yet, this approach becomes slow with larger DSL files (900 lines; 10200 semantic regions).
Is there an easier / faster way to archieve the desired behavior?

_(This is a copy of a question asked on SO as it was recommended to do so)_
_see:_  [this post](https://stackoverflow.com/questions/46665710/enabling-formatter2-autowrap-whenever-possible)

**Comment by meysholdt** [comment]
hi @l-wi,

you're using the right approach to enable autowrap for all hidden regions.

The performance problem has very likely been fixed in https://github.com/eclipse/xtext-core/commit/c1014a09722b04352b06706d04419288405b92e6.

If you can it would be great if you could measure again with a nightly build of Xtext 2.13. or with Xtext 2.13.RC1 that we want to release today.

regards,
  Moritz

**Comment by l-wi** [comment]
I just tested formatting with the nightly build (2.13.0.v20171011-248). Formatting is now almost instantaneous, reducing a lag of 6-7 seconds to 1-2 seconds.

So it seems that our problem will be fixed with the that release. 

Thanks for your great work.

**Comment by meysholdt** [comment]
yay, thank you for the feedback! :-D
