### ISSUE TITLE
Java 11+ hates some of the reflection stuff we do

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#506]
e.g.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.xtext.util.MergeableManifest (file:/C:/Users/aart/eclipse/plugins/org.eclipse.xtext.util_2.13.0.v20171005-0628.jar) to field java.util.jar.Manifest.attr
WARNING: Please consider reporting this to the maintainers of org.eclipse.xtext.util.MergeableManifest
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by cdietrich** [comment]
no news on guice side

**Comment by cdietrich** [comment]
move to 2.22

**Comment by cdietrich** [comment]
still waiting for guice fix to be released. move to 2.24

**Comment by wmanth** [comment]
Any news on that? Would be reducing the extensive use of dependency injection an option?
Some people (or is it just me?) anyway have problems understanding what's going on and how to fix things if they don't work as expected.

And obviously Guice is not a well behaving first class citizen on Java >8 anymore.

**Comment by cdietrich** [comment]
there is a guice 5 beta out containing a fix.
but that brings other problems
so it will take some time to integrate it
once it is release

see also https://github.com/eclipse/xtext-core/issues/393
you might also experiment using guice 3 noaop

**Comment by cdietrich** [comment]
as there is still no guice release: move to 2.25

**Comment by cdietrich** [comment]
as there is still no guice release: move to 2.26

**Comment by melaasar** [comment]
I think there is a release now: https://github.com/google/guice/releases/tag/5.0.1

**Comment by cdietrich** [comment]
@melaasar fee free to test with the information in https://github.com/eclipse/xtext-core/issues/393

**Comment by cdietrich** [comment]
TODO: milestone & bootstrapping test

**Comment by cdietrich** [comment]
there is also still some warnings in tycho/pde that needs tested with new version

**Comment by cdietrich** [comment]
done
