### ISSUE TITLE
[LSP] Input line to start LSP is too long

### ISSUE THREAD

**Issue by kdrozd** [eclipse/xtext-core#512]
Hi,

I have language that is in project with a bit long name (in.drozd.pdp.lang.tables) and it works as Eclipse plugin.
Now I added LSP support with wizard from 2.13 with following configuration:
* Eclipse support on
* maven build
* plain source layout
* regular LSP (not fatJar)

It works fine on macOS but on Windows 7 LSP is not starting du following errors:

> The input line is too long.
> The syntax of the command is incorrect.
> [Info  - 09:46:38] Connection to server got closed. Server will restart.
> The input line is too long.
> The syntax of the command is incorrect.
> [Info  - 09:46:38] Connection to server got closed. Server will restart.
> The input line is too long.
> The syntax of the command is incorrect.
> [Info  - 09:46:39] Connection to server got closed. Server will restart.
> The input line is too long.
> The syntax of the command is incorrect.
> [Error - 09:46:39] Connection to server got closed. Server will not be restarted.

My Configuration:
Eclipse 4.7.1a
Xtext 2.13-RC1 (tested with night builds as well)
Windows 7
Java 8

**Comment by kdrozd** [comment]
Example VSCode plugin: https://marketplace.visualstudio.com/items?itemName=krzysiekdrozd.pdp-table-definition

**Comment by kthoms** [comment]
If the start script produces a too long classpath, consider to use the Fat Jar.

**Comment by cdietrich** [comment]
i wonder what is so long. the path to the start.bat? the classpath should be handled by the gradle application plugin correct?

**Comment by kthoms** [comment]
In "Regular" format a start script is produced which lists all dependencies. When a DSL has many dependencies and stored in a deep path, tha classpath can grow long. This is a typical windows problem.
With a Fat Jar this becomes obsolete, the classpath is a single jar.

**Comment by cdietrich** [comment]
i wonder if https://issues.gradle.org/browse/GRADLE-2992 should be reopended at github.com/gradle/gradle or has already been reopened

**Comment by kdrozd** [comment]
But I use just Maven for build

**Comment by cdietrich** [comment]
@kthoms does the maven plugin we use have an option to create a `classpath` file?

**Comment by kthoms** [comment]
Please try to configure the [appassembler-maven-plugin](http://www.mojohaus.org/appassembler/appassembler-maven-plugin/assemble-mojo.html) in the IDE project:

```
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>appassembler-maven-plugin</artifactId>
				<version>1.10</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>assemble</goal>
						</goals>
						<configuration>
						   <repositoryLayout>flat</repositoryLayout>
						   <useWildcardClassPath>true</useWildcardClassPath>
						   ...

```

**Comment by kdrozd** [comment]
@kthoms Thank you this was the change I needed. 
Before class path was full (over 20 lines) like this:
./in/drozd/pdp/lang/tables/in.drozd.pdp.lang.tables.ide-org.eclipse.xtext.common.types-2.13.0.v20171013-1230.jar/1.0.0-SNAPSHOT/in.drozd.pdp.lang.tables.ide-org.eclipse.xtext.common.types-2.13.0.v20171013-1230.jar-1.0.0-SNAPSHOT.jar

Now I'm able to start and use LSP on Windows... I'll keep my CP as short as possible.

**Comment by kthoms** [comment]
Thanks for testing, I think this is a valuable change then. I will make these configuration options default.
