### ISSUE TITLE
[LSP] org.eclipse.xtext.build.Indexer - crashing

### ISSUE THREAD

**Issue by kdrozd** [eclipse/xtext-core#516]
Hi,

I have problem with `org.eclipse.xtext.build.Indexer`, few problems.

1. When LSP is started it calls `org.eclipse.xtext.build.Indexer` to index all files in my folder... including content of .git directory, why?
2. It is crashing each time I open file. First LSP starts and starts indexing... and as I've 60K+ files ind folder it takes 2.2G of RAM and 100% of CPU time.
3. With just few files (I made a copy of subset) it works just fine.

My code is in: https://github.com/kdrozd/pdp-table-definition
Example file should be a JSON file with .COL extension.

[org.eclipse.xtext.ide.server.ServerLauncher-debug.log](https://github.com/eclipse/xtext-core/files/1401244/org.eclipse.xtext.ide.server.ServerLauncher-debug.log)

**Comment by cdietrich** [comment]
do you have an example for that "big" folder as well? `org.eclipse.xtext.util.IFileSystemScanner.JavaIoFileSystemScanner` basically scans everything on the base folder

**Comment by cdietrich** [comment]
does 2. happen independently of the indexer state and if it has finished and the number of files?

**Comment by cdietrich** [comment]
i assume we still cant open files that are not yet indexed

**Comment by cdietrich** [comment]
the question is what find of crash this is. (the root cause) ist it a simple outofmemoryerror? could likely be with 60k files.

**Comment by cdietrich** [comment]
@svenefftinge we dont do any clustered builds in LSP yet. correct?

**Comment by cdietrich** [comment]
well we do clustering, but the default cluster size is all files

=>

```
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
	
	def Class<? extends IResourceClusteringPolicy> bindIResourceClusteringPolicy() {
		DynamicResourceClusteringPolicy
	}
}
```

**Comment by cdietrich** [comment]
=> @kdrozd can you retry with change module?

**Comment by svenefftinge** [comment]
No, we don't do clustered builds. Also, of course, we should have a decent default ignore behavior (e.g. `.git`).

**Comment by cdietrich** [comment]
i had a look. the build is clustered, but its disabled. same as in eclipse

**Comment by svenefftinge** [comment]
It's not just that binding. There are other things you need to adjust, too. 
Clustered builds are really the last thing to consider. I'd first try to reduce the memory footprint as much as possible.

**Comment by cdietrich** [comment]
well with 60k files: good luck

**Comment by szarnekow** [comment]
Superseded by https://github.com/eclipse/xtext/issues/2428
