### ISSUE TITLE
Only "index" AST elements when serializing / deserializing node model

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/xtext-core#521]
I can't think of any good reason why `SerializationUtil#fillIdToEObjectMap()` should "index" any EObjects other than the AST nodes created by the parser.

https://github.com/eclipse/xtext-core/blob/b43934a0efdde29a492cbba7713f1b19715b3327/org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/serialization/SerializationUtil.java#L41-L48

So I suggest to change the code so that it only processes the resource's first object and everything it contains.

**Comment by cdietrich** [comment]
Isn’t inferred stuff indexed as well?

**Comment by cdietrich** [comment]
the question is if this is used for node model only right?

**Comment by knutwannheden** [comment]
By "indexed" I mean added to the given "map" List. This method is called by the `DeserializationConversionContext` and the `SerializationConversionContext` when deserializing resp. serializing the node model. But the node model should of course only have references to the AST, so I don't see any point in "indexing" the inferred elements. It isn't wrong, but a slight unnecessary performance and (temporary) memory overhead.

**Comment by knutwannheden** [comment]
Looking at this again I just noticed that the code doesn't actually loop over the TreeIterator. Somehow I must have seen a "while" keyword on line 44 rather than an "if" :astonished:. But it does look like a rather roundabout way to access the resource's first element...

**Comment by cdietrich** [comment]
since the code works correct ill close this issue
