### ISSUE TITLE
Cannot override bindings from runtime module in ide module

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-core#524]
For GH-520, I wanted to override a binding from `DefaultRuntimeModule` in the `DefaultIdeModule`. For the `DefaultUiModule` this works, as it is combined with the runtime module using `Modules2.mixin()` in the activator of each language. Unfortunately, it doesn't work for the IDE module, as we create the injector using without mixin in the ide standalone setup, i.e.
```
Guice.createInjector(new FileAwareTestLanguageRuntimeModule(), new FileAwareTestLanguageIdeModule());
```
instead of
```
Guice.createInjector(Modules2.mixin(new FileAwareTestLanguageRuntimeModule(), new FileAwareTestLanguageIdeModule()));
```

The problem is that the IDE standalone setups are generate-once-classes and eagerly resolved by ```ResourceServiceProviderServiceLoader.loadRegistry()```. So we cannot just change the generator, and if we add such bindings *all* clients using existing ```ISetups``` will break – even the ones that just consume pre-built languages.

The only way out of this I currently see is to deprecate the `DefaultIdeModule`, and let new languages inherit from a new `NewDefaultIdeModule`and generate the correct mixin. Any other solutions?

**Comment by cdietrich** [comment]
@JanKoehnlein  i see this code generated

```
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule, new MyDslIdeModule))
	}
	
}
```

**Comment by cdietrich** [comment]
and if i have a look here: 

https://github.com/eclipse/xtext-core/blob/99f6aacbae0e57dc4a43ff28f708a28d8a1e011e/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend#L289

it was always mixin in all released versions ever

**Comment by cdietrich** [comment]
=> imho fixing the few bad places in the xtext codebase and we are fine.
users that created projects with betas cant call for api changes can they?

**Comment by JanKoehnlein** [comment]
Eclipse: https://github.com/eclipse/xtext-eclipse/pull/443
Core: https://github.com/eclipse/xtext-core/pull/523

**Comment by JanKoehnlein** [comment]
Fiexed
