### ISSUE TITLE
make sure standalone builder has same metadata than before

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#53]
The POM metadata for the standalone builder have changed. this leeds to test errors in xtext-maven

**Comment by spoenemann** [comment]
Do you mean `org.eclipse.xtext.builder.standalone`? That's an xtext-extras project.

**Comment by cdietrich** [comment]
yes i mean org.eclipse.xtext.builder.standalone (i dont know if other poms are affected as well)

**Comment by spoenemann** [comment]
Here's the dependency list of the old pom.xml:
```
org.eclipse.xtext
org.eclipse.xtext.xbase
org.eclipse.xtext.xbase.lib
org.eclipse.xtend.lib
org.eclipse.xtend.lib.macro
org.eclipse.emf.common
org.eclipse.emf.ecore
org.eclipse.emf.codegen
org.eclipse.emf.mwe2.runtime
org.eclipse.jdt.core
com.google.inject
com.google.guava
```
In our new generated pom.xml we have only
```
org.eclipse.xtext.common.types
```
which should transitively give us most of the old dependencies above, but not all of them. Which missing dependency is causing the problems? Is it jdt.core?

**Comment by spoenemann** [comment]
That doesn't answer my question. More precisely, the following dependencies are currently not covered:
```
org.eclipse.xtext.xbase
org.eclipse.emf.mwe2.runtime
```
and the following are only optional, so they're not included in the generated pom:
```
org.eclipse.emf.codegen
org.eclipse.jdt.core
```
If any of these old dependencies should be present in the pom, we should declare them as normal `compile` dependencies in the build file.

**Comment by cdietrich** [comment]
as i said: the xtext maven plugin asumes jdt and xbase are there.
for the others i cannot say. at lease the maven plugin tests dont complain.

**Comment by cdietrich** [comment]
i created https://github.com/eclipse/xtext-extras/issues/22 for that
