### ISSUE TITLE
Xtext LS does not exit if the parent process is not alive

### ISSUE THREAD

**Issue by akosyakov** [eclipse/xtext-core#552]

**Comment by cdietrich** [comment]
@akosyakov what do you exactly do. do you call the exit notification?

**Comment by akosyakov** [comment]
kill the express server with monaco for example and see the xtext ls hanging, without closing the page

**Comment by cdietrich** [comment]
hmmmm but if a third party kills processes its their fault isnt it?

**Comment by akosyakov** [comment]
not on windows

**Comment by cdietrich** [comment]
i cannot test this. how can one detect parent processes on windows? and track them?

**Comment by akosyakov** [comment]
it is the part of the LSP, see `InitializeParams.parentId`, we used to have this code before migrating to lsp4j, I cannot remember the name of the old project to look up the code

**Comment by cdietrich** [comment]
https://github.com/typefox/ls-api

**Comment by cdietrich** [comment]
and i wonder if this really should be implemented in each and every implementor of LanguageServer or if LSP4j should provider a general solution

**Comment by akosyakov** [comment]
good question, it is hardwired in vscode-jsonrpc

**Comment by akosyakov** [comment]
we can try to check similarly to java ls: https://github.com/eclipse/eclipse.jdt.ls/blob/a85b88e3d178e19a8885dd9d0c22fddf89aca83a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/LanguageServer.java#L39-L66

**Comment by cdietrich** [comment]
@svenefftinge @akosyakov how shall we proceed with this?

**Comment by svenefftinge** [comment]
We need to have that code either in Xtext or LSP4J. If in LSP4J it should be some optional thing.
Both places are fine with me.

**Comment by cdietrich** [comment]
created https://github.com/eclipse/lsp4j/issues/161

**Comment by cdietrich** [comment]
we wont fix this unless somebody provides a pr

**Comment by szarnekow** [comment]
Closing as per last comment.
