### ISSUE TITLE
TextRegionsToString handles windows line endings incorrectly

### ISSUE THREAD

**Issue by FStolte** [eclipse/xtext-core#555]
In `org.eclipse.xtext.formatting2.debug.TextRegionsToString::quote(String region, String maxLength)`, strings that exceed the maxLength are supposed to be shortened to exactly maxLength. In that case, the last three characters are also replaced with dots "...".

The dots are currently not added if there are windows line endings in the string. This also causes one test to fail when executed on a windows machine.

I already identified the cause for this problem and will be providing a fix shortly.

**Comment by cdietrich** [comment]
@kthoms  anything left for this issue?

**Comment by kthoms** [comment]
Fixed in 2.14
