### ISSUE TITLE
[LiveShadowedChunkedContainerTest] Add tests for resource rename and deletion

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#568]
Follow-up issue for #312: In [PR#523](https://github.com/eclipse/xtext-core/pull/523#pullrequestreview-81333931) it was requested to add tests for  a resource rename and resource deletion.

**Comment by JanKoehnlein** [comment]
https://github.com/eclipse/xtext-core/pull/567

**Comment by kthoms** [comment]
Thanks, Jan.
