### ISSUE TITLE
[LanguageServer] Support the case that rootPath is null

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#57]
When VS Code opens a file without opening a directory first, the language server is initialized with rootPath = null. This case should also be supported by the Xtext server (we would have a single resource then).

**Comment by cdietrich** [comment]
what happens if vscode is opened with a file?

**Comment by svenefftinge** [comment]
When rootPath is null, we don't index and start with an empty index and resourceset.
Simply waiting for didOpen notification

**Comment by spoenemann** [comment]
@svenefftinge is this already done?

**Comment by cdietrich** [comment]
imho this is still open
