### ISSUE TITLE
Fix Broken Tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#571]
http://services.typefox.io/open-source/jenkins/job/xtext-core/job/master/94/testReport/junit/

there are a few Modules2.mixin missing.
and FileAwareTestLanguageImportTest is failing cause there is no chunkedresourcedescriptions

**Comment by cdietrich** [comment]
@JanKoehnlein could you please have a look

**Comment by cdietrich** [comment]
[xtext-core.patch.txt](https://github.com/eclipse/xtext-core/files/1539471/xtext-core.patch.txt)

**Comment by cdietrich** [comment]
[xtext-core2.patch.txt](https://github.com/eclipse/xtext-core/files/1539491/xtext-core2.patch.txt)

**Comment by JanKoehnlein** [comment]
Patches are fine. Please commit. Sorry for being sloppy.

Why didn't you use a PR? That's a bit easier to review.
