### ISSUE TITLE
Deprecate old Xtext Generator

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#58]
The problem with the old generator is that it generates code wich makes use of these files:

```
xtext-eclipse/org.eclipse.xtext.ui/deprecated
└── org
    └── eclipse
        └── xtext
            └── ui
                └── editor
                    ├── contentassist
                    │   └── antlr
                    │       ├── AbstractContentAssistParser.java
                    │       ├── AbstractPartialContentAssistParser.java
                    │       ├── AntlrProposalConflictHelper.java
                    │       ├── EntryPointFinder.java
                    │       ├── FollowElement.java
                    │       ├── IContentAssistParser.java
                    │       ├── IPartialContentAssistParser.java
                    │       ├── LookAheadTerminal.java
                    │       ├── LookAheadTerminalRuleCall.java
                    │       ├── LookaheadKeyword.java
                    │       ├── ObservableXtextTokenStream.java
                    │       ├── ParserBasedContentAssistContextFactory.java
                    │       └── internal
                    │           ├── AbstractInternalContentAssistParser.java
                    │           ├── DFA.java
                    │           ├── InfiniteRecursion.java
                    │           └── Lexer.java
                    ├── reconciler
                    │   └── XtextReconcilerDebugger.java
                    └── syntaxcoloring
                        ├── DefaultSemanticHighlightingCalculator.java
                        ├── IHighlightedPositionAcceptor.java
                        ├── ISemanticHighlightingCalculator.java
                        ├── LightweightPosition.java
                        └── MergingHighlightedPositionAcceptor.java
```

These files, however, will no longer be maintained by us (I guess) and therefore deviate from the up-to-date implementation in xtext.ide.

Proposed Action:
deprecate 

```
org.eclipse.xtext.generator.Generator
org.eclipse.xtext.generator.LanguageConfig
```

in favor of 

```
org.eclipse.xtext.xtext.generator.XtextGenerator
org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage
```

To get out the clear message that migrating to the new generator infrastructure is a good idea.

**Comment by meysholdt** [comment]
#16 will cause deviation of said files

**Comment by meysholdt** [comment]
and since eclipse/xtext-eclipse#27 test coverage of said file is gone

**Comment by spoenemann** [comment]
Should we also "publish" parts of the API of the new generator? Currently there's `@noreference`, `@noextend` everywhere.

**Comment by svenefftinge** [comment]
Yes we should. AFAIK nobody has had any substantial change requests for the API so far.

**Comment by kthoms** [comment]
What has to be done for the old generator? Add @deprecated and @Deprecate on all classes and add a note into the release notes?

**Comment by spoenemann** [comment]
> Proposed Action: deprecate
> org.eclipse.xtext.generator.Generator
> org.eclipse.xtext.generator.LanguageConfig
> in favor of
> org.eclipse.xtext.xtext.generator.XtextGenerator
> org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage
> To get out the clear message that migrating to the new generator infrastructure is a good idea.

Done.

**Comment by kthoms** [comment]
Will there be a time when we will remove the old generator feature completely from the SDK and drop the dependency on Xpand? Maybe after Oxygen?

**Comment by spoenemann** [comment]
Certainly we won't do that in any Xtext 2.x version, since that would break users who haven't migrated yet. We could consider a 3.0 version where we can drop such deprecated components.

**Comment by cdietrich** [comment]
@spoenemann should the fragments be deprecated as well?

**Comment by spoenemann** [comment]
We could use the `@deprecated` Javadoc tag to add links to the new version, but I wouldn't add the `@Deprecated` annotation to all of them since you cannot use them independently of the Generator, anyway.

**Comment by kthoms** [comment]
I have added a section to the release notes.
