### ISSUE TITLE
[J9] Update to Tycho 1.1 (or later)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#596]
We need to update to tycho 1.1 (or later) once available to support J9 with tycho builds as well.

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=514471

**Comment by kthoms** [comment]
Shall we use 1.1-SNAPSHOT already? Eclipse Builds do this too.

**Comment by cdietrich** [comment]
last time i looked problem was still there with 1.1.0-SNAPSHOT so it wont help. maybe you can use it in our reference builds so we can see when its fixed

**Comment by cdietrich** [comment]
tycho change is merged and looks good. https://dev.eclipse.org/mhonarc/lists/tycho-dev/msg01488.html looks like they'll release very soon
