### ISSUE TITLE
AbstractXtextTest.setUp/tearDown does not handle Packages using each other correct

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#6]
AbstractXtextTest.setUp/tearDown does not handle Packages using each other correct

if we have multiple tests with the first test using a package and the second test using that from indirectly this will not work

```
package org.eclipse.xtext.resource.uriHell;

import org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage;
import org.eclipse.emf.ecore.xml.type.XMLTypePackage;
import org.eclipse.xtext.resource.uriHell.DemoSuite2.DemoTest;
import org.eclipse.xtext.resource.uriHell.DemoSuite2.FirstTest;
import org.eclipse.xtext.tests.AbstractXtextTests;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({ FirstTest.class, DemoTest.class, })
public class DemoSuite2 {

	public static class FirstTest extends AbstractXtextTests {

		@Test
		public void testIt() {
			XMLTypePackage p = XMLTypePackage.eINSTANCE;
		}

		@Override
		@Before
		public void setUp() throws Exception {
			super.setUp();
		}

		@Override
		@After
		public void tearDown() throws Exception {
			super.tearDown();
		}
	}

	public static class DemoTest extends AbstractXtextTests {

		@Test
		public void testIt() {
			XMLNamespacePackage p = XMLNamespacePackage.eINSTANCE;
		}

		@Override
		@Before
		public void setUp() throws Exception {
			super.setUp();
		}

		@Override
		@After
		public void tearDown() throws Exception {
			super.tearDown();
		}
	}
}
```

The Following tests were added with workaround for global state memento issues

added workaround to abstractxtexttest
org.eclipse.xtext.tests/src/org/eclipse/xtext/enumrules/GrammarParserTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/LineSeparatorHarminizerTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/AnotherInheritanceTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/InheritanceGrammarAccessTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/lazy/Bug281990Test.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/metamodelreferencing/tests/ExceptionTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/mwe/UriBasedReaderTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/ClassloaderClasspathUriResolverTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/XtextResourceSetTest.xtend
org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/impl/DefaultResourceDescription2Test.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/URIsInEcoreFilesTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java

have a look if we can get rid of them

**Comment by meysholdt** [comment]
calling 

```
XMLTypePackage.eINSTANCE
```

does *not* suffice to initialize an EPackage, because once org.eclipse.emf.ecore.xml.type.impl.XMLTypePackageImpl.isInited is set to true the the registry will never be updated agin.

instead you should do 
```
EPackage.Registry.INSTANCE.put(XMLTypePackage.eNS_URI, XMLTypePackage.eINSTANCE);
```

If an EPackage depends  on another one, you'll need to register that one first:
```
EPackage.Registry.INSTANCE.put(XMLTypePackage.eNS_URI, XMLTypePackage.eINSTANCE);
EPackage.Registry.INSTANCE.put(XMLNamespacePackage.eNS_URI, XMLNamespacePackage.eINSTANCE);
```

**Comment by meysholdt** [comment]
with that kind of registration, your tests pass for me

**Comment by cdietrich** [comment]
well the problem is the example only shows the problem.
there are some tests that load some ecore xmi which does init the XMLTypePackage.

then the tearDown will throw XMLTypePackage out of the package registry

then there are other tests that use (and thus init) XMLNamespacePackage that expect XMLTypePackageto be inside the registry but it is not.

**Comment by cdietrich** [comment]
the suite will ail if you remove the workaround from AbstractXtextTest

**Comment by cdietrich** [comment]
fixed
