### ISSUE TITLE
Regenerate Serializer Languages

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#60]
if i rerun GenerateSerializerLanguages.mwe2 i get changes.
this should be investigated

(maybe simply deleting GenerateSerializerLanguages.mwe2 and other mwe2s does the trick)

**Comment by meysholdt** [comment]
My guess is that something in the `StandaloneSetup` of `GenerateAllTestLanguages.mwe2` makes the difference.

**Comment by cdietrich** [comment]
yes. taking parts of the standalonesetup solves the problem of regenerating
