### ISSUE TITLE
[J9][wizard] Maven compiler settings

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#609]
The wizard creates Maven compiler entries as follows in the parent pom.xml:
```
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
```

These entries are not required when a Tycho-only build is used.

**Comment by cdietrich** [comment]
which version of the wizard do you use?

**Comment by cdietrich** [comment]
am getting
```
	<properties>
		<tycho-version>1.0.0</tycho-version>
		<xtextVersion>2.14.0-SNAPSHOT</xtextVersion>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>9</maven.compiler.source>
		<maven.compiler.target>9</maven.compiler.target>
	</properties>
``` 
on master

**Comment by kthoms** [comment]
You are right, the compiler settings change when J9 is selected.
Then the only issue is to remove the entries for Tycho-only builds.

**Comment by cdietrich** [comment]
i am not really sure if we should remove this. see https://eclipse.org/tycho/sitedocs/tycho-compiler-plugin/compile-mojo.html

**Comment by kthoms** [comment]
Thought that Tycho uses BREE. We should leave as is if in doubt, and does not harm.
