### ISSUE TITLE
Typo in class name AbstractLanguageServerTest$WorkspaceSymbolConfiguraiton

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#617]
Must be WorkspaceSymbolConfigura**ti**on

**Comment by cdietrich** [comment]
hmm would that be an api change?

**Comment by szarnekow** [comment]
It doesn't have a since tag so far. And there are not references to this type on github (apart from Xtext clones)

**Comment by cdietrich** [comment]
ok so id prefer a change ...

**Comment by cdietrich** [comment]
Fixed in 2.14
