### ISSUE TITLE
[J9] Consider making "ALL-SYSTEM" in tests dependent on jdt via profile

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#623]
see https://dev.eclipse.org/mhonarc/lists/tycho-user/msg07858.html (and follow ups)

this would allow building the domainmodel example and other ui-testy stuff with java 9 and java 8

**Comment by cdietrich** [comment]
idea is

have two properties

- j9stuff
- macstuff

set them via profile
have only one configuration for surefire

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
Is fixed now.
