### ISSUE TITLE
[LanguageServer] ContentAssist ignores snippets in LSP

### ISSUE THREAD

**Issue by xcariba** [eclipse/xtext-core#625]
In ContentAssistEntry there are `editPositions` field and `KIND_SNIPPET` constant. LSP4J supports snippets in `CompletionItem`, but `ContentAssistService.toCompletionItem` method does not set them. 
You can set `InsertTextFormat.Snippet` and `insertText` to use something like `${1|public,private,protected|} static ${2:void} ${3:main}()$0`. It works in VSCode and allows you to navigate using tab and shows you additional proposals, if set.

**Comment by cdietrich** [comment]
Fixed in Xtext 2.16
