### ISSUE TITLE
Wizard cannot compute Xtext version in dev mode

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#627]
Steps to reproduce:
- Create a new Xtext project with Maven build
- in the parent pom.xml there is the entry `<xtext-version>unspecified</xtext-version>`

It is expected that the `unspecified` is replaced by the current version with `-SNAPSHOT` qualifier. For releases, the qualifier is stripped.

It should be possible to derive the right version from the Manifest's Bundle-Version attribute.

**Comment by kthoms** [comment]
Yes, but it should also work in devenv, shouldn't it?

**Comment by cdietrich** [comment]
yes but you should change this only if Maven-Version returns unspecfied for the reasons i explained in the pr

**Comment by cdietrich** [comment]
Fixed in 2.14
