### ISSUE TITLE
[Grammar] Add Support for more Annotations

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#664]
In the grammar language we currently support the `@Override` annotation only. It would be nice to have support for further annotations

- `@Deprecated` for deprecated rules
- `@Final` for final rules
- `@Exported` to customize indexing
- `@Unique` and `@Pattern` for validations

We should evaluate which of these annotations we can and want to implement.

**Comment by cdietrich** [comment]
TODO: add validation (configureable, default warning) for calls do deprecated rules

**Comment by holgerschill** [comment]
Pushed two PRs about configurable issues for @Deprecated @cdietrich please have a look.
