### ISSUE TITLE
LanguageServerImpl.getAllLanguages returns duplicate results if a language supports several extensions

### ISSUE THREAD

**Issue by akosyakov** [eclipse/xtext-core#665]
As follow-up bug `ExecutableCommandRegistry.initialize` registers duplicate commands which eventually leads to troubles in `ExecutableCommandRegistry.executeCommand`

**Comment by cdietrich** [comment]
@akosyakov does a simply toSet solve the problem?

**Comment by akosyakov** [comment]
@cdietrich yes, it should do

**Comment by cdietrich** [comment]
@akosyakov could you give it a try with http://services.typefox.io/open-source/jenkins/job/xtext-core/job/cd_issue665/lastSuccessfulBuild/artifact/build/

**Comment by cdietrich** [comment]
@akosyakov with bad things you mean "32   [main] ERROR .commands.ExecutableCommandRegistry  - Multiple commands 'testlang.a' have been registered. All are executed but only one result will be send back.
" ????

**Comment by cdietrich** [comment]
Fixed in 2.14
