### ISSUE TITLE
Update wizard for xtext projects

### ISSUE THREAD

**Issue by AmatanHead** [eclipse/xtext-core#686]
Hello!

The current wizard for xtext projects generates rather outdated and sometimes invalid projects. What I've run into is old gradle version, old xtext and gradle plugin version. Intellij plugin is discontinued (xtext/xtext-gradle-plugin#112) and should be removed from the wizard. Also it would be nice to explicitly inform users about Java 9 support state and save them some hours of debugging.

**Comment by cdietrich** [comment]
Support for J9 and J10 will come with 2.14. we should make sure that the user only select BREEs that we support (no J11)
We should either remove idea from the wizard or add a big fat warning for it.

**Comment by ArneDeutsch** [comment]
@AmatanHead: Currently I have a look about the wizard. I am not sure what you refer to when you say: "What I've run into is old gradle version" ... in my version files are generated for "gradle 4.6" ... so you expect a different version?

**Comment by cdietrich** [comment]
i assume this "Old gradle" refers to the released xtext 2.13 wizard

**Comment by ArneDeutsch** [comment]
I've done the following:
-Fix case where unsupported JDK is added to the selection combo in case it is selected as a default. Instead, in the unlikely case that the default JDK is not supported, the last JDK from the list is selected.
- Remove IDEA from the new project wizard. IDE plugins are not well maintained any more, no need to bother new users with not working stuff.
- Adding "Automatic-Module-Name" to manifest if selected java version is at least 1.8.
- Set version of xtext-gradle-plugin to 1.0.21.

**Comment by cdietrich** [comment]
Fixed in 2.14. thx @ArneDeutsch
