### ISSUE TITLE
Update to LSP4J 0.4.0 / Protocol Version 3.6 

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#694]
we should consider a update to LSP4J 0.4.0 / Protocol Version 3.6 

@spoenemann @akosyakov are you going to provide a pr for this?

**Comment by spoenemann** [comment]
Hopefully this would be a one-liner (change the version number in `versions.gradle`) 😄

**Comment by cdietrich** [comment]
does languageserverimpl need adoptions for new services?

**Comment by spoenemann** [comment]
Maybe, but those can be implemented in different PRs. In LSP every service offered by a language server is optional.

**Comment by cdietrich** [comment]
Fixed in 2.14
