### ISSUE TITLE
[wizard] Outdated dependency to LSP4J

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#705]
The generated pom.xml for org.xtext.example.mydsl.ide contains

```xml
<dependency>
	<groupId>org.eclipse.lsp4j</groupId>
	<artifactId>org.eclipse.lsp4j</artifactId>
	<version>0.2.1</version>
</dependency>
```

when Eclipse plugin and Language Server are selected in the wizard.

The version is outdated: we have been using LSP4J 0.3.0, and I switched to 0.4.0-SNAPSHOT in #701.

Is this dependency really necessary? It should be covered transitively by org.eclipse.xtext.ide.

I cannot test whether the redundant dependency can be removed due to #704.

**Comment by cdietrich** [comment]
cc @kthoms

**Comment by spoenemann** [comment]
The Maven build works without the redundant dependency. Haven't tested the Language Server at runtime, though.

**Comment by cdietrich** [comment]
did you have a look at the built app? does it contain lsp4j?

**Comment by cdietrich** [comment]
will push an updated version for monday

**Comment by cdietrich** [comment]
TODO: find a cleaner way to manage this. at lease at a comment to the versions.gradle to update this place too.

**Comment by cdietrich** [comment]
@kthoms do you have any ideas?

**Comment by kthoms** [comment]
I would like to script such updates, also for Tycho and others. It is error-prone and time consuming nowadays to do any update. We should be able to manage versions and URLs at a central place and modify sources automatically.

As a first step, we should document the list of files that are affected by certain updates.

**Comment by cdietrich** [comment]
for this particular  dependency there should be already a comment

https://github.com/eclipse/xtext-core/blob/24ce555b09204a1ca71e27ed48ac89a57629e73a/gradle/versions.gradle#L12

**Comment by spoenemann** [comment]
We could move such versions to a properties file? That's very easy to update with a Gradle build task and very easy to read from Java.

**Comment by cdietrich** [comment]
could be unsolveable this way once we have a bom

**Comment by cdietrich** [comment]
i think we should close this as wontfix
