### ISSUE TITLE
Refactor FileSystemAccessQueue to synchronize read/write of IO operations

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-core#709]
This ticket is a result out of the following review: https://github.com/eclipse/xtext-core/pull/696#pullrequestreview-113965707

Currently the FileSystemAccessQueue has a mathod to wait for the requestQueue to be empty. Such the read operations can wait until all write operations are ready. It would be desirable to wait only for the write operations that are affecting folders/files the read operation want to access. On the other hand write operations should wait until all reads are ready.

To implement this FileSystemAccessRequest probably need to know what folder/file is affected by the operation. A new field of type "Path" qould do. But there are quite a lot if issues to solve here. It is not sufficient to just check if the pathes are equal. Deleting a directory also affects all contained files. In result the logic to add requests and wait for termination might become quite complicated. Also it might be a source of deadlocks and needs a carefull design.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext/issues/2265

**Comment by szarnekow** [comment]
Closed since there is already a ticket in https://github.com/eclipse/xtext
