### ISSUE TITLE
XtextVersionTests#getCurrent fails for non-snapshot version on Gradle

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#715]
The test case fails when the project's version is a non-snapshot version and the build is executed with Gradle. In Eclipse the test performs. Project version was set to `2.14.0.RC1`.

**Comment by cdietrich** [comment]
Do you have an error message or trace?

**Comment by cdietrich** [comment]
@kthoms so the versions in manifest are not adoped?

**Comment by szarnekow** [comment]
+1

**Comment by cdietrich** [comment]
how shall we proceed?

**Comment by kthoms** [comment]
+1 delete the test, I will provide the PR

**Comment by cdietrich** [comment]
@kthoms don't forget to PR

**Comment by cdietrich** [comment]
Fixed in 2.15. thx @kthoms
