### ISSUE TITLE
Wrong ConfigurableIssueCodesProvider generated for Xbase languages

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#722]
The ValidatorFragment2 now generates a DSL ConfigurableIssueCodesProvider and the corresponding Guice binding, but it always generate it as a subclass of ConfigurableIssueCodesProvider; this breaks Xbase languages: in this case XbaseConfigurableIssueCodes should be used as the superclass.

For example, if you regenerate the domain model example, some validation tests fail (the one related to imports), and the log shows:

```
0    [main] ERROR se.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.xbase.validation.IssueCodes.import_wildcard_deprecated' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
```

I was wondering if this generation should take place at all for Xbase languages.
If it has to be generated, it should extend XbaseConfigurableIssueCodes and make sure to call super.initialize.

Or am I missing something?

**Comment by cdietrich** [comment]
@holgerschill could you please have a look

**Comment by cdietrich** [comment]
@LorenzoBettini is a bug in the fragment imho

**Comment by LorenzoBettini** [comment]
For sure it's a bug, but I was wondering how to fix this... I can take care of that, in case.

For the domain model it's either redefine the binding so that it uses the Xbase one

```
	override bindConfigurableIssueCodesProvider() {
		XbaseConfigurableIssueCodes
	}
```

or redefine the binding and point to a custom implementation, based on the generated one, but with the right superclass and the right call to super method:

```
/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.domainmodel.validation;

import org.eclipse.xtext.preferences.PreferenceKey;
import org.eclipse.xtext.util.IAcceptor;
import org.eclipse.xtext.validation.SeverityConverter;
import org.eclipse.xtext.xbase.validation.XbaseConfigurableIssueCodes;

@SuppressWarnings("restriction")
public class CustomConfigurableIssueCodesProvider extends XbaseConfigurableIssueCodes {
	protected static final String ISSUE_CODE_PREFIX = "org.eclipse.xtext.example.domainmodel.";

	public static final String DEPRECATED_MODEL_PART = ISSUE_CODE_PREFIX + "deprecatedModelPart";

	@Override
	protected void initialize(IAcceptor<PreferenceKey> acceptor) {
		super.initialize(acceptor);
		acceptor.accept(create(DEPRECATED_MODEL_PART, SeverityConverter.SEVERITY_WARNING));
	}
}
```

**Comment by holgerschill** [comment]
Hi Lorenzo, thanks for your help. Will care next week. It‘s a bug for sure. Just forgot that case with Xbase. Cheers, Holger

**Comment by LorenzoBettini** [comment]
in general, Xbase language should not need such a binding, if I understand correctly...

**Comment by holgerschill** [comment]
Fix and tests are in PR: https://github.com/eclipse/xtext-core/pull/723
