### ISSUE TITLE
Compile Error in maven with Validation Preference Page

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#724]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.2.0-SNAPSHOT:compile (default-compile) on project org.xtext.example.mydsl3.ui: Compilation failure: Compilation failure: 
[ERROR] /home/dietrich/xtext-master/ws/org.xtext.example.mydsl3.parent/org.xtext.example.mydsl3.ui/src-gen/org/xtext/example/mydsl3/validation/MyDslValidatorConfigurationBlock.java:[22] 
[ERROR] 	super.fillSettingsPage(composite, nColumns, defaultIndent);
[ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Cannot directly invoke the abstract method fillSettingsPage(Composite, int, int) for the type AbstractValidatorConfigurationBlock
[ERROR] /home/dietrich/xtext-master/ws/org.xtext.example.mydsl3.parent/org.xtext.example.mydsl3.ui/src-gen/org/xtext/example/mydsl3/validation/MyDslValidatorConfigurationBlock.java:[41] 
[ERROR] 	super.validateSettings(changedKey, oldValue, newValue);
[ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Cannot directly invoke the abstract method validateSettings(String, String, String) for the type OptionsConfigurationBlock
[ERROR] 2 problems (2 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.xtext.example.mydsl3.ui

**Comment by cdietrich** [comment]
@holgerschill is this related to your changes?

**Comment by cdietrich** [comment]
i am not sure why this deprecation stuff is generated at all if not used

**Comment by cdietrich** [comment]
Fixed in 2.14

**Comment by holgerschill** [comment]
Fixed
