### ISSUE TITLE
[wizard] Missing JUnit 5 in created target platform

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#732]
Create project with setting:
- Java 1.8
- Eclipse Plug-in
- Testing JUnit 5
- Build System Maven

Perform mvn install on parent POM.

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.xtext.example.mydsl.tests 1.0.0.qualifier
[ERROR]   Missing requirement: org.xtext.example.mydsl.tests 1.0.0.qualifier requires 'bundle org.junit.jupiter.api 5.1.0' but it could not be found
```

**Comment by kthoms** [comment]
Actually it is the Xtext update site that should contain the JUnit 5 bundles from Orbit

**Comment by cdietrich** [comment]
does that automatically trigger an installation? i am not sure if it is a god idea to install junit5 on luna

**Comment by kthoms** [comment]
I'm pretty sure it won't cause an installation. But to be sure we have to put it on nightly and install Xtext on Luna. Can do this tomorrow.

**Comment by kthoms** [comment]
Sounds good. There are already other orbit bundles in the category.xml, this should make that obsolete.

**Comment by cdietrich** [comment]
@dhuebner we already did that in the past (include orbit stuff)

**Comment by cdietrich** [comment]
so you npropose to dadapt the xtext composite?

**Comment by dhuebner** [comment]
@cdietrich We did it in the past and got a lot of problems.
First what comes in my mind are re-signed orbit bundles problem. Second, we loosed a  control over available Update sites ->  bundles  during a tycho build: conflicting guava versions etc.

**Comment by kthoms** [comment]
Agree with @dhuebner , better idea to add an orbit entry to the target def
