### ISSUE TITLE
add 32 bit environments to parent pom

### ISSUE THREAD

**Issue by nittka** [eclipse/xtext-core#74]
The new project wizard creates a parent pom with only 64 bit architecture environments (https://github.com/eclipse/xtext-core/blob/e1a4782403497dd27f73276c409049a3d3ecdcf9/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend#L289).

When creating an Xtext project for maven, an install on a 32 bit system fails due to a "cryptic" error in the UI project (NoClassDefFound PlatformUI).

**Comment by meysholdt** [comment]
could you enumerate the OperatingSystems / WindowSystems / Architectures you would like to see there?

**Comment by LorenzoBettini** [comment]
I had already proposed a change with that respect (before repo splitting) https://github.com/eclipse/xtext/pull/1012 and bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=492648 but it was decided to "won't fix"

**Comment by meysholdt** [comment]
`fails due to a "cryptic" error in the UI project` (Alex) and `that test will fail with some kind of obscure error which is not easy to track` (Lorenzo) does not sound like good user experience :(

@nittka what OS are you using?

**Comment by LorenzoBettini** [comment]
@meysholdt that's why I had proposed the change ;)

**Comment by nittka** [comment]
At home, I use Win7 with 32 bit java.

I am with @LorenzoBettini here. This ticket is an exact duplicate of his bugzilla and his pull request is already in place. I'd have said "duplicate all three 64-bit versions as 32 as well" (not knowing about the Mac support). I understand that keeping poms small is an issue, but in this case my feeling is that a freshly created project not building outweighs that argument.

Granted, adding an environment is easily done, but arriving at the point that the problem "is" a missing environment in the parent pom is a totally different matter. When encountering the problem an googling for the cryptic error message (why can't the maven build find PlatformUI - starting the Application from Eclipse works after all, so what the heck is wrong), you have to have luck to run across a search result mentioning the environment and not ignore it; mostly it's "add dependencies to your target platform" which is not the problem at all...

**Comment by cdietrich** [comment]
since platform will no longer support 32 bit in 4.10 (2018-12) and later we will close this as wontfix
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536766
