### ISSUE TITLE
[wizard] Improve tycho-surefire-plugin plugin management

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#741]
The test project created by the wizard configures the tycho-surefire-plugin. With #623 the tycho-surefire-plugin has been added to the parent pom's pluginManagement section.

This makes it unnecessary to configure the version in the test project again. A warning is raised currently:

![screenshot 118](https://user-images.githubusercontent.com/265597/40185964-3f09931e-59f4-11e8-829a-eaf5444e4b7a.png)

Since the plugin is already managed, also the `failIfNoTests` setting can already be configured in the parent pom.

**Comment by kthoms** [comment]
Fixed for 2.14 via https://github.com/eclipse/xtext-core/commit/0d895884126e0405f4f2ba22835e6df5a07148bc

**Comment by cdietrich** [comment]
is this done or not?

**Comment by kthoms** [comment]
It is done.
