### ISSUE TITLE
[JUnit5] Relax dependencies to 5.0.0

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#742]
On Oxygen only JUnit 5.0.0 is available by default. When someone uses Oxygen with Xtext 2.14 and "Running Platform" as target, then the requirement `org.junit.jupiter.api` can't be fulfilled.

Also the `org.eclipse.xtext.testing` bundle requires this bundle in version 5.1.0, but optionally. 

Actually there are no technical restrictions to require at least 5.1, everything does work with 5.0 also. Therefore I would like to relax the constraints.

![screenshot 120](https://user-images.githubusercontent.com/265597/40188144-8b5b7c32-59f9-11e8-9988-d5a4254a6963.png)

**Comment by cdietrich** [comment]
i am not sure what bad side effects this has. e.g. the lauch whatever stuff

**Comment by kthoms** [comment]
I think it is just wrong currently. There is no limitation to use 5.0. Actually the feature was initially developed for it.

**Comment by cdietrich** [comment]
I just want to make sure this is tried before done

**Comment by kthoms** [comment]
Fixed via https://github.com/eclipse/xtext-core/commit/1b8d74a8a768226e39f0b6b4a5dd11d80df6cf71
