### ISSUE TITLE
UI tests not detected

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-core#746]
Create a new Xtext project with the new project wizard. Use eclipse photon (probably not of relevance) and JUnit 4. Delect maven as build engine. Use plain source folder layout and generate test projects.

After generting the projects create a UI test. You can for example use this code:

```
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.junit.Test;
import org.junit.runner.RunWith;

@InjectWith(MyDslUiInjectorProvider.class)
@RunWith(XtextRunner.class)
public class TTT {
	@Test
	public void testName() throws Exception {
		System.out.println(ResourcesPlugin.getWorkspace().getDescription());
	}
}
```
Build with maven (install). You can observe that the eclipse workbench opens for a UI test. But the test is actually not executed.

Output:
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

Expected:
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

**Comment by cdietrich** [comment]
That looks bad. Can you compare config with domain model example

**Comment by cdietrich** [comment]
I will try myself when at home

**Comment by cdietrich** [comment]
Is it possible that is the import package bs require bundle thing. That do we have now

**Comment by szarnekow** [comment]
Isn’t it the case that mvb builds scan tests for name patterns, eg suffic Test or PluginTest?

**Comment by cdietrich** [comment]
Yes please try this too

**Comment by ArneDeutsch** [comment]
Yes, my fault. It was the naming issue (I like maven each day less ;) ).
