### ISSUE TITLE
[releng] Xcore broken

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-core#759]
Just installed Xtext and Xcore from the Xtext releases repository. Xcore does not work:

```
org.eclipse.core.runtime.CoreException: Failed to create injector for org.eclipse.emf.ecore.xcore.Xcore (occurred in org.eclipse.emf.ecore.xcore.ui.XcoreExecutableExtensionFactory)
...
Caused by: com.google.inject.CreationException: Guice creation errors:

1) No implementation for org.eclipse.xtext.builder.EclipseSourceFolderProvider was bound.
  while locating org.eclipse.xtext.builder.EclipseSourceFolderProvider
    for field at org.eclipse.xtext.xbase.ui.hover.XbaseHoverDocumentationProvider.sourceFolderProvider(Unknown Source)
  at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)

```

**Comment by cdietrich** [comment]
i am not aware of this issue @merks are you?

**Comment by cdietrich** [comment]
but i am also not aware of any changes in that place. and there is a binding in DefaultXbaseUiModule.

**Comment by cdietrich** [comment]
@JanKoehnlein which xcore version did you install from where

**Comment by cdietrich** [comment]
i am not sure which emf version is bundled in your composite. it might be really old.

**Comment by cdietrich** [comment]
the newest xcore stuff on the composite http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/ is from 2015 which is hopelessly outdated

**Comment by cdietrich** [comment]
http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/compositeContent.xml
includes http://download.eclipse.org/modeling/emf/emf/updates/2.10.x/

**Comment by JanKoehnlein** [comment]
Yes, I can confirm that. Now using Xcore from Photon.

**Comment by cdietrich** [comment]
=> i propose to either remove emf from the composite or use the new emf release composite
or additionally add it

**Comment by JanKoehnlein** [comment]
Agreed. @dhuebner what do you think?

**Comment by cdietrich** [comment]
new releases update site is  http://download.eclipse.org/modeling/emf/emf/builds/release
cc @kthoms

**Comment by merks** [comment]
Note that the update sites are documented here:

http://download.eclipse.org/modeling/emf/emf/builds/index.html

The Photon version is of course the latest milestone currently.  The latest release is what was released for Oxygen and will become the Photon version later this month.

**Comment by kthoms** [comment]
If we would include the EMF composite release site, accessing our composite release site with p2 would slow down again and be PITA. So including a concrete EMF release (or 2) would be better IMHO. We can use the new sites.
Just tell me what exactly has to be done and I can arrange this then.

**Comment by cdietrich** [comment]
well i am not sure. if we did a take all in the past we should do it in the future.
otherwise we should complete remove emf from the xtext update site

**Comment by kthoms** [comment]
We would have to test if Xtext installs fine with just using the Composite without EMF then, also for some older Xtext versions and on older platforms.

**Comment by cdietrich** [comment]
arggg of course it wont install if you do not have another update site that has emf .
the question was why this was not assumed before.

**Comment by cdietrich** [comment]
and if you ask for old versions then we have to add the new emf composite anyway ....

**Comment by cdietrich** [comment]
and if people care about performance they should not use the xtext composite anyway.
but the specific emf, xtext, mwe and xpand sites.
=> i dont see the problem with using the composite emf

**Comment by kthoms** [comment]
You usually have the Eclipse Release update site enabled, which contains EMF.

**Comment by JanKoehnlein** [comment]
My issue was that I was trying to install Xtext 2.14 and there was no compatible Xcore anywhere.
I use the Xtext repo mainly to install Xtext versions that are not on the release train.

**Comment by cdietrich** [comment]
wasnt the issue that you used the xtext update site to install xcore?

**Comment by JanKoehnlein** [comment]
Yes, because I expected the compatible version to be there as well. 
It was extremely outdated instead.

**Comment by kthoms** [comment]
FYI: On a plain vanilla Photon IDE Xtext 2.9 and 2.14 are installable without problems. No EMF repo involved (just using releases/photon)

![screenshot 163](https://user-images.githubusercontent.com/265597/41152575-580ac4ce-6b14-11e8-8036-654e862d9208.png)
![screenshot 164](https://user-images.githubusercontent.com/265597/41152576-58222c36-6b14-11e8-84f3-e40dcc3fb602.png)

**Comment by cdietrich** [comment]
that was clear. but it wont help if you select stuff from the xtext composite site

**Comment by dhuebner** [comment]
We should think about removing EMF from the composite Update site

**Comment by cdietrich** [comment]
Am not sure which clients (target platforms) this may break

**Comment by dhuebner** [comment]
Almost all TP I saw, use eclipse update site as well. So I think only some will break 
Also the most people figured out that the xtext composite update site is very slow and switched to plain release sites.

**Comment by merks** [comment]
If you're going to point to an EMF update site (that includes Xcore) from your composite please use http://download.eclipse.org/modeling/emf/emf/builds/release or http://download.eclipse.org/modeling/emf/emf/builds/milestone

**Comment by cdietrich** [comment]
we decided to use the new emf composite update site.
analogous http://download.eclipse.org/modeling/tmf/xtext/updates/composite/nightly/compositeContent.xml should use http://download.eclipse.org/modeling/emf/emf/builds/nightly/latest

**Comment by cdietrich** [comment]
@kthoms can we consider that as fixed?

**Comment by kthoms** [comment]
Yes, should be done.

**Comment by kthoms** [comment]
Related PR xtext/xtext-p2-orbit#21 was not merged yet

**Comment by kthoms** [comment]
Now it should be done
