### ISSUE TITLE
Cache Annotation/Checkmode in MethodWrapper

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#790]
```org.eclipse.xtext.validation.AbstractDeclarativeValidator.MethodWrapper.invoke(State)```
should cache the annotation instead of recomputing it each time.

the callers of createMethodWrapper should have it anyway

**Comment by cdietrich** [comment]
@szarnekow how "api" is that code?

**Comment by szarnekow** [comment]
> how "api" is that code?
What's your plan? It's certainly not on the obvious API surface.

**Comment by cdietrich** [comment]
See pull request. I initiale planend to pass the annotation to the constructor but that is not needed
