### ISSUE TITLE
[junit5] InjectionExtension not working with `@BeforeEach`

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#795]
The InjectionExtension implements `BeforeTestExecutionCallback`and `AfterTestExecutionCallback`. These lifecycle methods are called _after_ any user method. This does not work when a user defines a `@BeforeEach` method and expects that fields are injected before.

Instead, InjectionExtension has to implement `Before/AfterEachCallback`.

The following test will fail:
```
@InjectWith(MyDslInjectorProvider.class)
@ExtendWith(InjectionExtension.class)
public class InjectionExtensionTest  {
	@Inject Injector injector;
	
	@BeforeEach
	public void setUp () {
		assertNotNull(injector);
	}
}
```

**Comment by cdietrich** [comment]
did you test that with junit4?

**Comment by kthoms** [comment]
Why JU4? BeforeEach and InjectionExtension is JU5 only.

**Comment by cdietrich** [comment]
I just what both to be aligned

**Comment by szarnekow** [comment]
Indeed a Junit4 test with `@Before` and `@After` would be great. The registry should still have the "test"-state in the after method and injected stuff should be available in the before method.

**Comment by kthoms** [comment]
I'm not sure if there is something to align here. The InjectionExtension's equivalent is XtextRunner. I don't think something has to change there.

**Comment by kthoms** [comment]
Ah, did not see @szarnekow 's comment before. I could have a look at XtextRunnerTest to align it.

**Comment by kthoms** [comment]
Added `@Before` test to XtextRunnerTest.
