### ISSUE TITLE
[gradle] Make Maven repository setup parameterizable

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#8]
Using additional parameters (e.g. environment variables?) the build should be able to
 * deploy the Maven artifacts into a given local directory,
 * pull dependencies from a given local directory.

When deploying locally, signing should probably be skipped.

**Comment by spoenemann** [comment]
@meysholdt: Did you work in a65917c fix this?

**Comment by meysholdt** [comment]
yes
