### ISSUE TITLE
[ls] Diagnostics generated during the LS initialization can never arrive to the client

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#800]
Because it is not yet ready, we are just initializing the LS. A related discussion is here: https://github.com/theia-ide/theia/issues/2422

**Comment by cdietrich** [comment]
have never experienced this with vscode.

**Comment by Rajsmit** [comment]
I am also experiencing this issue and as per analysis the client is not ready to receive message until server sends back the initializeResult with capability. 
The initial build shoud be started once we receive the Initialized even, then client can get all the diagnostic that is reported during initial build.

**Comment by cdietrich** [comment]
@dhuebner is this fixed now?
