### ISSUE TITLE
[ls] Support the semantic highlighting with the Xtext LS

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#812]
There is a proposed LSP extension for the semantic highlighting here: https://github.com/Microsoft/vscode-languageserver-node/pull/367.

I would like to start working on the Xtext LS part.

**Comment by kittaakos** [comment]
Depends on https://github.com/eclipse/xtext-core/issues/813.

**Comment by cdietrich** [comment]
thx @kittaakos for your contribution

**Comment by kuniss** [comment]
@kittaakos Do you know whether this works already with the latest language server protocol implementation provided with vscode 1.43.0?

**Comment by kittaakos** [comment]
> @kittaakos Do you know whether this works already with the latest language server protocol implementation provided with vscode 1.43.0?

I do not know; probably no.
