### ISSUE TITLE
[ls] Cannot build xtext-core with LSP4J 0.5.0 dependency

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#813]
There was a [Code Action related API](https://github.com/eclipse/lsp4j/commit/378e4e49b3e78e75623fab313b27c5c17c846388) change. I will take care of it.

**Comment by cdietrich** [comment]
this looks like a duplicate of https://github.com/eclipse/xtext-core/issues/793

**Comment by kittaakos** [comment]
It is, sorry for the noise.
