### ISSUE TITLE
Project/File Wizard: plugin.xml contribution

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#816]
Unlike other contributions, the project wizard creates spaces instead of tabs. This should be harmonized.

Further, the template provider's class should be prefixed with the extension factory.

Same issue for the file wizard.

![screenshot 285](https://user-images.githubusercontent.com/265597/44217854-b46d2780-a178-11e8-8c9d-48e5b9edcfa6.png)

**Comment by cdietrich** [comment]
@kthoms @ArneDeutsch do you kknow why we dont use executable extension factory?

**Comment by kthoms** [comment]
I think it was forgotten. We stumbled over this when we wanted to used `@Inject` in a template provider in a customer project.

**Comment by cdietrich** [comment]
Fixed in 2.15
