### ISSUE TITLE
[LS] Support for new/changed features in lsp4j 0.5

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#821]
we should investigate if/how we want to support new/changed features in lsp4j 0.5

- Command / Action
- Outline / Document Symbol https://github.com/eclipse/xtext-core/issues/858
- Folding

(check for others)

**Comment by dhuebner** [comment]
@cdietrich Are there already concrete plans to extend the  ICodeActionService to support `CodeAction` ?

**Comment by cdietrich** [comment]
unless you or @kittaakos dont provide anything: no

**Comment by dhuebner** [comment]
@cdietrich 
The changes around the CodeAction will simplify the implementation a lot. We will figure out who and when can do it

**Comment by dhuebner** [comment]
Link to the corresponding documentation: 
https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction

**Comment by kthoms** [comment]
It would be sufficient to provide separate PRs and reference this issue. The issue will be resolved when all LSP 0.5 features are supported.

**Comment by dhuebner** [comment]
Regarding the CodeAction, the fix that @kittaakos  did in https://github.com/eclipse/xtext-core/pull/815/files#diff-b63a430ae1f0796570037b39d1f135a3R24 would already work for me.

**Comment by cdietrich** [comment]
@dhuebner this is not about beeing compilable but to actually use the new api

**Comment by kittaakos** [comment]
> Document Symbol

I would like to make some contribution to support the hierarchical document symbols in the Xtext LS. That feature does not have its own GH ticket, and I would like to avoid stepping on somebody's toes and the do the work twice. Do I have the green light for that?

 - https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol
 - "_The client support hierarchical document symbols._"
 - "_[...] Document symbols can be hierarchical and they have two ranges [...]_"
 - `TextDocumentClientCapabilities.documentSymbol.hierarchicalDocumentSymbolSupport`
 - The API is already [available in LSP4J](https://github.com/eclipse/lsp4j/blob/02ddbda6e65d23a7f31c7eaf6f7e81263d2ecc8c/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L463) (`0.5.0`).

**Comment by cdietrich** [comment]
@kittaakos can you create a second issue for that. then i can link it above.
currently nobody from itemis side is working on this so unless you dont step on dennis toes we are fine

**Comment by cdietrich** [comment]
created https://github.com/eclipse/xtext-core/issues/897 for folding
@kittaakos has provided an impl for outline
