### ISSUE TITLE
ConfigurableIssueCodesProvider generated even when no grammar annotations are used

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-core#825]
Found in the nigthly of Xtext 2.15.0. I have a customer project where I define my own `ConfigurableIssueCodesProvider` for the language CFG. But building the language l end up with two classes `CFGConfigurableIssueCodesProvider` and two tries to bind them.
I would propose two changes:
1. Generate a less dangerous name ... e.g. `CFGDeclarativeIssueCodesProvider`.
2. (not sure if best solution) ... disable the generation bz default. Of course then thr user has to opt-in to use the annotations ... not sure what is more important here. Backward compatibility or ease of use ...

**Comment by cdietrich** [comment]
maybe default false and "on" with wizard?

**Comment by holgerschill** [comment]
Or looking for usage of the annotations and only then generate the stuff.

**Comment by holgerschill** [comment]
Current default is true.

**Comment by holgerschill** [comment]
maybe default false and "on" with wizard? -> sounds good. Should I do that @cdietrich ?

**Comment by szarnekow** [comment]
👍

**Comment by cdietrich** [comment]
@holgerschill is this fixed now?

**Comment by holgerschill** [comment]
Yes

**Comment by holgerschill** [comment]
Fixed in 2.15
