### ISSUE TITLE
Make CliProjectsCreator executable

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#849]
To make the CliProjectsCreator usable as CLI tool to create Xtext projects, it could become a main class with appropriate command line interface and main method.

This will help to scaffold projects with a simple interface.

**Comment by cdietrich** [comment]
for args4j https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17418

**Comment by cdietrich** [comment]
@kthoms this is fixed and delivered with 2.15 correct?

**Comment by kthoms** [comment]
Correct, added with 2.15.
