### ISSUE TITLE
[LS] Support the hierarchical document symbols

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-core#858]
Part of the issue description was copied from [here](
https://github.com/eclipse/xtext-core/issues/821#issuecomment-418292716).

 - https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol
 - "_The client support hierarchical document symbols._"
 - "_[...] Document symbols can be hierarchical and they have two ranges [...]_"
 - `TextDocumentClientCapabilities.documentSymbol.hierarchicalDocumentSymbolSupport`
 - The API is already [available in LSP4J](https://github.com/eclipse/lsp4j/blob/02ddbda6e65d23a7f31c7eaf6f7e81263d2ecc8c/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L463) (`0.5.0`).

**Comment by cdietrich** [comment]
it would be nice if the api could be designed in a way that is independent from lsp so that the same implementation can be used in eclipse and lsp via adapters
