### ISSUE TITLE
[JUnit] Check against JUnit 5.3.1 for Eclipse 2018-12

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#867]
We have to make sure to use the new JUnit version when available in Orbit.

---------- Forwarded message ----------
From: Noopur Gupta <noopur_gupta@in.ibm.com>
Date: 2018-09-12 12:25 GMT+02:00
Subject: [orbit-dev] Replace JUnit 5.1 with JUnit 5.3.1
To: orbit-dev@eclipse.org

Hello,

The JDT project is planning to add JUnit 5.3.1 into Orbit and remove
the older JUnit 5.1 in master branch for Eclipse 2018-12 M1. [1]

Please respond to this note if there are any objections in replacing
JUnit 5.1 with JUnit 5.3.1.

Regards,
Noopur

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=538925

**Comment by cdietrich** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17855

**Comment by cdietrich** [comment]
@kthoms do you think we should increase minimal versions in gradle and manifests as well?

**Comment by kthoms** [comment]
I don't think so, since it would disallow to use that on Oxygen. We do not rely on a specific JUnit 5 version with the extension.

**Comment by cdietrich** [comment]
We ship junit with our Update sure don’t we

**Comment by cdietrich** [comment]
but which version should we use in gradle/maven?

**Comment by cdietrich** [comment]
(and in the target platform)

**Comment by kthoms** [comment]
Maven/Gradle is fine with 5.3.1, also for latest target def. But Oxygen/Photon targets stay as is.
