### ISSUE TITLE
Review Eclipse Metadata of Testing

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#88]
To get xtend tests running i had to change the eclipse metadata in META-INF/MANIFEST.MF

 https://github.com/eclipse/xtext-core/commit/5738a92b8615fd8cc68b0abb23a3ceefd1b5cfc2 
and subsequent commits
we should get a clean state before we release it as api

**Comment by cdietrich** [comment]
having 'log4j': '1.2.16', in gradle is bogus too leads to additional test failures in maven tycho i think

**Comment by spoenemann** [comment]
I had a look at the manifest and it looks good to me. Is there anything left to do here? Any concrete problem?

**Comment by cdietrich** [comment]
There is the bug Moritz created about the pde dependency

**Comment by spoenemann** [comment]
Link?

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-eclipse/issues/91

**Comment by spoenemann** [comment]
But that has nothing to do with xtext.testing from xtext-core, right? Can we close this one?

**Comment by cdietrich** [comment]
yes
