### ISSUE TITLE
Xtext 2.15.0 generates projects with old 2.14.0 dependencies:

### ISSUE THREAD

**Issue by colameo** [eclipse/xtext-core#884]
**With Xtext 2.15.0 generated project:**

![_org_eclipse_xtend_lib_and_ws_-_org_xtext_example_mydsl1_meta-inf_manifest_mf_-__users_serano_development_eclipse_4_8_eclipse-jhipster_ws_-_eclipse_ide](https://user-images.githubusercontent.com/629760/46262283-63827a00-c4ff-11e8-8878-ae1a87d28622.jpg)

**Comment by cdietrich** [comment]
Duplicates https://github.com/eclipse/xtext-core/issues/859

**Comment by cdietrich** [comment]
since we cannot control if we use new features that were introduce with 2.15 (or 2.16) we should bump this version to 2.16 (or at best read the version programmatically as we do it at other places)

**Comment by cdietrich** [comment]
works as intended
