### ISSUE TITLE
[LSP] Ignore didChangeWatchedFiles for open documents

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-core#888]
The language server should ignore file change events for documents that are opened in an editor.

**Comment by svenefftinge** [comment]
Yes, it should be ignored as well.

**Comment by cdietrich** [comment]
Sure? What do clients send on delete? Just make sure the server recognizes deletes

**Comment by svenefftinge** [comment]
When a document is open it overlays the file version. Only when it gets closed the language server should update with the contents from the file system again.

**Comment by cdietrich** [comment]
@dhuebner is this fixed now?

**Comment by dhuebner** [comment]
@cdietrich Yes

**Comment by cdietrich** [comment]
thx @dhuebner
