### ISSUE TITLE
[LSP] Update to LSP4J 0.6.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#893]

**Comment by kthoms** [comment]
I'd prefer that the LSP4J 0.6 support would be prepared on a separate branch until the release version is available. In other words: Do not have a snapshot dependency on master.

**Comment by cdietrich** [comment]
@spoenemann @kittaakos is there already a release timeline for that. we plan to release Xtext on Dec. 4th

**Comment by kittaakos** [comment]
2018-11-30 is the planned date release for `0.6.0.`.

See: https://projects.eclipse.org/projects/technology.lsp4j.

**Comment by cdietrich** [comment]
Fixed
