### ISSUE TITLE
[LSP] Implement Folding

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#897]
- Implement Service
  - Would be nice if the actual impl would be free of LSP4J classes and similar to the eclipse api
  - so that it can be adapted in both eclipse and lsp4j
- Test Service (implement folding in lsp test lang & write a test for it, maybe adapt AbstractLanguageServerTest)

**Comment by cdietrich** [comment]
cc @lievenlemiengre

**Comment by cdietrich** [comment]
@tivervac @lievenlemiengre will move this to Xtext 2.17

**Comment by cdietrich** [comment]
@tivervac @lievenlemiengre any updates on this?

**Comment by tivervac** [comment]
@cdietrich Will come back to this next week when Lieven is available again.

**Comment by lievenlemiengre** [comment]
@cdietrich Currently I have no time to do this, it's on our roadmap to migrate to the new API but currently it doesn't have a high priority.

**Comment by miklossy** [comment]
@drkstr101 will take a look at this issue.

**Comment by drkstr101** [comment]
I am just chiming in to say this is now my current task for today. I am still digesting the issue but will report back with my plan of action once I have one.

Cheers all!

**Comment by miklossy** [comment]
@cdietrich Could you list some bullet points here to divide the task into small consecutive steps?

**Comment by drkstr101** [comment]
@miklossy Is my understanding correct that the goal is is to refactor the [Code Folding](https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#folding) feature from something.ui into something.ide?

**Comment by miklossy** [comment]
@cdietrich Could you help me answering this question?

**Comment by cdietrich** [comment]
No. This is about having a new infrastructure in ide that consists of two parts.
A service impl that is independent from lsp and thus can be easily adapted to the eclipse api
And an adaptation to lsp in language server impl

**Comment by drkstr101** [comment]
@miklossy I have no problem digging my teeth into this, but I hope you realize I will need a lot of hand holding so it may not end up saving you all that much time in the end. I would be happy to try and see what kind of progress I can make on this front as long as the expectations are clear.

**Comment by cdietrich** [comment]
There are other good first issues. These are much more restricted and may not be as rewarding and demanding as this one. I cannot judge what kind of tasks you prefer

**Comment by drkstr101** [comment]
@cdietrich @miklossy  I figured this may be the case. It may be a good idea to get a few smaller tasks under my belt first. I would like to get a bit more familiar with the code base before I start making artifactual decisions such as this task would require.

That being said, I am not afraid of the challenge if you feel this would be a more valuable contribution of my time.

**Comment by Darkgaja** [comment]
@cdietrich I will take on this issue. You'll receive a PR later today probably.

**Comment by cdietrich** [comment]
move to 2.26
