### ISSUE TITLE
Exception when executing MWE2 on Homeautomation Example in MergeableManifest2

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-core#918]
The replacement of MergeableManifest developed in #864 does not yet work flawless. Creating the Homeautomation Example and executing the MWE2 workflow produces an exception.

> [ERROR]: GeneratorException: (Element: -UNKNOWN-; Reported by: XtextGenerator)
> 	 java.io.IOException: Line is to long 'Export-Package: org.eclipse.xtext.example.homeautomation.ruleEngine.util,org.eclipse.xtext.example.homeautomation.ruleEngine,org.eclipse.xtext.example.homeautomation.ruleEngine.impl,org.eclipse.xtext.example.homeautomation,org.eclipse.xtext.example.homeautomation.parser.antlr.lexer,org.eclipse.xtext.example.homeautomation.parser.antlr.internal,org.eclipse.xtext.example.homeautomation.validation,org.eclipse.xtext.example.homeautomation.jvmmodel,org.eclipse.xtext.example.homeautomation.scoping,org.eclipse.xtext.example.homeautomation.serializer,org.eclipse.xtext.example.homeautomation.parser.antlr,org.eclipse.xtext.example.homeautomation.services,org.eclipse.xtext.example.homeautomation.formatting2'
> 	at org.eclipse.xtext.util.MergeableManifest2.readHeader(MergeableManifest2.java:116)
> 	at org.eclipse.xtext.util.MergeableManifest2.read(MergeableManifest2.java:100)
> 	at org.eclipse.xtext.util.MergeableManifest2.read(MergeableManifest2.java:96)
> 	at org.eclipse.xtext.util.MergeableManifest2.<init>(MergeableManifest2.java:66)
> 	at org.eclipse.xtext.xtext.generator.XtextGenerator.mergeManifest(XtextGenerator.java:365)
> 	at org.eclipse.xtext.xtext.generator.XtextGenerator.generateManifests(XtextGenerator.java:340)
> 	at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:245)
> 	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:132)
> 	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
> 	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:212)
> 	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:37)
> 	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:20)
> 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
> 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
> 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
> 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
> 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
> 
> 	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.handleIssues(Mwe2Bridge.java:59)
> 	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:51)
> 	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:212)
> 	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:37)
> 	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:20)
> 	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
> 	... 4 more

**Comment by cdietrich** [comment]
@ArneDeutsch is this fixed now?

**Comment by ArneDeutsch** [comment]
Right now jenkins has test failure. Most probably because of line ending issue. Should be fixed with latest comit.

**Comment by cdietrich** [comment]
same problem with domainmodel example

**Comment by ArneDeutsch** [comment]
Fixed.
