### ISSUE TITLE
[LSP] API of ICodeActionService has no access to WorkspaceManager

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#923]
the current API work ICodeActionService looks like

`def List<Either<Command, CodeAction>> getCodeActions(Document document, XtextResource resource, CodeActionParams params, CancelIndicator indicator)`

as you can see the implementer of code actions has no access to the `WorkspaceManager`

lets compare it with the `IRenameService` API

`def WorkspaceEdit rename(WorkspaceManager workspaceManager, RenameParams renameParams, CancelIndicator cancelIndicator)`

One usecase for CodeActions is Quickfixes. Lets asume we have a model that looks like an enhanced Greeting example and a model like this

```
Hello xtext!
Hello Quickfix from xtext!
```

Then lets assume we want to offer a (one pass) code action that fixes the lower case `xtext` to upper case `Xtext`. that would be a perfect fit to use the change serializer as the Rename Service does, unfortunately i need a `WorkspaceManager` to do so.

(see attached file)

@svenefftinge @kittaakos @dhuebner what do you think? do i overlook something? should we change the api? should we add a ICodeActionServiceExtension?

**Comment by cdietrich** [comment]
[MyDslCodeActionService.xtend.txt](https://github.com/eclipse/xtext-core/files/2518283/MyDslCodeActionService.xtend.txt)

**Comment by cdietrich** [comment]
org.eclipse.xtext.ide.tests.testlanguage.ide.server.CodeActionService.recordWorkspaceEdit(Document, XtextResource, IModification<Resource>) tricks around that by not using manager at all (and e.g. ignoring dirty state)

**Comment by dhuebner** [comment]
@cdietrich Adding access to the resources did make sense at least from the point we added CodeAction as return type. I'm not quite sure that it should be the `WorkspaceManager` class because the only method being called is `doRead(URI uri, (Document, XtextResource)=>T work)` For me it  looks more like a kind of `IResourceAccess` is needed. However I would prefer an extension interface.

**Comment by cdietrich** [comment]
hmm the workspace manager is already part of the change serializer api

**Comment by svenefftinge** [comment]
We also have `ILanguageServerAccess` which also provides the underlying Document. 
Maybe we should add an `ILspDocumentAccess` that only has the `doRead` method and have ILanguageServerAccess extend it.

**Comment by svenefftinge** [comment]
The `WorkspaceManager` should not be exposed into APIs as it is now. I.e. the usage in the change serializer should indeed be replaced with something that only has the doRead method.

**Comment by JanKoehnlein** [comment]
Since #1084 the ILanguageServerAccess now exposes a method to create a new resource set that is configured in the right way to calculate text edits using the change serializer API. We should got he same way as for rename refactoring and add a new interface using the ILanguageServerAccess.

**Comment by cdietrich** [comment]
yes that would be nice
