### ISSUE TITLE
Formatting2: auto-wrap in lines prior to currently processed one.  

### ISSUE THREAD

**Issue by torstenkraemer** [eclipse/xtext-core#97]
I stumbled upon this odd behaviour while writing the formatter for N4JS:  
If for whatever reason the current line exceeds the line-length and auto-wrapping is not able to find a wrapping-point in this line to fix the length, it 
will continue to search backwards in the file until it finds another auto-wrap point and does the wrapping there. 

C.f. the following Xpect-test currently disabled by FIXME keyword:
https://github.com/NumberFour/n4js/blob/0dd81984dfdbd41143f2bace4b11f6dee7235d51/tests/eu.numberfour.n4js.xpect.tests/model/formatter2/x_annotations_long_wrapping_problem.n4js.xt

**Comment by meysholdt** [comment]
I will take a look.

**Comment by kduske-n4** [comment]
@meysholdt I have created a "minimal" example to demonstrate the problem based on the domain model example. See [branch "Xtext-97" of my repository](https://github.com/kduske-n4/DomainModel/tree/Xtext-97), specifically the changes in [this commit](https://github.com/kduske-n4/DomainModel/commit/3a51fa6247ec857265e1b5bb5dbe51d25a739573).

Hope this helps!

**Comment by kduske-n4** [comment]
Please also see [this commit](https://github.com/kduske-n4/DomainModel/commit/41581ba767414d592560e325d9ad30311f3691c3), where the expectation is changed such that the test actually fails ;-).

**Comment by meysholdt** [comment]
@kduske-n4 thank you for the example!
