### ISSUE TITLE
Adapt to Potential LSP4J snapshots builder server move

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#975]
https://github.com/eclipse/lsp4j/issues/290

**Comment by kthoms** [comment]
lsp4j JIPP location: https://ci.eclipse.org/lsp4j/job/lsp4j-snapshots/lastSuccessfulBuild/artifact/build-result/p2.repository/

**Comment by kthoms** [comment]
The above location does not contain the latest build yet.

**Comment by cdietrich** [comment]
mitigated by not using snapshots

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/lsp4j/issues/331

**Comment by cdietrich** [comment]
still nothing done. as a mitigation we have our own job

**Comment by szarnekow** [comment]
I'll close this for now since we have the workaround that is mentioned in https://github.com/eclipse-lsp4j/lsp4j/issues/331
