### ISSUE TITLE
DiagnosticConverterImpl: Make message customizable

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#983]
In a special use case we want to customize the message for produced issues that differ from the diagnostic's message (to be specific: the diagnostic's data carries an exception and the message should contain the exception type and even stack trace).

The creation of diagnostics from exceptions therefore should be customizable.

**Comment by kthoms** [comment]
CC @fabtagon

**Comment by cdietrich** [comment]
@kthoms anything left

**Comment by kthoms** [comment]
DiagnosticConverterImpl contains now `getMessage()` methods, which can be overridden by a customized class.
