### ISSUE TITLE
Register multiple language server extensions independent of language registration

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/xtext-core#989]
Hi, I want to register multiple language server extensions and languages in the same language server.
Currently I register my languages and the extensions same as seen in [yang-lsp](https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/io.typefox.yang.diagram/src/main/java/io/typefox/yang/diagram/YangServerLauncher.xtend). However binding multiple IdeLanguageServerExtensions or ILanguageServerExtensions is problematic. Currently I solve this by overriding the `createInjector()` method of different language, but this is destined to produce new problems in the future.
My language and extension registration looks something like this:
```
newMyLang1IdeSetup {
    override createInjector() {
        Guice.createInjector(Modules2.mixin(new MyLang1RuntimeModule, new MyLang1IdeModule, new Stuff1Module))
    }
}.createInjectorAndDoEMFRegistration()
new MyLang2IdeSetup {
    override createInjector() {
        Guice.createInjector(Modules2.mixin(new MyLang2RuntimeModule, new MyLang2IdeModule, new Stuff2Module))
    }
}.createInjectorAndDoEMFRegistration()
```
If I understand correctly this creates child injectors for each language that are used to register my extension commands. Each implemented ILanguageServerExtension has no access to the other ones.
Is there a more elegant way to register these extensions that does no depend on the language registration?

**Comment by cdietrich** [comment]
hi i am not sure if i understand your problem. xtext service loader will load all languages anncounced via ISetup 
can you please explain?

**Comment by soerendomroes** [comment]
I want to register additional LSP messages that are implemented by extending `ILanguageServerExtension` independent of the languages I register. How can I do that?

**Comment by cdietrich** [comment]
cc @svenefftinge

**Comment by soerendomroes** [comment]
I found a solution to register one extension (I will test it with multiple) independent of the language:
```
val launcher = new Builder<LanguageClient>()
                .setLocalServices(#[languageServer, regExtension])
                .setRemoteInterface(LanguageClient)
                .setInput(in)
                .setOutput(out)
                .setExecutorService(threadPool)
                .wrapMessages([it])
                .configureGson(configureGson)
                .setClassLoader(this.getClass.classLoader)
                .create();
```
`regExtension` is a `ILanguageServerExtension` and languageServer the `LanguageServerImpl`.
Doing this `val launcher = Launcher.createIoLauncher(#[languageServer, regExtension], LanguageClient, in, out, threadPool, [it], configureGson)` does not work.
