### ISSUE TITLE
[Wizard] Gradle: Remove Deployment to Local Repo

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#991]
We remove the convenice generation of maven deployment into gradle.
if users want to they can configure the gradle maven or gradle publishing plugins themselves

**Comment by kthoms** [comment]
The wizard creates a `maven-deployment.gradle` file. This makes use of the deprecated `maven` Gradle plugin. We decided to drop this feature and make the wizard to not generate and use this file.

**Comment by cdietrich** [comment]
@kthoms is this fixed?

**Comment by kthoms** [comment]
Fixed in 2.17
