### ISSUE TITLE
Initialize method of ILanguageServerExtension only called if registered together with language

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/xtext-core#997]
The `initialize` method of a `ILanguageServerExtension` is only called, if the implementing class is registered together with a language (meaning such as in the following example):
```
new MyLangIdeSetup {
    override createInjector() {
        Guice.createInjector(Modules2.mixin(new MyLangRuntimeModule, new MyLangIdeModule, new MyModule))
    }
}.createInjectorAndDoEMFRegistration()
```
In this example `MyModule` extends on `IdeDiagramModule` and binds a `IdeLanguageServerExtension` (similar to [`YangDiagramModule`](https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/io.typefox.yang.diagram/src/main/java/io/typefox/yang/diagram/YangDiagramModule.xtend) which needs an initialized `languageServerAccess`. However doing this does not register the IdeLanguageServerExtension at the injector, so I cannot inject it into another `ILanguageServerExtension` (what would be great).

Currently I try to register all my extensions via the `localServices` field in the `Launcher`.
Is there any particular reason not to call `initialize` if the extension is not registered via a language?

**Comment by cdietrich** [comment]
i assume this is cause the place is not under control from the xtext LanguageServerImpl.

**Comment by svenefftinge** [comment]
> However doing this does not register the IdeLanguageServerExtension at the injector, so I cannot inject it into another ILanguageServerExtension (what would be great).

I am not sure I understand this bit. Do you mean a different injector than the one that is created through `createInjector` from the code above?

**Comment by soerendomroes** [comment]
Yes, I figure that is one of the problems I have here. I want to register multiple languages like this: 
```
new MyLang1IdeSetup {
    override createInjector() {
        Guice.createInjector(Modules2.mixin(new MyLang1RuntimeModule, new MyLang1IdeModule))
    }
}.createInjectorAndDoEMFRegistration()
new MyLang2IdeSetup {
    override createInjector() {
        Guice.createInjector(Modules2.mixin(new MyLang2RuntimeModule, new MyLang2IdeModule))
    }
}.createInjectorAndDoEMFRegistration()
```
My `ILanguageServerExtensions` are not language dependent and I cannot register them all together with a language (see the example above). I plan to register them at the `Launcher` like this:
```
val launcher = new Builder<LanguageClient>()
                .setLocalServices(#[languageServer, iLanguageServerExtension1, iLanguageServerExtension2])
                .setRemoteInterface(LanguageClient)
                .setInput(in)
                .setOutput(out)
                .setExecutorService(threadPool)
                .wrapMessages([it])
                .configureGson(configureGson)
                .setClassLoader(this.getClass.classLoader)
                .create();
```
One of them however is a [DiagramLanguageServerExtension](https://github.com/theia-ide/sprotty/blob/master/server/xtext-diagram/src/main/java/io/typefox/sprotty/server/xtext/DiagramLanguageServerExtension.xtend), which needs to be initialized. Therefore, I register it together with the languages. This causes the problems, described earlier, since this is not the same `injector` and I create multiple ones by registering the languages.

**Comment by soerendomroes** [comment]
I think initializing other localServices is not possible in the `LanguageServerImpl`.
